### ISSUE TITLE
how to realize to apply-cmvn-online?

### ISSUE THREAD

**Issue by liuchenbaidu** [pykaldi/pykaldi#100]
there is apply-cmvn-online in kaldi,how to realize it in pykaldi.
i want to find something in doc.but i don't get it.

**Comment by JerryPeng21cuhk** [comment]
It is an executable so you can not find it in doc and there is no corresponding script in pykaldi. You need to realize it by hand. There are several good examples in kaldi-style-executables directory. You can imitate the coding style to develop your scripts. Whenever you meet trouble in invoking pykaldi's functions, try search in its doc. If you still can not find out, then search the corresponding **kaldi's function** in pykaldi's github code. There are .clif files which provide the mapping from kaldi's functions to pykaldi's.

**Comment by dogancan** [comment]
@liuchenbaidu Note that pykaldi does not include equivalents of kaldi executables. If you need the functionality provided by a kaldi executable, I suggest you use that executable. You can use the table readers in kaldi.util.table along with read specifiers to read the output of kaldi pipelines, e.g.

```python
from kaldi.util.table import SequentialMatrixReader

feats_rspecifier = (
    "ark:compute-mfcc-feats --config=mfcc.conf scp:wav.scp ark:-"
    " | apply-cmvn-sliding --cmn-window=10000 --center=true ark:- ark:-"
    " | add-deltas ark:- ark:- |"
    )

for key, feats in SequentialMatrixReader(feats_rspecifier):
    # feats: CMVN normalized mfcc + delta + delta-delta features
```

Note that you need to add the kaldi executables to your PATH for above code to work. 

I suggest you read the IO mechanisms in kaldi and pykaldi. If you understand how extended filenames and read/write specifiers work in kaldi and pykaldi, you will be able to do most of the standard kaldi things without implementing them in python. There are many examples of these in kaldi and pykaldi repositories.

**Comment by liuchenbaidu** [comment]
@dogancan you are clever and give the best answer i want.
