### ISSUE TITLE
Any example for xvector by pykaldi?

### ISSUE THREAD

**Issue by ybdesire** [pykaldi/pykaldi#101]
I noticed that xvector code has been merged into kaldi (https://github.com/kaldi-asr/kaldi/pull/1896/).

Can we use pykaldi for xvector extraction ? Any example for xvector ?

**Comment by ybdesire** [comment]
More details for xvector to kaldi here: https://david-ryan-snyder.github.io/2017/10/04/model_sre16_v2.html

**Comment by dogancan** [comment]
> Can we use pykaldi for xvector extraction ? Any example for xvector ?

Technically yes, but practically no. For inference, you would have to reimplement the functionality of high-level executables like nnet3-xvector-compute using low level functions and classes provided by PyKaldi. This is not a trivial task but certainly doable if you have a good understanding of xvector code in Kaldi. For training, you would have to reimplement everything in that PR, so definitely not something easy to do. If you need to train xvector models, I recommend using the recipes provided by Kaldi. Note that PyKaldi is not a replacement for Kaldi. The goal of PyKaldi project is to enable development in Python, not replicate the functionality of Kaldi executables or scripts.

**Comment by ybdesire** [comment]
Got that. Thanks @dogancan for the details.   :)

**Comment by dogancan** [comment]
You're welcome. I am closing this issue but feel free to reopen it if you have additional questions.

**Comment by lalimili6** [comment]
@dogancan 
Hi
Is it possible to use xvector models by pykaldi?
what abut I-vector extractor model and plda?
I mean only use x-vector extractor and extract vectors?

**Comment by vrmpx** [comment]
yes it is possible but not recommended. It would require reimplementing the high level functionality provided by kaldi executables using low level pykaldi functions and classes.

**Comment by lalimili6** [comment]
> You would have to read and understand how relevant kaldi executables work and replicate them in python using pykaldi

Thanks
any example of "relevant kaldi executables"?
