### ISSUE TITLE
there is a question in getting fbank_pitch feature between pykaldi and kaldi

### ISSUE THREAD

**Issue by liuchenbaidu** [pykaldi/pykaldi#103]
1.use kaldi to get fbank_pitch feature as C
fbank_feats="ark:compute-fbank-feats $vtln_opts --verbose=2 --config=$fbank_config scp,p:$logdir/wav.JOB.scp ark:- |"
 pitch_feats="ark,s,cs:compute-kaldi-pitch-feats --verbose=2 --config=$pitch_config scp,p:$logdir/wav.JOB.scp ark:- | process-kaldi-pitch-feats $postprocess_config_opt ark:- ark:- |"

paste-feats --length-tolerance=$paste_length_tolerance "$fbank_feats" "$pitch_feats" ark:- \| \
    copy-feats --compress=$compress $write_num_frames_opt ark:- \

2.use kaldi to get fbank_pitch feature as feat

3.then use
result=approx_equal(C,feat,0.1)
the result is False,Is C different from feat?tol is 0.1 so big.

**Comment by dogancan** [comment]
In general, they should be very similar. Since they are different -- 0.1 tolerance is indeed large --, I am guessing your Python code is doing something different from Kaldi executables. Make sure you are using the same feature extraction options in both cases. Also, the Python code you shared in the other thread was averaging the two audio channels prior to feature extraction. Kaldi executables choose one of the channels based on the command line options.

**Comment by liuchenbaidu** [comment]
How much tolerance is similar?

my python code : 
kaldi.matrix.set_printoptions(5)

    #Create FBANK
    fbank_opts = FbankOptions()
    fbank_opts.frame_opts.samp_freq = 16000.00
    fbank_opts.mel_opts.num_bins=80

    fbank_opts.frame_opts.dither = 0.0  #add by 20190318

    sf_fbank = fbank_opts.frame_opts.samp_freq
    fbank=Fbank(fbank_opts)

    if TestFlag==False:
        wavedata=WaveData()
    # inp=Input("test.wav")
        inp = Input(f_wavename)

        wavedata.read(inp.stream())
        s3=wavedata.data()
    else:
        s3=wavedata.data()
    s3 = s3[:,::int(wavedata.samp_freq / sf_fbank)]
    m3 = SubVector(mean(s3, axis=0))
    f3=fbank.compute_features(m3,sf_fbank,1.00)
    #print f3.shape

    ####make_pitch_feature
    pitch_opts = PitchExtractionOptions()
    #pitch_opts.samp_freq=16000.0
    pitch_opts.resample_freq=16000.0
    feat_pitch=compute_kaldi_pitch(pitch_opts,m3)
    processpitchoptions=ProcessPitchOptions()
    f_pitch=process_pitch(processpitchoptions,feat_pitch)
    #print f_pitch.shape

    #C = Matrix(142,83)
    C = Matrix(f3.num_rows,83)

    C[:,:80]=f3
    C[:,80:]=f_pitch

    cmvn=Cmvn(83)
    cmvn.read_stats("cmvn.ark")
    cmvn.apply(C,norm_vars=True)

**Comment by dogancan** [comment]
Maybe something like 0.01, definitely smaller than 0.1. I don't understand what is happening in your Python code. You are taking average of two channels it seems, which is different from Kaldi executables. Why are you averaging them? Also, you are setting a bunch of options to non-standard values. Why? Are you also setting them in this way when running Kaldi executables? Also, you are reading CMVN stats from an archive file which is probably wrong.

**Comment by liuchenbaidu** [comment]
> Also, the Python code you shared in the other thread was averaging the two audio channels prior to feature extraction. Kaldi executables choose one of the channels based on the command line options.

what should i do one of the channels in pykaldi.

**Comment by dogancan** [comment]
What does that mean? I'm saying you are averaging them in your code. Why are you doing that?

**Comment by liuchenbaidu** [comment]
Are you referring to these codes?
m3 = SubVector(mean(s3, axis=0))

**Comment by dogancan** [comment]
Yes.

**Comment by liuchenbaidu** [comment]
I learn from the example of pykaldi mfcc. i want to delete mean,but how to do it.

**Comment by dogancan** [comment]
If you want to choose the first channel, it would be something like
```
m3 = s3[0,:]
```
The example you copied from is doing all kinds of non-standard things. That is not how standard features are computed in Kaldi. [This script](https://github.com/pykaldi/pykaldi/blob/master/examples/scripts/kaldi-style-executables/compute-mfcc-feats/compute-mfcc-feats.py) is a much better example for feature extraction.

**Comment by liuchenbaidu** [comment]
ok,thanks

> Also, you are reading CMVN stats from an archive file which is probably wrong.
how to reading CMVN stats?

**Comment by dogancan** [comment]
The code you have is trying to read the stats from a file with extension ark. If that file is indeed an archive file, then that is not correct. What you need to provide is a file containing a stats matrix not a stats matrix inside a Kaldi archive file. See my [earlier answer](https://github.com/pykaldi/pykaldi/issues/92#issuecomment-474059836).

From the questions you have been asking, I am gathering that you do not understand how Kaldi works. Note that you won't be able to make progress with PyKaldi unless you understand how Kaldi does the things you are trying to achieve. You need to start reading Kaldi documentation and code to see how everything comes together. Asking questions every time you get stuck is not a scalable strategy.

**Comment by liuchenbaidu** [comment]
1.use kaldi to get fbank_pitch feature as C
fbank_feats="ark:compute-fbank-feats $vtln_opts --verbose=2 --config=$fbank_config scp,p:$logdir/wav.JOB.scp ark:- |"
pitch_feats="ark,s,cs:compute-kaldi-pitch-feats --verbose=2 --config=$pitch_config scp,p:$logdir/wav.JOB.scp ark:- | process-kaldi-pitch-feats $postprocess_config_opt ark:- ark:- |"

paste-feats --length-tolerance=$paste_length_tolerance "$fbank_feats" "$pitch_feats" ark:- | 
copy-feats --compress=$compress $write_num_frames_opt ark:- \

2.use pykaldi
#Create FBANK
fbank_opts = FbankOptions()
fbank_opts.frame_opts.samp_freq = 16000.00
fbank_opts.mel_opts.num_bins=80


sf_fbank = fbank_opts.frame_opts.samp_freq
fbank=Fbank(fbank_opts)

if TestFlag==False:
    wavedata=WaveData()
# inp=Input("test.wav")
    inp = Input(f_wavename)

    wavedata.read(inp.stream())
    s3=wavedata.data()
else:
    s3=wavedata.data()
s3 = s3[:,::int(wavedata.samp_freq / sf_fbank)]
m3 =s3[0,:]
f3=fbank.compute_features(m3,sf_fbank,1.00)
#print f3.shape

####make_pitch_feature
pitch_opts = PitchExtractionOptions()
#pitch_opts.samp_freq=16000.0
pitch_opts.resample_freq=16000.0
feat_pitch=compute_kaldi_pitch(pitch_opts,m3)
processpitchoptions=ProcessPitchOptions()
f_pitch=process_pitch(processpitchoptions,feat_pitch)
#print f_pitch.shape

#C = Matrix(142,83)
C = Matrix(f3.num_rows,83)

C[:,:80]=f3
C[:,80:]=f_pitch

cmvn=Cmvn(83)
cmvn.read_stats("cmvn.ark")
cmvn.apply(C,norm_vars=True)

3.result=approx_equal(C,feat,0.01)
result is false

**Comment by liuchenbaidu** [comment]
> The code you have is trying to read the stats from a file with extension ark. If that file is indeed an archive file, then that is not correct. What you need to provide is a file containing a stats matrix not a stats matrix inside a Kaldi archive file. See my [earlier answer](https://github.com/pykaldi/pykaldi/issues/92#issuecomment-474059836).
> 
> From the questions you have been asking, I am gathering that you do not understand how Kaldi works. Note that you won't be able to make progress with PyKaldi unless you understand how Kaldi does the things you are trying to achieve. You need to start reading Kaldi documentation and code to see how everything comes together. Asking questions every time you get stuck is not a scalable strategy.

the cmvn.ark is use compute-cmvn-stats to generate cmvn.ark in kaldi.
