### ISSUE TITLE
About disabling post processing in kaldi

### ISSUE THREAD

**Issue by eracube** [pykaldi/pykaldi#105]
Hello there, 
Firstly many thanks for making this available in python. I am trying to extract hesitation <ah, um, uh> and disfluencies using pykaldi asr. It seems to me that there is some post processing step done in SequentialMatrixReader as it is trying to replace hesitations with some random words. I would be very glad if you could advise me to disable post-processing of the transcriptions. 

Thanks.

**Comment by dogancan** [comment]
> It seems to me that there is some post processing step done in SequentialMatrixReader as it is trying to replace hesitations with some random words.

I don’t follow. Where did you see a post processing step in SequentialMatrixReader? Also, I don’t understand how matrix reader is related to transcripts. How are you obtaining the transcripts? Could you copy and paste your code so I can see what you are trying to do?

**Comment by vrmpx** [comment]
I am closing this issue due to no follow-up. But feel free to re-open it anytime.
