### ISSUE TITLE
Resource to Learn how to write a feat_rspecifier??

### ISSUE THREAD

**Issue by Anwarvic** [pykaldi/pykaldi#108]
Hi Mr. Dogan,

In the past few days, I was trying to create a GMM/HMM model using pyKaldi and I found the script named `gmm-recognizer.py` in the `examples` directory. And I came across the part where you have created `feat_rspecifier`, and I couldn't understand how did you create this pipeline?
And I get that every line in the pipeline is just a binary file inside `kaldi\src\featbin` directory.

So, my question is that are there any resources that I could look at that would help me understand how to create/modify these pipelines??

I hope you get this sooner than later as I'm pretty desperate !!

**Comment by dogancan** [comment]
> And I came across the part where you have created `feat_rspecifier`, and I couldn't understand how did you create this pipeline? And I get that every line in the pipeline is just a binary file inside `kaldi\src\featbin` directory.

What is it exactly that you couldn't understand? The feature pipelines are simply unix pipelines. They include calls to a number of Kaldi executables for feature extraction, normalization, etc.

Kaldi documentation and example setups in Kaldi repo are good resources for learning more about these pipelines and Kaldi I/O mechanisms.

**Comment by Anwarvic** [comment]
In the previous example, you have used `compute-mfcc-feats`, `apply-cmvn-sliding`, and `add-deltas`... right?? Is there a good resource where I could learn more about these Kadli executables and others??

**Comment by dogancan** [comment]
I am not sure if I understand your question. The best resources for learning more about these executables are [kaldi documentation](http://kaldi-asr.org/doc), [example setups in kaldi repo](https://github.com/kaldi-asr/kaldi/tree/master/egs) and the help messages printed when you run these executables.

**Comment by Anwarvic** [comment]
My mistake... I was asking about the kaldi executables and that is not related to pyKaldi.. so sorry about that. You can close this issue if you want!!

But let me ask you a question and tell me if I'm wrong, the following is the pipeline that you have used in `examples/scripts/asr/gmm-recognizer.py`:
```
 "ark:compute-mfcc-feats --config=mfcc.conf scp:wav.scp ark:-"
    " | apply-cmvn-sliding --cmn-window=10000 --center=true ark:- ark:-"
    " | add-deltas ark:- ark:- |"
```
In this pipeline you have used three Kaldi executables.. right?? You have used `compute-mfcc-feats`, `apply-cmvn-sliding` and `add-deltas`. Till now, I think we can agree on that!!

At first, this was meaningless to me!! But after a while, I found out that this is exactly what happens when I trained my model. Let's take this `run.sh` script taken from [Kaldi for dummies tutorial](http://kaldi-asr.org/doc/kaldi_for_dummies.html). This shell script when it extracted features, it runs:

- `make_mfcc.sh`: which is similar to `compute-mfcc-feats` (AS I THINK).
- `steps/compute_cmvn_stats.sh`: which is similar to `apply-cmvn-sliding` responsible for feature normalization.
- Then, it runs `train_mono.sh`. When I opened it, I found out that the pipeline in it uses `add-deltas`.

Am I right with my conclusions till now???

**Comment by vrmpx** [comment]
Jumping into this conversation...
The pipeline in `gmm-recognizer.py` is not to be used for training. It assumes that a model was trained using Kaldi's recipes (e.g., by following the tutorial you linked). Specifically, see [this line in gmm-recognizer](https://github.com/pykaldi/pykaldi/blob/3f19b029d42c4a3fc250c9fb82e7ddba859be25b/examples/scripts/asr/gmm-recognizer.py#L17). Pykaldi is just taking the previously trained model as an input. That is were the differences between the two scripts are coming from: one is training a model, ours is only applying the trained model.

**Comment by Anwarvic** [comment]
@vrmpx, of course, I know that the pipeline in `gmm_recognizer.py` is not for training. But it's used to mimic the same preprocessing that is done while training. For example, extracting features, normalizing and adding delta. My question was is this pipeline (the one used in `gmm_recognizer.py` is the same as the pipeline made in training which was done using `make_mfcc.sh` in order to extract features, `compute_cmbn_stats.sh`in order to normalize the features and `train_mono.sh` to add the delta??

Anyway, thanks @vrmpx for jumping into the conversation :)

**Comment by vrmpx** [comment]
The pipeline in `gmm-recognizer.py` is not exactly the same as the one used in training but it is a good substitute which does not require 2 pass feature normalization. We are using sliding cmvn, instead of regular cmvn, in the `gmm-recognizer` example script because the goal is to demonstrate recognizer workflow, not mimic kaldi feature extraction pipeline. Regular cmvn is a two pass operation. It requires computing cmvn stats for each utterance and feeding those into apply-cmvn, which makes the example script unnecessarily complicated and we wanted to avoid that. The feature pipeline in `gmm-recognizer` is just an example, and should be treated as such, and it is to [this pipeline in kaldi's decode](https://github.com/kaldi-asr/kaldi/blob/master/egs/wsj/s5/steps/decode.sh#L97).

**Comment by vrmpx** [comment]
I am closing this issue but feel free to re-open or add to it.
