### ISSUE TITLE
Upstream with Kaldi repository

### ISSUE THREAD

**Issue by ar13pit** [pykaldi/pykaldi#110]
Hello,

When I checked the specified version of Kaldi to be used with pykaldi, I saw that it differs by just 2 commits in `src/cudamatrix/cu-vector.cc` and `src/cudamatrix/cu-packed-matrix.cc`.

However I don't see a requirement of CUDA to use pykaldi so why can't it be used with the upstream repository of Kaldi, as stated in the README?

If those 2 commits are absolutely necessary then why are they not being merged into Kaldi, because github compare shows no issues with such merge.

**Comment by vrmpx** [comment]
Hi ar13pit,

The differences between our kaldi repo and the upstream kaldi are not limited to cudamatrix. There are other changes we had to implement (e.g., adding accessor methods or refactoring function headers). You can check all the differences [in this list](https://github.com/kaldi-asr/kaldi/compare/master...pykaldi:pykaldi).

**Comment by ar13pit** [comment]
Hi vrmpx,

Indeed I see the differences now. I was comparing the master branches instead of comparing the pykaldi branch with upstream master.

May be it will be good to update the urls in the README for both Kaldi and CLIF to the pykaldi branches of the repository trees as the current urls are linked to the default branches which do not intuitively imply that the branch to be cloned is not master.
