### ISSUE TITLE
Is there a way to produce an `ark:loglikes.ark` from nnet

### ISSUE THREAD

**Issue by davidavdav** [pykaldi/pykaldi#113]
Hello,

Thanks for making this awesome interface to Kaldi.  

This [example](https://github.com/pykaldi/pykaldi/blob/master/examples/scripts/asr/mapped-loglikes-recognizer.py) show how you can decode from having precomputed loglikes.  

Is there a way one can obtain these loglikes efficiently, using pykaldi, from a plain Kaldi nnet3/online setup?  I know the standard Kaldi access to log_likelihoods is one value at the time, probably for good reasons, but not very efficient for nnet likelihoods:
```python
    d = asr._decodable
    feat_pipeline.accept_waveform(wav.samp_freq, wav.data()[0])                                       
    ## slow
    for i in range(d.num_frames_ready()):
        for j in range(d.num_indices()):
            ll[i, j] = d.log_likelihood(i, j)                                                                
```

The reason I ask is that in our application we work with computations over the loglikes matrix. 

Up to now we've defined our own c++ decodable `DecodableNnet3LoopedOnline` with the essential export function
```c++
SubVector<BaseFloat> DecodableNnet3LoopedOnline::getLogLikelihoods(int32 subsampled_frame) {
  EnsureFrameIsComputed(subsampled_frame);
  return current_log_post_.Row(subsampled_frame - current_log_post_subsampled_offset_);
}
```
but having our own c++ decodable around isn't very easy to maintain, and lacking pykaldi support.  And pykaldi seems to be exactly what we've been looking for in the past years...

**Comment by vrmpx** [comment]
Do you need to produce these log likelihoods online? Otherwise you can use `nnet-compute` executable for what you need.

**Comment by davidavdav** [comment]
Thanks, yes, well, I need to produce them online and from a python environment.  We have our own python wrapper around our own c++ decodable, but that is not very maintainable and I'd rather make a complete switch to pykaldi.

**Comment by vrmpx** [comment]
At the moment pykaldi does not have this functionality because upstream kaldi does not have such an api.  To produce log likelihoods online, we would have to patch [our kaldi fork](https://github.com/pykaldi/kaldi) and add a method similar to the one you added. Then we can wrap that with clif. 

I think this would be a great addition to pykaldi. If you're interested, we could help you with the necessary steps to contribute a new pull request.

**Comment by davidavdav** [comment]
I have a patch to Kaldi around for a while, and in order to test it I've dived into building pykaldi locally (see issue #120).  

I can now build pykaldi in a linux / python 3.5 environment, and this appears to work to some extent, but I see strange differences w.r.t. an anaconda install (which uses python 3.7) on the same machine:
 - For a test script very similar to [nnet3-batch-recognizer.py](https://github.com/pykaldi/pykaldi/blob/master/examples/scripts/asr/nnet3-batch-recognizer.py) the anaconda install is really a lot faster (~5x) than my own built version.  In the script I disable the use of the GPU
 - the (slow) log_likelihood extraction as in the excerpt above works in the anaconda install, but crashes in the built version on a Kaldi assertion
```
ASSERTION_FAILED ([5.5.196-5dc5d]:EnsureFrameIsComputed():nnet3/decodable-online-looped.h:94) : 'subsampled_frame >= current_log_post_subsampled_offset_ && "Frames must be accessed in order."' 
```
This is comparing a pykaldi anaconda environment and a fresh built environment of pykaldi commit b0ac6c1, without my kaldi patch. 

My current workflow for development is
 - activate virtual environment as in the README of pykaldi
 - develop kaldi source in `tools/kaldi/src`
 - run `make`
 - `cd ../../..` to the root of pykaldi
 - run `python setup.py install`
 - run `python setup.py test` --- this seems essential for a proper install
 - still keeping this virtual environment, `cd` to the location of the python test script and run that there. 

What could be the reason for the big difference in speed between anaconda and my own build?

**Comment by davidavdav** [comment]
Just pinging @vrmpx (I don't want to be too intrusive...) The PRs above, if they are acceptable, would fix this issue.

**Comment by vrmpx** [comment]
Sorry been busy with other stuff. We have some comments on the PR which I'll make sure to add today. Thanks for doing this :)
