### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by wentaoxandry** [pykaldi/pykaldi#117]
Hello, 

I have a problem by install pykaldi, during install there are no error, but at the step: python setup.py install, the computer will always be frozen, I have tried many times but it always so, I want to ask if you know what can cause this problem and how can I fix it?

Thank you

**Comment by vrmpx** [comment]
You are probably running out of memory during build. Try limiting the number of parallel jobs as described [here](https://github.com/pykaldi/pykaldi#how-do-i-prevent-pykaldi-install-command-from-exhausting-the-system-memory).

**Comment by wentaoxandry** [comment]
Thank you so much, it works
