### ISSUE TITLE
get all path of lattice

### ISSUE THREAD

**Issue by wentaoxandry** [pykaldi/pykaldi#118]
Hi, 
I want do some MMI training, so I have to get the posterior of all path of lattice, I want to ask if there is any way can get all path(or best n path) of lattice?

Thank you

**Comment by vrmpx** [comment]
There is no function in pykaldi to get all lattice paths. You can use the [shortestpath function](https://pykaldi.github.io/api/kaldi.fstext.html?highlight=shortest#kaldi.fstext.shortestpath) for n best paths.
