### ISSUE TITLE
convert loglike to posterior

### ISSUE THREAD

**Issue by wentaoxandry** [pykaldi/pykaldi#119]
Hi, 

I have a question, can we convert loglike to posterior? Is there any function can do it?

**Comment by davidavdav** [comment]
I'd say subtract log prior, exponentiate, and normalize.  But as far as I understand nnet3/chain models somehow have a constant prior, so the log likelihoods basically are posteriors.  In fact, that is what the nnet computes, and if you look at [the source](https://github.com/kaldi-asr/kaldi/blob/1da8ebdc583ce8c0d42dc4480e46a573537eb48e/src/nnet3/decodable-online-looped.cc#L238-L246) it looks like the computed log posteriors are simply returned as log likelihoods.

**Comment by wentaoxandry** [comment]
Thank you for your reply, it is very helpful, but I still have a question, if my logprob is come from nnet, is that still the same?

**Comment by vrmpx** [comment]
Regarding log likelihood to posterior conversion. If you're using an AmNnet, which includes the log priors in addition to the raw neural network, to produce the log-likelihoods, then the `LogLikelihood` method of the decodable object returns scaled log posteriors, i.e. acoustic-scale * (log-likelihood - log-prior). If you use a raw Nnet, then the `LogLikelihood` method of the decodable object returns scaled log likelihoods, i.e. acoustic-scale * log-likelihood.

Keep in mind that neither of these values are normalized, so they don’t sum up to one after exponentiation.

**Comment by vrmpx** [comment]
Closing up this issue but feel free to re-open it.
