### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by wanglong001** [pykaldi/pykaldi#124]
HI,  memory leak， how to fix？
================================================
   **Mem usage    Increment   Line Contents**
   166 1145.148 MiB **1145.148 MiB**       @profile
   167                                 def extractIvector(self, file):
   168 1145.148 MiB    0.000 MiB           num_guass = 20
   169 1155.305 MiB   **10.156 MiB**           waveData = WaveData().read(ifstream().from_file(file))
   170 1165.164 MiB    **9.859 MiB**           feats = self.mfcc.compute_features(waveData.data()[0],
   171 1165.160 MiB    0.000 MiB                                              waveData.samp_freq, 1.0)
   172 1165.160 MiB    0.000 MiB           vadFeats = Vector(compute_vad_energy(self.vadOpt, feats))
   173 1165.160 MiB    0.000 MiB           deltaFeaturesOpt = DeltaFeaturesOptions()
   174 1165.160 MiB    0.000 MiB           deltaFeats = compute_deltas(deltaFeaturesOpt, feats)
   175 1165.160 MiB    0.000 MiB           voiceFeats = self.select_voiced_frames(deltaFeats, vadFeats)

**Comment by vrmpx** [comment]
It would be really helpful if you could provide more information like which OS are you running on, how did you install pykaldi (e.g., conda package, docker image), and/or a small code example of what you're trying to achieve when the memory leak happens.

**Comment by wanglong001** [comment]
@vrmpx ths

OS: Ubuntu18.04
install command: conda install -c pykaldi pykaldi-cpu

code :
    class Obj():
        def __init__(self, model_path):
            usage = "mfcc"
            po = ParseOptions(usage)
            mfccOpt = MfccOptions()
            mfccOpt.register(po)
            po.read_config_file(path_mfcc)
            self.mfcc = Mfcc(mfccOpt)

            usage = "vad"
            po = ParseOptions(usage)
            self.vadOpt = VadEnergyOptions()
            self.vadOpt.register(po)
            po.read_config_file(path_vad)

        def extractIvector(self, file):
            num_guass = 20
            waveData = WaveData().read(ifstream().from_file(file))
            feats = self.mfcc.compute_features(waveData.data()[0],
                                               waveData.samp_freq, 1.0)
            vadFeats = Vector(compute_vad_energy(self.vadOpt, feats))
            deltaFeaturesOpt = DeltaFeaturesOptions()
            deltaFeats = compute_deltas(deltaFeaturesOpt, feats)
            voiceFeats = self.select_voiced_frames(deltaFeats, vadFeats)


o = Obj()
while True:
    o.extractIvector(file)
