### ISSUE TITLE
Successive calls of DecodableNnetSimpleLoopedInfo.from_am() get slower

### ISSUE THREAD

**Issue by AlexPapp** [pykaldi/pykaldi#125]
Hi,
Not sure if I'm doing something obviously wrong here, apologies if I am!
I've noticed that when creating `NnetLatticeFasterOnlineRecognizer`s from pre-loaded models, the first one is created a lot quicker than any successive ones. I've narrowed the issue down to successive calls of `DecodableNnetSimpleLoopedInfo.from_am()` getting slower when using the same, pre-loaded acoustic model.
Now, checking the constructor in Kaldi (http://kaldi-asr.org/doc/decodable-simple-looped_8h_source.html, line 102), it does warn that the acoustic model might have to be modified to allow for multiple iVectors - not sure if that's related? The acoustic model is definitely modified (checked using `.info()`), although I can't yet understand how that relates to the slowdown.
I'm currently working around the issue by copying the acoustic model before initialising recognizers.
Here's some code that reproduces the issue:
```
import time
from kaldi.asr import NnetLatticeFasterOnlineRecognizer
from kaldi.nnet3 import NnetSimpleLoopedComputationOptions, DecodableNnetSimpleLoopedInfo

_, acoustic_model = NnetLatticeFasterOnlineRecognizer.read_model('final.mdl')
decodable_opts = NnetSimpleLoopedComputationOptions()
decodable_opts.frames_per_chunk = 150

for i in range(10):
    t0 = time.time()
    DecodableNnetSimpleLoopedInfo.from_am(decodable_opts, acoustic_model)
    print('{}: {}s'.format(i, time.time()-t0))
```
Result is this:
```
0: 0.854362964630127s
1: 3.2782909870147705s
2: 2.748094081878662s
3: 3.0606131553649902s
4: 2.7350778579711914s
5: 2.7128713130950928s
6: 2.994333028793335s
7: 2.8012709617614746s
8: 2.7912797927856445s
9: 2.7119319438934326s
```
Thanks!

**Comment by vrmpx** [comment]
Hello,
You're right in that the problem has to do with the nnet getting modified on the first iteration. Specifically `DecodableNnetSimpleLoopedInfo.from_am(decodable_opts, acoustic_model)` edits the nnet configuration the first time it is called.

I'll eventually try to get it fix in our kaldi fork, but for the meantime you can work around the problem by reloading the configuration, e.g.

```{python}
import time
from kaldi.asr import NnetLatticeFasterOnlineRecognizer
from kaldi.nnet3 import NnetSimpleLoopedComputationOptions, DecodableNnetSimpleLoopedInfo
from kaldi.base.io import ifstream

_, acoustic_model = NnetLatticeFasterOnlineRecognizer.read_model('final.mdl')
decodable_opts = NnetSimpleLoopedComputationOptions()
decodable_opts.frames_per_chunk = 150

with open("config", "w") as ofile:
    for line in acoustic_model.get_nnet().get_config_lines(False):
        print(line, file=ofile)

for i in range(10):
    t0 = time.time()
    acoustic_model.get_nnet().read_config(ifstream.from_file("config"))
    DecodableNnetSimpleLoopedInfo.from_am(decodable_opts, acoustic_model)
    print('{}: {}s'.format(i, time.time()-t0))
```

**Comment by AlexPapp** [comment]
Hi - all right, thanks for the answer!
