### ISSUE TITLE
Error starting Jupyter Notebook

### ISSUE THREAD

**Issue by SergeyShk** [pykaldi/pykaldi#126]
Hello. When I run the docker and try to turn on the Jupyter Notebook, the following error occurs.
![Screenshot from 2019-05-19 07-39-55](https://user-images.githubusercontent.com/10076495/57977863-b2870c00-7a09-11e9-993d-74dd1037b637.png)

**Comment by vrmpx** [comment]
Can you try with the following command **inside the container**?
```
jupyter notebook --no-browser --ip=0.0.0.0 --port=9000 --allow-root
```
That should start the jupyter server running in http://localhost:9000

**Comment by SergeyShk** [comment]
Thanks. Problem is solved.
