### ISSUE TITLE
OSError: Could not open stream for reading

### ISSUE THREAD

**Issue by ivannson** [pykaldi/pykaldi#129]
I am trying to run the "Offline ASR using Kaldi Models" example using Docker + Jupyter Notebook. When trying to run the script, I am getting the following error on MacOS:

```
OSError                                   Traceback (most recent call last)
<ipython-input-23-1def4b3ace20> in <module>
     19 asr = NnetLatticeFasterRecognizer.from_files(
     20         model_path, graph_path, symbols_path,
---> 21         decoder_opts=decoder_opts, decodable_opts=decodable_opts)
     22 
     23 # Extract the features, decode and write output lattices

/usr/local/lib/python3.5/dist-packages/pykaldi-0.1.2-py3.5-linux-x86_64.egg/kaldi/asr.py in from_files(cls, model_rxfilename, graph_rxfilename, symbols_filename, allow_partial, decoder_opts, decodable_opts, online_ivector_period)
   1052             NnetLatticeFasterRecognizer: A new recognizer.
   1053         """
-> 1054         transition_model, acoustic_model = cls.read_model(model_rxfilename)
   1055         graph = _fst.read_fst_kaldi(graph_rxfilename)
   1056         if not decoder_opts:

/usr/local/lib/python3.5/dist-packages/pykaldi-0.1.2-py3.5-linux-x86_64.egg/kaldi/asr.py in read_model(model_rxfilename)
    887     def read_model(model_rxfilename):
    888         """Reads model from an extended filename."""
--> 889         with _util_io.xopen(model_rxfilename) as ki:
    890             transition_model = _hmm.TransitionModel().read(ki.stream(),
    891                                                            ki.binary)

/usr/local/lib/python3.5/dist-packages/pykaldi-0.1.2-py3.5-linux-x86_64.egg/kaldi/util/io.py in xopen(xfilename, mode, write_header)
    250         binary = True
    251     if reading:
--> 252         return Input(xfilename, binary)
    253     else:
    254         return Output(xfilename, binary, write_header)

/usr/local/lib/python3.5/dist-packages/pykaldi-0.1.2-py3.5-linux-x86_64.egg/kaldi/util/io.py in __init__(self, rxfilename, binary)
     48         self.binary = False
     49         if rxfilename is not None:
---> 50             self.open(rxfilename, binary)
     51 
     52     def __del__(self):

/usr/local/lib/python3.5/dist-packages/pykaldi-0.1.2-py3.5-linux-x86_64.egg/kaldi/util/io.py in open(self, rxfilename, binary)
     80             success = self._open_text_mode(rxfilename)
     81         if not success:
---> 82             raise IOError("Could not open stream for reading.")
     83         self._read = _base_io.read if binary else _base_io.read_text
     84         self._readline = _base_io.readline if binary else _base_io.readline_text

OSError: Could not open stream for reading.
```

**Comment by vrmpx** [comment]
Hello,
Did you, by any chance, downloaded the models before running the example?
Maybe take a look at the [zamia example](https://github.com/pykaldi/pykaldi/tree/master/examples/setups/zamia) to get a better idea of how to obtain the models.

**Comment by Domquatzo** [comment]
Is there any update on this topic? I have installed pykaldi from source and downloaded the models as it is described in https://github.com/pykaldi/pykaldi/tree/master/examples/setups/zamia . Trying to run any of the python files in https://github.com/pykaldi/pykaldi/tree/master/examples/scripts/asr still prints the same error

Traceback (most recent call last):
  File "nnet3-rnnlm-recognizer.py", line 24, in <module>
    decodable_opts=decodable_opts)
  File "/home/daniel/repository/pgchill2/Entwicklung/Speechtest/pykaldi/tools/env/local/lib/python2.7/site-packages/pykaldi-0.1.2-py2.7-linux-x86_64.egg/kaldi/asr.py", line 1054, in from_files
    transition_model, acoustic_model = cls.read_model(model_rxfilename)
  File "/home/daniel/repository/pgchill2/Entwicklung/Speechtest/pykaldi/tools/env/local/lib/python2.7/site-packages/pykaldi-0.1.2-py2.7-linux-x86_64.egg/kaldi/asr.py", line 889, in read_model
    with _util_io.xopen(model_rxfilename) as ki:
  File "/home/daniel/repository/pgchill2/Entwicklung/Speechtest/pykaldi/tools/env/local/lib/python2.7/site-packages/pykaldi-0.1.2-py2.7-linux-x86_64.egg/kaldi/util/io.py", line 252, in xopen
    return Input(xfilename, binary)
  File "/home/daniel/repository/pgchill2/Entwicklung/Speechtest/pykaldi/tools/env/local/lib/python2.7/site-packages/pykaldi-0.1.2-py2.7-linux-x86_64.egg/kaldi/util/io.py", line 50, in __init__
    self.open(rxfilename, binary)
  File "/home/daniel/repository/pgchill2/Entwicklung/Speechtest/pykaldi/tools/env/local/lib/python2.7/site-packages/pykaldi-0.1.2-py2.7-linux-x86_64.egg/kaldi/util/io.py", line 82, in open
    raise IOError("Could not open stream for reading.")
IOError: Could not open stream for reading.
