### ISSUE TITLE
Why is compute-mfcc-feats not found and ivector-extract-online2. IS there a simple way to fix this issue

### ISSUE THREAD

**Issue by zachadasm16** [pykaldi/pykaldi#132]
![Capture](https://user-images.githubusercontent.com/39277460/58911798-a62bd000-86e6-11e9-8a1c-a36eac720176.PNG)

**Comment by zachadasm16** [comment]
solved

**Comment by cosmicaug** [comment]
More information would have been nice.

**Comment by ahmedalbahnasawy** [comment]
@cosmicaug you need to do . ./path 👍
