### ISSUE TITLE
Inbuit functionality of extracting word timestamps in pykaldi

### ISSUE THREAD

**Issue by arpit1102** [pykaldi/pykaldi#133]
Is there a way to directly extract timestamps of each word during speech to text conversion?

**Comment by vrmpx** [comment]
There isn't a direct way. You can take a look into the code in alignment.py to see an example of converting frame alignments to token alignments. The token alignments are in terms of number of frames not seconds.

**Comment by arpit1102** [comment]
Is it then possible to convert these frame alignments to time in seconds by any analytical approach?

> There isn't a direct way. You can take a look into the code in alignment.py to see an example of converting frame alignments to token alignments. The token alignments are in terms of number of frames not seconds.

**Comment by vrmpx** [comment]
You can convert token alignments that are in terms of number of frames to seconds by multiplying them with the frame duration, which is typically 0.01 for most models, 0.03 for chain models.
