### ISSUE TITLE
error in SequentialMatrixReader

### ISSUE THREAD

**Issue by yhifny** [pykaldi/pykaldi#135]
feats_rspecifier= "ark,s,cs:apply-cmvn  --utt2spk=ark:/mnt/c/yasser/kaldi/egs/timit/s5/data/train/split3/1/utt2spk scp:/mnt/c/yasser/kaldi/egs/timit/s5/data/train/split3/1/cmvn.scp scp:/mnt/c/yasser/kaldi/egs/timit/s5/data/train/split3/1/feats.scp ark:- |" +\
                  "splice-feats --left-context=3 --right-context=3 ark:- ark:- |" +\
                  "transform-feats /mnt/c/yasser/kaldi/egs/timit/s5/exp/tri3/final.mat ark:- ark:- |" +\
                  "transform-feats --utt2spk=ark:/mnt/c/yasser/kaldi/egs/timit/s5/data/train/split3/1/utt2spk ark:/mnt/c/yasser/kaldi/egs/timit/s5/exp/tri3_ali/trans.1 ark:- ark:- |"

with SequentialMatrixReader(feats_rspecifier) as f:
    for  i in f:
        print(i)
        break

**ERROR (transform-feats[5.5.357~3-80092]:Write():kaldi-matrix.cc:1403) Failed to write matrix to stream**

**Comment by vrmpx** [comment]
maybe due to insufficient memory, e.g. docker container, or some sort of linking problem, e.g. runtime libs do not match link time libs.

**Comment by vrmpx** [comment]
Are you getting the same error without the break statement in the loop? 
transform-feats might be throwing the write error because you're closing the pipe early
