### ISSUE TITLE
getting the ASpIRE chain models

### ISSUE THREAD

**Issue by PhantomGrin** [pykaldi/pykaldi#137]
How can I make offline ASpIRE chain models to work using pykaldi. When we download the model from the Kaldi repo, it says we need to run the scripts to make it as a model. When I try to make the model, it gives error command tree-info not found. In a forum, I saw it is because of compilation error with Kaldi. Do we need to install Kaldi from the source to create the model?

**Comment by vrmpx** [comment]
Hi, you can take a look at https://github.com/pykaldi/pykaldi/tree/master/examples/setups/aspire which downloads the models you need.
