### ISSUE TITLE
Errors occurred when I run "./install_clif.sh "

### ISSUE THREAD

**Issue by CXiaoDing** [pykaldi/pykaldi#138]
I was install pykaldi from source.
I followed the command in readme file, and some errors occurred but I solved them.
When I run "./install_clif.sh ", an error occurred and I could not sovle it.
Can anybody help me???
@dogancan @vrmpx @r9y9 @davidavdav @caizexin 

`Destination /home/cxd/pykaldi/tools/clif already exists.
Already up-to-date.
/home/cxd/pykaldi/env/bin/ninja
Using ninja for the clif backend build.
Checked out revision 307315.
Checked out revision 307315.
CMake Deprecation Warning at CMakeLists.txt:15 (cmake_policy):
  The OLD behavior for policy CMP0051 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- Native target architecture is X86
-- Threads enabled.
-- Doxygen disabled.
-- Go bindings disabled.
-- OCaml bindings disabled, need ctypes >=0.4.
-- LLVM host triple: x86_64-unknown-linux-gnu
-- LLVM default target triple: x86_64-unknown-linux-gnu
-- Building with -fPIC
-- Constructing LLVMBuild project information
-- Targeting X86
-- Found Z3: /usr/lib/x86_64-linux-gnu/libz3.so (found suitable version "4.8.6 - 64 bit", minimum required is "4.5") 
-- Clang version: 5.0.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/cxd/pykaldi/tools/clif_backend/build_matcher
[1/11] Generating SVNVersion.inc
-- Found Subversion: /usr/bin/svn (found version "1.9.3") 
[1/214] Building C object tools/clang/tools/c-index-test/CMakeFiles/c-index-test.dir/c-index-test.c.o
FAILED: tools/clang/tools/c-index-test/CMakeFiles/c-index-test.dir/c-index-test.c.o 
/usr/bin/cc -DCLANG_ENABLE_ARCMT -DCLANG_ENABLE_OBJC_REWRITER -DCLANG_ENABLE_STATIC_ANALYZER -DGTEST_HAS_RTTI=0 -DLLVM_BUILD_GLOBAL_ISEL -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/clang/tools/c-index-test -I/home/cxd/pykaldi/tools/clif_backend/llvm/tools/clang/tools/c-index-test -I/home/cxd/pykaldi/tools/clif_backend/llvm/tools/clang/include -Itools/clang/include -Iinclude -I/home/cxd/pykaldi/tools/clif_backend/llvm/include -isystem /home/cxd/anaconda3/include/libxml2 -fPIC -Werror=date-time -Wall -W -Wno-unused-parameter -Wwrite-strings -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-comment -ffunction-sections -fdata-sections -O3 -DNDEBUG   -std=gnu89 -MD -MT tools/clang/tools/c-index-test/CMakeFiles/c-index-test.dir/c-index-test.c.o -MF tools/clang/tools/c-index-test/CMakeFiles/c-index-test.dir/c-index-test.c.o.d -o tools/clang/tools/c-index-test/CMakeFiles/c-index-test.dir/c-index-test.c.o   -c /home/cxd/pykaldi/tools/clif_backend/llvm/tools/clang/tools/c-index-test/c-index-test.c
In file included from /home/cxd/anaconda3/include/libxml2/libxml/parser.h:810:0,
                 from /home/cxd/pykaldi/tools/clif_backend/llvm/tools/clang/tools/c-index-test/c-index-test.c:15:
/home/cxd/anaconda3/include/libxml2/libxml/encoding.h:31:26: fatal error: unicode/ucnv.h: No such file or directory
compilation terminated.
[2/214] Building CXX object tools/clang/tools/libclang/CMakeFiles/libclang.dir/CIndexCXX.cpp.o
ninja: build stopped: subcommand failed.
`

**Comment by caizexin** [comment]
Hi Xiaoding,

I think the problem you got is similar to this one <https://github.com/pykaldi/pykaldi/issues/50>. Follow the instructions mentioned in the issue may solve your case.

**Comment by CXiaoDing** [comment]
ok, thank you very much! @caizexin
