### ISSUE TITLE
Why I can't run the examples?

### ISSUE THREAD

**Issue by CXiaoDing** [pykaldi/pykaldi#139]
I followed the readme, and installed pykaldi from sources.
I met some problems but I solved them all.
while when I want to run the codes in example, I open the python file using pycharm,
and I found there were red lines under the code. and I can't run the code successfully.
Can anybody help me???
@dogancan @r9y9 @vrmpx @davidavdav @caizexin 
`/home/cxd/pykaldi/env/bin/python2.7 /home/cxd/PycharmProjects/pykaldi/examples/scripts/asr/nnet3-keep-loglikes.py
ERROR ([5.5.201~1-7d4bd]:ReadConfigFile():parse-options.cc:469) Cannot open config file: online.conf
ERROR ([5.5.201~1-7d4bd]:ReadConfigFile():parse-options.cc:469) Cannot open config file: online.conf
Traceback (most recent call last):
  File "/home/cxd/PycharmProjects/pykaldi/examples/scripts/asr/nnet3-keep-loglikes.py", line 32, in <module>
    po.read_config_file("online.conf")
RuntimeError: C++ exception: 

Process finished with exit code 1`

**Comment by vrmpx** [comment]
These scripts are meant as examples of what and how to do things. They are not meant to be run as it is, since it requires files in hardcoded locations.

**Comment by CXiaoDing** [comment]
So how do I know that I have installed pykaldi successfully and I can use it when the installation process has finished?
@vrmpx

**Comment by vrmpx** [comment]
You could run the tests. I believe the command is `python setup.py test`.

**Comment by CXiaoDing** [comment]
I can run the command `python setup.py test`, and the result is `167 passed, 8 skipped in 1.76 seconds `. Does it mean I installed pykaldi successfully?
@vrmpx

**Comment by vrmpx** [comment]
yes

**Comment by CXiaoDing** [comment]
Thank you! But how do I use it?
Is there a document for using pykaldi?
@vrmpx
