### ISSUE TITLE
Why I can't download model?

### ISSUE THREAD

**Issue by CXiaoDing** [pykaldi/pykaldi#140]
I run the command "./models.sh" inside zamia directory.
While there is an error:

`HTTP request sent, awaiting response... 404 Not Found
2019-06-22 21:06:24 ERROR 404: Not Found.

tar (child): kaldi-generic-en-tdnn_f-r20190227.tar.xz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
mv: cannot stat 'kaldi-generic-en-tdnn_f-r20190227/README.md': No such file or directory
mv: cannot stat 'kaldi-generic-en-tdnn_f-r20190227/*': No such file or directory
mv: cannot stat 'model': No such file or directory
mv: cannot stat 'extractor': No such file or directory
mv: cannot stat 'ivectors_test_hires': No such file or directory
ln: failed to create symbolic link 'conf/.': No such file or directory
ln: failed to create symbolic link 'data/.': No such file or directory
`

Does it mean that this url is useless？
@dogancan @r9y9 @vrmpx @davidavdav @caizexin 
thank you！！！

**Comment by vrmpx** [comment]
Hello,
The url for the zamia model has been updated. The new url is

https://goofy.zamia.org/zamia-speech/asr-models/kaldi-generic-en-tdnn_f-r20190609.tar.xz

**Comment by CXiaoDing** [comment]
ok,thank you very much!
