### ISSUE TITLE
Figure out a way to get MKL work

### ISSUE THREAD

**Issue by davidavdav** [pykaldi/pykaldi#143]
Apparently, recent Kaldi ships with support for install and link with Intel's MKL libraries, and I've heard reports of major performance increases.  

I managed to install MKL using the downloadscript from recent Kaldi source, and I can build from the pykaldi/tools (pykaldi/kaldi source) by setting the options `./configure --shared --mkl-root="/opt/intel/mkl" --threaded-math=no --use-cuda=no`.  Then the kaldi executable seem to run fine, but the pykaldi wrapper gives runtime linking problems, like in 
```sh
examples/scripts/asr/nnet3-online-recognizer.py
LOG ([5.5.202~1-45e00]:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so.
```
so this happens really when the ivector constants are computed (this uses multi-threading, and when the script is prepended with a `LD_DEBUG=libs` the culprit seems to be:
```
/opt/intel/mkl/lib/intel64/libmkl_def.so: error: symbol lookup error: undefined symbol: mkl_sparse_optimize_bsr_trsm_i8 (fatal)
```
I don't understand where the symbol comes from, and why it is not found (it is defined in one of the MKL libs, which are indexed by `ldconfig`.  

At some stage I figured it might be related to different versions of MKL, one perhaps installed by the python environment (although I have tried with and without python `mkl`).  

So I re-built kaldi, this time linking into the `pip install mkl mkl-include` location, using 
```
./configure --shared --mkl-root="$CWD/../env/" --mkl-libdir="$CWD/../env/lib" --threaded-math=no --use-cuda=no
```
but this gives similar runtime link errors, like 
```
python: symbol lookup error: /home/david/src/pykaldi/env/lib/libmkl_vml_avx2.so: undefined symbol: mkl_serv_getenv
```

At this stage I've spent nearly a day compiling and debugging, but I'm not getting much further.  It would be nice if someone else could have a dig at this.

**Comment by vrmpx** [comment]
Hi,
Could you try again with environmental variable `DEBUG=1`? that way we can know if the correct linker flags are being set. This could also make the compilation fail if there are any undefined symbols.

**Comment by davidavdav** [comment]
Hello again, we're getting to the point where we really could use some Kaldi efficiency, so I finally got back to this issue.  

I assume you mean `DEBUG=1` for the `python setup.py build`?  This is the start of the output:
```
CWD: /home/david/src/pykaldi
PYCLIF: /home/david/.virtualenvs/pykaldi/bin/pyclif
CLIF_MATCHER: /home/david/.virtualenvs/pykaldi/clang/bin/clif-matcher
KALDI_DIR: /home/david/src/pykaldi/tools/kaldi
CXX_FLAGS: -std=c++11 -I.. -isystem /home/david/src/pykaldi/tools/kaldi/tools/openfst/include -O1 -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_MKL -I/home/david/src/pykaldi/env/include -m64 -msse -msse2 -pthread -g -fPIC -Wno-maybe-uninitialized
CLIF_CXX_FLAGS: -I/home/david/.virtualenvs/pykaldi/clang/lib/clang/5.0.0/include
LD_FLAGS: -Wl,-rpath=/home/david/src/pykaldi/tools/kaldi/tools/openfst/lib -rdynamic -Wl,--as-needed -Wl,--no-undefined
LD_LIBS: /home/david/src/pykaldi/tools/kaldi/tools/openfst/lib/libfst.so -L/home/david/src/pykaldi/env/lib -Wl,-rpath=/home/david/src/pykaldi/env/lib -lmkl_intel_lp64 -lmkl_core -lmkl_sequential -ldl -lpthread -lm -lm -lpthread -ldl
BUILD_DIR: /home/david/src/pykaldi/build
CUDA: False
MAKE: ninja -j 14 -v
```
Perhaps a bit confusing, `env` is a link to `~/.virtualenvs/pykaldi`.  Running a pykaldi script gives me:
```
examples/scripts/asr/nnet3-online-recognizer.py
LOG ([5.5.205~1-75fd]:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so.
```
Even a `LD_LIBRARY_PATH=env/lib/ examples/scripts/asr/nnet3-online-recognizer.py` results in the same error.   Both `libmkl_avx2.so` and `libmkl_def.so` are in `env/lib`.  More debugging with `LD_DEBUG=libs LD_LIBRARY_PATH=$HOME/.virtualenvs/pykaldi/lib/ examples/scripts/asr/nnet3-online-recognizer.py` results in
```
LOG ([5.5.205~1-75fd]:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
     10992:     /home/david/.virtualenvs/pykaldi/lib/libmkl_avx2.so: error: symbol lookup error: undefined symbol: mkl_sparse_optimize_bsr_trsm_i8 (fatal)                                                     10992:     find library=libmkl_avx2.so [0]; searching
     10992:      search path=/home/david/.virtualenvs/pykaldi/lib               (LD_LIBRARY_PATH)
     10992:       trying file=/home/david/.virtualenvs/pykaldi/lib/libmkl_avx2.so
     10992:     
     10992:     /home/david/.virtualenvs/pykaldi/lib/libmkl_avx2.so: error: symbol lookup error: undefined symbol: mkl_sparse_optimize_bsr_trsm_i8 (fatal)
     10992:     /home/david/.virtualenvs/pykaldi/lib/libmkl_def.so: error: symbol lookup error: undefined symbol: mkl_sparse_optimize_bsr_trsm_i8 (fatal)
     10992:     find library=libmkl_def.so [0]; searching
     10992:      search path=/home/david/.virtualenvs/pykaldi/lib               (LD_LIBRARY_PATH)
     10992:       trying file=/home/david/.virtualenvs/pykaldi/lib/libmkl_def.so
     10992:     
     10992:     /home/david/.virtualenvs/pykaldi/lib/libmkl_def.so: error: symbol lookup error: undefined symbol: mkl_sparse_optimize_bsr_trsm_i8 (fatal)
Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so.
```
so, really, I'm confused how to progress.

**Comment by davidavdav** [comment]
Bump, is there any way someone that understands these linking issues better than me could have a look at this?  A rough estimation of the potential speed boost for Kaldi is around a factor 2...

Thanks!

**Comment by davidavdav** [comment]
There is a couple of other threads related to this, [here](https://github.com/ContinuumIO/anaconda-issues/issues/698) and [here](https://github.com/BVLC/caffe/issues/3884), which all seem to have been resolved years ago.

**Comment by davidavdav** [comment]
Kirill Katnelson on [the Kaldi google group](https://groups.google.com/d/msg/kaldi-help/m3nyQke0HS0/4fj8gkSWAgAJ) solved the problem: link with `libmkl_rt.so` and work with environment variables to select the ABI and threading model at run-time.  

It still is unclear to me why the linking options `-lmkl_intel_lp64 -lmkl_core -lmkl_sequential/` work for kaldi but not for pykaldi, but the dynamic runtime dynamic library `-lmkl_rt` works for both.
