### ISSUE TITLE
Offline ASR with PyTorch Aspire Models

### ISSUE THREAD

**Issue by Pradeep-Rangan** [pykaldi/pykaldi#147]
Hello everyone,

I have used the pre-trained aspire models trained in Kaldi using the following link:
http://kaldi-asr.org/models/m1
I successfully executed the Offline ASR using Kaldi Models. It works great.
However, i would like to extend the framework using PyTorch i.e., Offline ASR using a PyTorch Acoustic Model.
Can I please know the path of the pre-trained aspire models trained in Pytorch? (model.pt)
Or any pre-trained models available?

I hope you do the needful.

Thanks in advance.

Regards,
Pradeep
Research Scholar,
Dept. of CSE,
IIT Kharagpur

**Comment by vrmpx** [comment]
Hi!
Wwe don't know of any pretrained pytorch models compatible with kaldi. But you  might be able to train such pytorch models using the new pykaldi2 toolkit.

**Comment by Pradeep-Rangan** [comment]
Thanks for your suggestion. Pre-trained models would have  been very much useful as some of the standard datasets are not open sourced (Ex: aspire dataset/WSJ/Switchboard, etc). 
I will look into some alternative solution based on your suggestions. Thanks.
