### ISSUE TITLE
FST not of type vector 

### ISSUE THREAD

**Issue by taomanwai** [pykaldi/pykaldi#151]
Hi all

I tried fst.StdVectorFst.read() to read HCLG.fst, but failed, this error occurs

ERROR: FstImpl::ReadHeader: FST not of type vector: /mnt/nas2/corpus/online_model_test/HCLG.fst

What's wrong? I ensure that the HCLG.fst is valid !

Thanks in advance.

**Comment by taomanwai** [comment]
I tried CastOrConvertToVectorFst solution of https://groups.google.com/forum/#!msg/kaldi-help/0SuCkeHyUmU/u3bM04_AAAAJ

I modified *.cc under /pykaldi/tools/kaldi/src/ 's bin folder, but still doesn't work. 

Any solution ?

Thanks thanks !

**Comment by vrmpx** [comment]
Hello,
It appears you're  trying to read a StdConstFst as StdVectorFst. 
Please see https://pykaldi.github.io/api/kaldi.fstext.html?highlight=read_fst_kaldi#kaldi.fstext.read_fst_kaldi
