### ISSUE TITLE
Unable to test audio files

### ISSUE THREAD

**Issue by Sumit1673** [pykaldi/pykaldi#154]
I have build KALDI from source and trying to test it on some audio files but facing the error below after running this command:
Command:
steps/online/nnet3/decode.sh --nj 1 --acwt 1.0 --post-decode-acwt 10.0 exp/tdnn_7b_chain_online/graph ~/Documents/KALDI/ exp/tdnn_7b_chain_online/decode_ASR_demo

Error Log;
# online2-wav-nnet3-latgen-faster --do-endpointing=false --frames-per-chunk=20 --extra-left-context-initial=0 --online=true --frame-subsampling-factor=3 --config=exp/tdnn_7b_chain_online/conf/online.conf --min-active=200 --max-active=7000 --beam=15.0 --lattice-beam=6.0 --acoustic-scale=1.0 --word-symbol-table=exp/tdnn_7b_chain_online/graph/words.txt exp/tdnn_7b_chain_online/final.mdl exp/tdnn_7b_chain_online/graph/HCLG.fst ark:/home/garud/Documents/KALDI//split1/1/spk2utt "ark,s,cs:wav-copy scp,p:/home/garud/Documents/KALDI//split1/1/wav.scp ark:- |" "ark:|lattice-scale --acoustic-scale=10.0 ark:- ark:- | gzip -c >exp/tdnn_7b_chain_online/decode_ASR_demo/lat.1.gz" 
# Started at Mon Aug 12 19:12:45 EDT 2019
#
online2-wav-nnet3-latgen-faster --do-endpointing=false --frames-per-chunk=20 --extra-left-context-initial=0 --online=true --frame-subsampling-factor=3 --config=exp/tdnn_7b_chain_online/conf/online.conf --min-active=200 --max-active=7000 --beam=15.0 --lattice-beam=6.0 --acoustic-scale=1.0 --word-symbol-table=exp/tdnn_7b_chain_online/graph/words.txt exp/tdnn_7b_chain_online/final.mdl exp/tdnn_7b_chain_online/graph/HCLG.fst ark:/home/garud/Documents/KALDI//split1/1/spk2utt 'ark,s,cs:wav-copy scp,p:/home/garud/Documents/KALDI//split1/1/wav.scp ark:- |' 'ark:|lattice-scale --acoustic-scale=10.0 ark:- ark:- | gzip -c >exp/tdnn_7b_chain_online/decode_ASR_demo/lat.1.gz' 
LOG (online2-wav-nnet3-latgen-faster[5.5.201~1-7d4bd]:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (online2-wav-nnet3-latgen-faster[5.5.201~1-7d4bd]:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (online2-wav-nnet3-latgen-faster[5.5.201~1-7d4bd]:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (online2-wav-nnet3-latgen-faster[5.5.201~1-7d4bd]:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (online2-wav-nnet3-latgen-faster[5.5.201~1-7d4bd]:Collapse():nnet-utils.cc:1378) Added 1 components, removed 2
LOG (online2-wav-nnet3-latgen-faster[5.5.201~1-7d4bd]:CompileLooped():nnet-compile-looped.cc:345) Spent 0.00825691 seconds in looped compilation.
WARNING (online2-wav-nnet3-latgen-faster[5.5.201~1-7d4bd]:Open():util/kaldi-table-inl.h:513) Failed to open stream /home/garud/Documents/KALDI//split1/1/spk2utt
ERROR (online2-wav-nnet3-latgen-faster[5.5.201~1-7d4bd]:SequentialTableReader():util/kaldi-table-inl.h:860) Error constructing TableReader: rspecifier is ark:/home/garud/Documents/KALDI//split1/1/spk2utt

[ Stack-Trace: ]
kaldi::MessageLogger::HandleMessage(kaldi::LogMessageEnvelope const&, char const*)
kaldi::FatalMessageLogger::~FatalMessageLogger()
main
__libc_start_main
_start

ERROR (online2-wav-nnet3-latgen-faster[5.5.201~1-7d4bd]:SequentialTableReader():util/kaldi-table-inl.h:860) Error constructing TableReader: rspecifier is ark:/home/garud/Documents/KALDI//split1/1/spk2utt

[ Stack-Trace: ]
kaldi::MessageLogger::HandleMessage(kaldi::LogMessageEnvelope const&, char const*)
kaldi::MessageLogger::~MessageLogger()
kaldi::FatalMessageLogger::~FatalMessageLogger()
main
__libc_start_main
_start

# Accounting: time=1 threads=1
# Ended (code 255) at Mon Aug 12 19:12:46 EDT 2019, elapsed time 1 seconds

I am not sure how to resolve this error.

**Comment by vrmpx** [comment]
This is a kaldi issue not related to pykaldi. 
Closing this issue

**Comment by hontarenkoYana** [comment]
@Sumit1673, hello!
Did you find the answer?

**Comment by bmilde** [comment]
Probably it's just the "spk2utt" file missing. It's a plain text file
mapping speaker ids to utterance ids. I recommend checking out
https://kaldi-asr.org/doc/data_prep.html. If you have just one recording
you can just put one single line like "myspeaker1 myutterance1" into this
file, if your wav.scp is "myutterance1 myutterance1.wav".

Am Mo., 11. Jan. 2021 um 11:51 Uhr schrieb Yana Hontarenko <
notifications@github.com>:
