### ISSUE TITLE
Request for SGMM decoder class like GmmLatticeFasterRecognizer

### ISSUE THREAD

**Issue by NecklessCage** [pykaldi/pykaldi#155]
I'm attempting to host an SGMM model using PyKaldi. Is there a way to do so? If not, is there any plan on adding this feature?

I appreciate very much for the awesome work you all have done on PyKaldi.

**Comment by vrmpx** [comment]
Hi, we don't have any plans to add this feature at the moment (due to time constraints) but we would be happy to merge a PR

**Comment by NecklessCage** [comment]
I see. Thanks for the good work again.
