### ISSUE TITLE
How to convert ndarray to kaldi data structure？

### ISSUE THREAD

**Issue by 601222543** [pykaldi/pykaldi#157]
Hi：
     I read the wav stream to `numpy.ndarray` through the soundfile. I want to convert `numpy.ndarray` to `_kaldi_vector.VectorBase`. I don't know how to operate it.
    Or if there is a way to read the wav stream to `_kaldi_vector.VectorBase` can solve my problem.

Looking forward to your reply。
Thank you！

**Comment by vrmpx** [comment]
```
from kaldi.matrix import Vector
​
vec = Vector(arr)  # arr: 1-dimensional ndarray
```

 VectorBase is an abstract base class. You need to construct a concrete subclass of it like Vector or SubVector.

**Comment by 601222543** [comment]
Thank you, I also found this class.，And has been implemented without disk io.
Thank you so mach!
