### ISSUE TITLE
Not able to install in a windows system

### ISSUE THREAD

**Issue by NarviLuna** [pykaldi/pykaldi#158]
While installing the following are not getting installed in windows. How can i install them using python or git?
./extras/check_dependencies.sh: WARNING: unknown compiler g++.                   ./extras/check_dependencies.sh: make is not installed.                           ./extras/check_dependencies.sh: automake is not installed.                       ./extras/check_dependencies.sh: autoconf is not installed.                       ./extras/check_dependencies.sh: wget is not installed.                           ./extras/check_dependencies.sh: sox is not installed.                            ./extras/check_dependencies.sh: neither libtoolize nor glibtoolize is installed  ./extras/check_dependencies.sh: subversion is not installed                      ./extras/check_dependencies.sh: python2.7 is not installed
--

**Comment by vrmpx** [comment]
Hello,
As of now, we don't support windows.
