### ISSUE TITLE
when install pykaldi cpu-only, run some asr code on cpu server,an error occurs

### ISSUE THREAD

**Issue by Pydataman** [pykaldi/pykaldi#161]
from kaldi.asr import NnetLatticeFasterOnlineRecognizer

ImportError:   /env/lib/python3.6/site-packages/kaldi/cudamatrix/../lib/libkaldi-cudamatrix.so: undefined symbol: _ZN5kaldi9TraceSpSpIdfLPv0EEET_RKNS_8SpMatrixIS2_EERKNS3_IT0_EE

**Comment by vrmpx** [comment]
Hello, we will need more information like 

1. How did you install pykaldi? Was it from source, conda package, docker?
2. What command did you try to run?

**Comment by Pydataman** [comment]
@vrmpx 
1、conda package
2、from kaldi.asr import NnetLatticeFasterOnlineRecognizer

**Comment by vrmpx** [comment]
Hey @Pydataman, 

I wasn't able to replicate this issue. Maybe this went away with the most recent pykaldi-cpu conda package version. Could you please make sure you're running version 0.1.3 and try again?

```
(base) root@ac069c2b42ea:/# conda list pykaldi-cpu
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
pykaldi-cpu               0.1.3            py37h14c3975_1    pykaldi
```
