### ISSUE TITLE
is it possible to to find source code pykaldi's tool directory if all you have is the pykaldi installed in site-package?

### ISSUE THREAD

**Issue by kkawabat** [pykaldi/pykaldi#162]
Sorry if the question doesn't make sense, I didn't know how else to word it. 

I am writing a script that uses both pykaldi python module and some helper bash script in wsj directory provided in pykaldi's tool directory inside the source code. The problem is when I `import kaldi` it points to the pykaldi scripts that are in site-packages and I can't figure out how to get the path of the WSJ directory inside pykaldi's source code from just python import along. 

```
import kaldi
print(kaldi.__file__)
>>/Users/kankawabata/anaconda3/lib/python3.7/site-packages/pykaldi-0.1.2-py3.7-macosx-10.7-x86_64.egg/kaldi/__init__.py
```

The bash script is located inside the git cloned directory of pykaldi
>/Users/kankawabata/Documents/pykaldi/tools/kaldi/egs/wsj/s5/utils/prepare_lang.sh
 
This script will be used by multiple people in different environments so I can't hardcode the pykaldi source code path inside the script and I can't guarantee that any of the paths would be in the environment path before the use of the script.  

Is there an automatic way of getting the pykaldi source code path from the pykaldi module alone?

**Comment by vrmpx** [comment]
Pykaldi package does not know anything about its source location other than being implicitly linked with the kaldi libs inside the source directory (in case of installing from source).

You can do a development installation which would keep everything inside the source directory:
```
python setup.py develop
```

Alternatively,  I am assuming you considered simply using an environment variable pointing to kaldi root or something like that, right?

**Comment by kkawabat** [comment]
Yes, currently we ask the users to specify the kaldi root path but was hoping there was a way to extract the path if the environment path is not set. Thank you for the reply I will try python setup.py develop.
