### ISSUE TITLE
Support for pip install

### ISSUE THREAD

**Issue by ar13pit** [pykaldi/pykaldi#164]
Hi,

Are there any plans to make pip releases? It should be easy considering conda releases exist.

Thanks
Arpit

**Comment by vrmpx** [comment]
Hello,
AFAIR we discussed this but found pip to be too restrictive with the size of its packages. Given that pykaldi builds on top of clif and kaldi, we don't think it would be possible.

However, we would certainly appreciate and help anyone willing to try building one
