### ISSUE TITLE
"python setup.py install" found the wrong python version in python 3

### ISSUE THREAD

**Issue by yfliao** [pykaldi/pykaldi#169]
Dear All,

I tried to build pykaldi from source in pythin 3.6.8 in colab. everything was built smoothly. However, it seems that the "python setup.py install" command found the wrong python version. Therefore, the "python setup.py test" command failed and reported "undefined symbol: PyClass_Type".

The most strange thing in the log is:
-- Found PythonInterp: /usr/local/bin/python (found version "2.7.15") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found version "2.7.15+") 

How could I force "setup.py" to use python3?

**Comment by vrmpx** [comment]
I haven't used colab, but maybe you could try something like `/usr/local/bin/python3 setup.py install`?

**Comment by vrmpx** [comment]
Also make sure `which python` is pointing to the correct python before building and installing the clif python package.

**Comment by yfliao** [comment]
The procedure "./install_clif.sh" is fine, it did find python3 as shown in the log: 
- Found PythonInterp: /usr/bin/python3 (found version "3.6.8") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1 (found version "3.6.8") 

The problem came from the install stage, both the "python setup.py install" and "python3 setup.py install" commands reported python2.7 as follows:
-- Found PythonInterp: /usr/local/bin/python (found version "2.7.15")
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found version "2.7.15+")

The most strange thing is that "/usr/local/bin/python" is in fact python 3.6,8, but setup.py still said it is version 2.7.

**Comment by vrmpx** [comment]
cmake is finding the wrong python most likely because ‘which python’ is pointing to the wrong python. Launching setup.py with correct python does not do anything for cmake.

The reason clif is finding the correct python is because we are trying very hard to make it so, by setting the correct cmake variables in install_clif.sh.

It is possible that which python is pointing to the correct python but cmake is somehow confused

**Comment by vrmpx** [comment]
I am closing this issue but feel free to re-open it if there is anything to add.
