### ISSUE TITLE
Error installing Pykaldi in Ubuntu 18.04

### ISSUE THREAD

**Issue by ppsingh98** [pykaldi/pykaldi#171]
I am trying to install Pykaldi in Ubuntu 18.04 without CUDA support. The error log is enclosed. Please help to resolve the issue.
Used the following command after successful installation of Protobuf, clif and Kaldi. 
python setup.py install

[Pykaldi_errorlog.txt](https://github.com/pykaldi/pykaldi/files/3707085/Pykaldi_errorlog.txt)

**Comment by vrmpx** [comment]
Hi,
How did you install clif? Did you use the `install_clif.sh` script inside `tools`?

**Comment by ppsingh98** [comment]
Yes , installed clif,  using install_clif.sh script inside tools. It was installed successfully and displayed the message 'Done installing clif'
