### ISSUE TITLE
how to use segments file to do the recognition?

### ISSUE THREAD

**Issue by MXuer** [pykaldi/pykaldi#175]
Hi~
I got some long audio, and there is a 'segments' file to describe the long audio.
when I extract the mfcc features, I wonder how to use this in pykaldi.

Thank  you ~

**Comment by MXuer** [comment]
I already knew it.
feats_rspec = ("ark:extract-segments scp:wav.scp segments ark:- | compute-mfcc-feats --config=mfcc_hires.conf  ark:- ark:- |")
like this.
sorry to bother.
thank you.

**Comment by emirdemirel** [comment]
Hi! I am trying to accomplish the same, I have the segments file for the recording I would like to decode. I have modified the related line according to your suggestion, yet it still doesn't work for my system. Could you please be more explicit on how you solved this problem and used 'segments' file for decoding the target recordings?

Thanks and regards!
