### ISSUE TITLE
FAILED: lib/libpyClifRuntime.so /usr/bin/ld: final link failed: Bad value | ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by kkawabat** [pykaldi/pykaldi#177]
-- Looking for sys/resource.h - found
-- Clang version: 5.0.0
-- Performing Test CXX_SUPPORTS_NO_NESTED_ANON_TYPES_FLAG
-- Performing Test CXX_SUPPORTS_NO_NESTED_ANON_TYPES_FLAG - Failed
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'protobuf'
--   Found protobuf, version 3.5.0
-- Found PythonLibs: /home/kan/.pyenv/versions/3.7.4/lib/libpython3.7m.a (found version "3.7.4") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kan/Documents/motormetrics/pykaldi/tools/clif_backend/build_matcher
[101/1788] Building CXX object lib/Sup...akeFiles/LLVMSupport.dir/Process.cpp.o
In file included from /home/kan/Documents/motormetrics/pykaldi/tools/clif_backend/llvm/lib/Support/Unix/Unix.h:24:0,
                 from /home/kan/Documents/motormetrics/pykaldi/tools/clif_backend/llvm/lib/Support/Unix/Process.inc:14,
                 from /home/kan/Documents/motormetrics/pykaldi/tools/clif_backend/llvm/lib/Support/Process.cpp:85:
/home/kan/Documents/motormetrics/pykaldi/tools/clif_backend/llvm/include/llvm/Support/Errno.h:34:13: warning: mangled name for ‘decltype (F(llvm::sys::RetryAfterSignal::As ...)) llvm::sys::RetryAfterSignal(const FailT&, const Fun&, const Args& ...) [with FailT = int; Fun = int(int, stat*) throw (); Args = {int, stat*}]’ will change in C++17 because the exception specification is part of a function type [-Wnoexcept-type]
 inline auto RetryAfterSignal(const FailT &Fail, const Fun &F,
             ^~~~~~~~~~~~~~~~
[140/1788] Generating VCSRevision.h
-- Found Subversion: /usr/bin/svn (found version "1.9.7") 
[334/1788] Building CXX object lib/Cod...s/LLVMCodeGen.dir/CodeGenPrepare.cpp.o
/home/kan/Documents/motormetrics/pykaldi/tools/clif_backend/llvm/lib/CodeGen/CodeGenPrepare.cpp:2622:6: warning: ‘void {anonymous}::ExtAddrMode::print(llvm::raw_ostream&) const’ defined but not used [-Wunused-function]
 void ExtAddrMode::print(raw_ostream &OS) const {
      ^~~~~~~~~~~
[347/1788] Building CXX object lib/Cod...VMCodeGen.dir/LiveDebugVariables.cpp.o
/home/kan/Documents/motormetrics/pykaldi/tools/clif_backend/llvm/lib/CodeGen/LiveDebugVariables.cpp:391:6: warning: ‘void {anonymous}::LDVImpl::print(llvm::raw_ostream&)’ defined but not used [-Wunused-function]
 void LDVImpl::print(raw_ostream &OS) {
      ^~~~~~~
[398/1788] Building CXX object lib/Cod...LLVMCodeGen.dir/MachinePipeliner.cpp.o
/home/kan/Documents/motormetrics/pykaldi/tools/clif_backend/llvm/lib/CodeGen/MachinePipeliner.cpp:3964:6: warning: ‘void {anonymous}::SMSchedule::print(llvm::raw_ostream&) const’ defined but not used [-Wunused-function]
 void SMSchedule::print(raw_ostream &os) const {
      ^~~~~~~~~~
[450/1788] Building CXX object lib/Cod...les/LLVMCodeGen.dir/WinEHPrepare.cpp.o
/home/kan/Documents/motormetrics/pykaldi/tools/clif_backend/llvm/lib/CodeGen/WinEHPrepare.cpp:1017:6: warning: ‘void {anonymous}::WinEHPrepare::verifyPreparedFunclets(llvm::Function&)’ defined but not used [-Wunused-function]
 void WinEHPrepare::verifyPreparedFunclets(Function &F) {
      ^~~~~~~~~~~~
[615/1788] Building CXX object lib/Tra...LLVMScalarOpts.dir/GuardWidening.cpp.o
/home/kan/Documents/motormetrics/pykaldi/tools/clif_backend/llvm/lib/Transforms/Scalar/GuardWidening.cpp:667:11: warning: ‘static llvm::StringRef {anonymous}::GuardWideningImpl::scoreTypeToString({anonymous}::GuardWideningImpl::WideningScore)’ defined but not used [-Wunused-function]
 StringRef GuardWideningImpl::scoreTypeToString(WideningScore WS) {
           ^~~~~~~~~~~~~~~~~
[664/1788] Building CXX object lib/Tra...calarOpts.dir/LoopStrengthReduce.cpp.o
/home/kan/Documents/motormetrics/pykaldi/tools/clif_backend/llvm/lib/Transforms/Scalar/LoopStrengthReduce.cpp:5349:6: warning: ‘void {anonymous}::LSRInstance::print(llvm::raw_ostream&) const’ defined but not used [-Wunused-function]
 void LSRInstance::print(raw_ostream &OS) const {
      ^~~~~~~~~~~
/home/kan/Documents/motormetrics/pykaldi/tools/clif_backend/llvm/lib/Transforms/Scalar/LoopStrengthReduce.cpp:3844:6: warning: ‘void {anonymous}::WorkItem::print(llvm::raw_ostream&) const’ defined but not used [-Wunused-function]
 void WorkItem::print(raw_ostream &OS) const {
      ^~~~~~~~
/home/kan/Documents/motormetrics/pykaldi/tools/clif_backend/llvm/lib/Transforms/Scalar/LoopStrengthReduce.cpp:1346:6: warning: ‘void {anonymous}::Cost::print(llvm::raw_ostream&) const’ defined but not used [-Wunused-function]
 void Cost::print(raw_ostream &OS) const {
      ^~~~
/home/kan/Documents/motormetrics/pykaldi/tools/clif_backend/llvm/lib/Transforms/Scalar/LoopStrengthReduce.cpp:198:6: warning: ‘void {anonymous}::RegSortData::print(llvm::raw_ostream&) const’ defined but not used [-Wunused-function]
 void RegSortData::print(raw_ostream &OS) const {
      ^~~~~~~~~~~
[710/1788] Building CXX object lib/Tra...eFiles/LLVMipo.dir/SampleProfile.cpp.o
/home/kan/Documents/motormetrics/pykaldi/tools/clif_backend/llvm/lib/Transforms/IPO/SampleProfile.cpp:448:6: warning: ‘void {anonymous}::SampleProfileLoader::printBlockWeight(llvm::raw_ostream&, const llvm::BasicBlock*) const’ defined but not used [-Wunused-function]
 void SampleProfileLoader::printBlockWeight(raw_ostream &OS,
      ^~~~~~~~~~~~~~~~~~~
/home/kan/Documents/motormetrics/pykaldi/tools/clif_backend/llvm/lib/Transforms/IPO/SampleProfile.cpp:437:6: warning: ‘void {anonymous}::SampleProfileLoader::printBlockEquivalence(llvm::raw_ostream&, const llvm::BasicBlock*)’ defined but not used [-Wunused-function]
 void SampleProfileLoader::printBlockEquivalence(raw_ostream &OS,
      ^~~~~~~~~~~~~~~~~~~
/home/kan/Documents/motormetrics/pykaldi/tools/clif_backend/llvm/lib/Transforms/IPO/SampleProfile.cpp:428:6: warning: ‘void {anonymous}::SampleProfileLoader::printEdgeWeight(llvm::raw_ostream&, {anonymous}::Edge)’ defined but not used [-Wunused-function]
 void SampleProfileLoader::printEdgeWeight(raw_ostream &OS, Edge E) {
      ^~~~~~~~~~~~~~~~~~~
[911/1788] Building CXX object lib/Asm...eFiles/LLVMAsmParser.dir/LLLexer.cpp.o
In file included from /home/kan/Documents/motormetrics/pykaldi/tools/clif_backend/llvm/include/llvm/ADT/StringRef.h:13:0,
                 from /home/kan/Documents/motormetrics/pykaldi/tools/clif_backend/llvm/include/llvm/ADT/StringMap.h:17,
                 from /home/kan/Documents/motormetrics/pykaldi/tools/clif_backend/llvm/include/llvm/Support/Host.h:17,
                 from /home/kan/Documents/motormetrics/pykaldi/tools/clif_backend/llvm/include/llvm/ADT/Hashing.h:49,
                 from /home/kan/Documents/motormetrics/pykaldi/tools/clif_backend/llvm/include/llvm/ADT/ArrayRef.h:13,
                 from /home/kan/Documents/motormetrics/pykaldi/tools/clif_backend/llvm/include/llvm/ADT/APFloat.h:21,
                 from /home/kan/Documents/motormetrics/pykaldi/tools/clif_backend/llvm/lib/AsmParser/LLLexer.h:18,
                 from /home/kan/Documents/motormetrics/pykaldi/tools/clif_backend/llvm/lib/AsmParser/LLLexer.cpp:14:
/home/kan/Documents/motormetrics/pykaldi/tools/clif_backend/llvm/include/llvm/ADT/STLExtras.h:814:6: warning: mangled name for ‘bool llvm::all_of(R&&, UnaryPredicate) [with R = llvm::StringRef&; UnaryPredicate = int (*)(int) throw ()]’ will change in C++17 because the exception specification is part of a function type [-Wnoexcept-type]
 bool all_of(R &&Range, UnaryPredicate P) {
      ^~~~~~
[938/1788] Linking CXX shared library lib/libpyClifRuntime.so
FAILED: lib/libpyClifRuntime.so 
: && /usr/bin/c++ -fPIC -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wdelete-non-virtual-dtor -Wno-comment -ffunction-sections -fdata-sections -O3 -DNDEBUG  -Wl,-z,defs -shared -Wl,-soname,libpyClifRuntime.so -o lib/libpyClifRuntime.so tools/clif/python/CMakeFiles/pyClifRuntime.dir/optional.cc.o tools/clif/python/CMakeFiles/pyClifRuntime.dir/pyproto.cc.o tools/clif/python/CMakeFiles/pyClifRuntime.dir/runtime.cc.o tools/clif/python/CMakeFiles/pyClifRuntime.dir/slots.cc.o tools/clif/python/CMakeFiles/pyClifRuntime.dir/types.cc.o -L/home/kan/Documents/motormetrics/pykaldi/tools/protobuf/lib -Wl,-rpath,/home/kan/Documents/motormetrics/pykaldi/tools/protobuf/lib -lprotobuf -lpthread /home/kan/.pyenv/versions/3.7.4/lib/libpython3.7m.a && :
/usr/bin/ld: /home/kan/.pyenv/versions/3.7.4/lib/libpython3.7m.a(ceval.o): relocation R_X86_64_PC32 against symbol `_PyRuntime' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
[952/1788] Building CXX object lib/Pas...Files/LLVMPasses.dir/PassBuilder.cpp.o
ninja: build stopped: subcommand failed.

**Comment by zhaoyun630** [comment]
I encountered the same problem as you and solved it following your solution. Thanks for a lot for sharing.
