### ISSUE TITLE
is conda install ok ？

### ISSUE THREAD

**Issue by zira-wang** [pykaldi/pykaldi#180]
i have use “conda install -c pykaldi pykaldi”。 And i get same masseage ：
nltk -> numpy[version='1.5.*|1.6.*|1.7.*|1.8.*|1.9.*']
distributed -> dask[version='>=0.10.0'] -> pandas[version='>=0.18.0'] -> scipy -> numpy[version='1.5.*|>=1.15.1,<2.0a0']
scipy -> numpy[version='1.10.*|1.11.*|1.12.*|1.13.*|1.5.*|1.6.*|1.7.*|1.8.*|1.9.*|>=1.11.3,<2.0a0|>=1.15.1,<2.0a0|>=1.9.3,<2.0a0']
numba -> numpy[version='1.10.*|1.11.*|1.12.*|1.13.*|1.5.*|1.6.*|1.7.*|1.8.*|1.9.*|>=1.10,<1.11.0a0|>=1.11,<1.12.0a0|>=1.11.3,<2.0a0|>=1.12,<1.13
.0a0|>=1.13,<1.14.0a0|>=1.14,<1.15.0a0|>=1.9.3,<2.0a0']
bottleneck -> numpy[version='1.10.*|1.11.*|1.12.*|1.13.*|1.9.*|>=1.11.3,<2.0a0|>=1.9.3,<2.0a0']
numexpr -> numpy[version='1.10.*|1.11.*|1.12.*|1.13.*|1.6.*|1.7.*|1.8.*|1.9.*|>=1.11.3,<2.0a0|>=1.15.4,<2.0a0|>=1.16.4,<2.0a0|>=1.9.3,<2.0a0']
seaborn -> numpy[version='1.10.*|1.9.*|>=1.9.3']
Package openblas conflicts for:
pykaldi -> openblas[version='>=0.3.*']
numpy-base -> mkl-service[version='>=2,<3.0a0'] -> numpy[version='>=1.11.3,<2.0a0'] -> openblas==0.2.19
numexpr -> numpy[version='>=1.11.3,<2.0a0'] -> openblas[version='0.2.14|0.2.19']
Package numpydoc conflicts for:
scikit-image -> dask[version='>=0.5'] -> bokeh -> ipython -> jedi[version='>=0.10'] -> numpydoc
dask -> bokeh -> ipython -> jedi[version='>=0.10'] -> numpydoc
Package cython conflicts for:
h5py -> cython==0.22
anaconda==2019.10 -> cython==0.29.13[build='py37he6710b0_0|py36he6710b0_0|py27he6710b0_0']
cython
Package libopenblas conflicts for:
scikit-learn -> numpy=1.8 -> libopenblas[version='>=0.3.2,<0.3.3.0a0']

+++++++++++++++++
If I installed it successfully ？
but i pip list ，there is not “kaldi” or “pykaldi”

**Comment by vrmpx** [comment]
Seems like you have multiple conflicts (like openblas and cython).
I am not sure if these are warnings or errors, but you can always try `import kaldi` to test if the installation worked.
If that is not the case, then I would recommend that you create a new conda environment `conda create -n pykaldienv python=3.7` where you might be able to install pykaldi without any conflict with your current setup
