### ISSUE TITLE
protobuf installation step

### ISSUE THREAD

**Issue by zzdoug** [pykaldi/pykaldi#186]
Hi, I'm trying to get pykaldi installed inside a conda environment. I'm not very good with linux installations but have used conda in windows.  I'm now in step 2 and trying to install protobuf. 

While inside the activated environment, if I type 
`conda install protobuf=3.5`

what does that do?  In particular, have I installed the required C++ library and the Python package?  If not, what is involved in installing the C++ library?  I do see many C files and header files in the `anaconda3/envs/kaldi_0/include/google/protobuf` directory. (kaldi_0 is the environment name)

(btw I tried `conda install protobuf=3.5.0` and conda could not find that version.  But the above command was successful and installed version 3.5.2.)
Thanks very much for anyone's help.
![Screenshot from 2019-11-21 10-24-39](https://user-images.githubusercontent.com/5385985/69361205-3d5ef280-0c49-11ea-98f0-0f99715dad2f.png)

**Comment by vrmpx** [comment]
Hello,
For installing inside conda environments, you can directly install pykaldi by using one of the following commands:
if you want CUDA functionality: `conda install -c pykaldi pykaldi` 
or `conda install -c pykaldi pykaldi-cpu`

Your question seems a bit more like a conda-related question than a pykaldi issue. Regardless `conda install protobuf` installs the [Google Protocol Buffer library](https://developers.google.com/protocol-buffers) only. This is one of the requirements to install pykaldi, but there are many others. Please read the [README](https://github.com/pykaldi/pykaldi/blob/master/README.md) thoroughly to get a better sense of how to get pykaldi installed.
