### ISSUE TITLE
Publish on PyPI?

### ISSUE THREAD

**Issue by chrisspen** [pykaldi/pykaldi#188]
Would it be possible to publish this package on PyPI, to make installation easier?

There doesn't appear to be any way to actually install the package.

Even installing from source fails:

    $ git clone git@github.com:pykaldi/pykaldi.git
    $ cd pykaldi
    $ virtualenv -p python3.7 .env
    $ . .env/bin/activate
    (.env) python setup.py install
    Could not find pyclif.
    Please add pyclif binary to your PATH or set PYCLIF environment variable.

What is pyclif? It doesn't appear to be available on PyPI or the Ubuntu standard repo. Searching Google only finds references to this repo. I'm not sure if this was intentional, but setup.py should not depend on tools that are only available in the package it's meant to install.

**Comment by vrmpx** [comment]
Please read the [installation instructions on the README](https://github.com/pykaldi/pykaldi#from-source).
And refer to my reply #164 for what is needed for a pip package.

**Comment by chrisspen** [comment]
Sorry, didn't see the conda commands.

**Comment by chrisspen** [comment]
The conda commands don't seem to result in a functioning install, even though I already have the `libkaldi-asr` Ubuntu package installed.

I ran:

    conda create --prefix ./.cenv -c defaults -y python=3.6
    conda activate ./.cenv
    conda install -c pykaldi pykaldi-cpu
    python
    >>> from kaldi.asr import NnetLatticeFasterRecognizer
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/chris/git/pykaldi/kaldi/__init__.py", line 14, in <module>
        from . import base
      File "/home/chris/git/pykaldi/kaldi/base/__init__.py", line 1, in <module>
        from ._kaldi_error import *
    ModuleNotFoundError: No module named 'kaldi.base._kaldi_error'

**Comment by vrmpx** [comment]
I ran all commands successfully in a docker container running miniconda.

So it seems to me that this is likely due to the location of where you ran this command.
It is picking on this file: `/home/chris/git/pykaldi/kaldi/__init__.py` instead of the ones shipped with the conda package.
