### ISSUE TITLE
./install_kaldi.sh fails with wave-reader.cc:254:10: error: call to 'abs' is ambiguous

### ISSUE THREAD

**Issue by kkawabat** [pykaldi/pykaldi#210]
Hello I am trying to install pykaldi on macOS 10.15.3 (Catalina) and it has been a rather frustrating uphill battle the whole way through. I was able to get through `./install_clif.sh` by adding macOS.sdk/usr/include path to the `build.ninja` with the help of this [suggestion](https://github.com/pykaldi/pykaldi/issues/120#issuecomment-490003277)  (i needed to -isystem commandlinttool's sdk usr/include libraries) but then I ran into the following issue while running `./install_kaldi.sh`:

```
g++ -std=c++11 -I.. -I/Users/kankawabata/Documents/auralanalytics/analytics_engine/pykaldi/tools/kaldi/tools/openfst/include -O1  -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_CLAPACK -msse -msse2 -pthread -g  -fPIC -Wno-mismatched-tags  -c -o wave-reader.o wave-reader.cc

wave-reader.cc:254:10: error: call to 'abs' is ambiguous
      && std::abs(static_cast<int64>(riff_chunk_read) +
         ^~~~~~~~
/usr/local/include/stdlib.h:132:6: note: candidate function
int      abs(int) __pure2;
         ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/math.h:765:1: note: candidate function
abs(double __lcpp_x) _NOEXCEPT {return ::fabs(__lcpp_x);}
^
/Library/Developer/CommandLineTools/usr/include/c++/v1/math.h:769:1: note: candidate function
abs(long double __lcpp_x) _NOEXCEPT {return ::fabsl(__lcpp_x);}
^
1 error generated.
```
[Here](https://github.com/kaldi-asr/kaldi/blob/master/src/feat/wave-reader.cc#L254) is the corresponding line in the kaldi source code. the error went away when I monkey patching the line from:

```
std::abs(static_cast<int64>(riff_chunk_read) +
                  static_cast<int64>(data_chunk_size) -
                  static_cast<int64>(riff_chunk_size)) > 1)
```

to:
```
std::abs((int)(static_cast<int64>(riff_chunk_read) +
                  static_cast<int64>(data_chunk_size) -
                  static_cast<int64>(riff_chunk_size))) > 1)
```

But I don't have much experience with c++ and I'm not sure if this actually solves the underlining issue on why it failed. I would appreciate some feedback as to why it's failing.

in case this adds additional context, here is the output of the failed command if I used --verbose mode

> g++ -std=c++11 -I.. -I/Users/kankawabata/Documents/auralanalytics/analytics_engine/pykaldi/tools/kaldi/tools/openfst/include -O1  -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_CLAPACK -msse -msse2 -pthread -g  -fPIC -Wno-mismatched-tags -c -o wave-reader.o wave-reader.cc -v
> Apple clang version 11.0.0 (clang-1100.0.33.17)
> Target: x86_64-apple-darwin19.3.0
> Thread model: posix
> InstalledDir: /Library/Developer/CommandLineTools/usr/bin
>  "/Library/Developer/CommandLineTools/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.15.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -disable-free -disable-llvm-verifier -discard-value-names -main-file-name wave-reader.cc -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fno-strict-return -masm-verbose -munwind-tables -target-sdk-version=10.15 -target-cpu penryn -target-feature +sse -target-feature +sse2 -dwarf-column-info -debug-info-kind=standalone -dwarf-version=4 -debugger-tuning=lldb -ggnu-pubnames -target-linker-version 530 -v -coverage-notes-file /Users/kankawabata/Documents/auralanalytics/analytics_engine/pykaldi/tools/kaldi/src/feat/wave-reader.gcno -resource-dir /Library/Developer/CommandLineTools/usr/lib/clang/11.0.0 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I .. -I /Users/kankawabata/Documents/auralanalytics/analytics_engine/pykaldi/tools/kaldi/tools/openfst/include -D KALDI_DOUBLEPRECISION=0 -D HAVE_EXECINFO_H=1 -D HAVE_CXXABI_H -D HAVE_CLAPACK -I/usr/local/include -stdlib=libc++ -internal-isystem /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1 -O1 -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -Wno-mismatched-tags -Wno-framework-include-private-from-public -Wno-atimport-in-framework-header -Wno-extra-semi-stmt -Wno-quoted-include-in-framework-header -std=c++11 -fdeprecated-macro -fdebug-compilation-dir /Users/kankawabata/Documents/auralanalytics/analytics_engine/pykaldi/tools/kaldi/src/feat -ferror-limit 19 -fmessage-length 179 -pthread -stack-protector 1 -fstack-check -mdarwin-stkchk-strong-link -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fobjc-runtime=macosx-10.15.0 -fcxx-exceptions -fexceptions -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o wave-reader.o -x c++ wave-reader.cc
> clang -cc1 version 11.0.0 (clang-1100.0.33.17) default target x86_64-apple-darwin19.3.0
> ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1"
> ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/local/include"
> ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/Library/Frameworks"
> #include "..." search starts here:
> #include <...> search starts here:
>  ..
>  /Users/kankawabata/Documents/auralanalytics/analytics_engine/pykaldi/tools/kaldi/tools/openfst/include
>  /usr/local/include
>  /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1
>  /Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include
>  /Library/Developer/CommandLineTools/usr/include
>  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
>  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks (framework directory)
> End of search list.

### Things I tried
I thought it has something to do with pathing similar to ./install_clif.sh

so I also attempted to add sdk/usr/include and commandlinetool/usr/include as cxxflags
from:
`./configure` --shared`
to:
```
CXX_SYSTEM_INCLUDE_DIR="/Library/Developer/CommandLineTools/usr/include/c++/v1"
CXX_SDK_SYSTEM_INCLUDE_DIR="$/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/"
CXXFLAGS="-isystem $CXX_SYSTEM_INCLUDE_DIR -isystem $CXX_SDK_SYSTEM_INCLUDE_DIR" ./configure --shared
```
Unfortunately, the issue still persists so I reverted the change

---
I also tried adding `#include <cstdlib>` header at the top of the `wave-reader.cc` as this seems to be a common solution to abs ambiguous error on stackoverflow. However this also didn't solve the issue 

Thank you.

**Comment by kkm000** [comment]
What is really weird here is `std::abs(int64_t)` or something like it is not listed among candidate function for overload resolution. The compiler considers `abs(int)`, `abs(double)` and `abs(long double)`. You mention you had to add an include path to the compilation, and this is what may have caused this. I know very little about Macs to be of help, but this is a clue.

**Comment by kkawabat** [comment]
Turned out this error was because of `-I/usr/local/include` messing up the header file search order. A while back I used this solution [here](https://stackoverflow.com/questions/58278260/cant-compile-a-c-program-on-a-mac-after-upgrading-to-catalina-10-15/58349403#58349403) to fix missing header files for macOS Catalina which probably messed up the `#include_next` commands in the header files. 

Removing the files in `/usr/local/include` seems to have worked and seems safe to do [so](https://apple.stackexchange.com/questions/231832/homebrew-and-usr-local-include-question)
