### ISSUE TITLE
Update Docker Image to Ubuntu 18.04

### ISSUE THREAD

**Issue by colinbjohnson** [pykaldi/pykaldi#211]
I have a project that requires me to build a pykaldi Docker Image running Ubuntu 18.04 as a base Docker Image. I can provide a PR with this update and confirm that both `Dockerfile` and `Dockerfile.min` build properly.

The reason I've been asked to update to 18.04 (I'm doing the work on behalf of a pykaldi user) is that the pandas 1.0.3 (which they'd like to use) requires python 3.6.1 or later, which is not available via Ubuntu Packages.

This also has the benefit of moving some packages to later EOL support dates (python 3.5 EOL date is 2020-09-13, per https://devguide.python.org/#status-of-python-branches).

**Comment by vrmpx** [comment]
Looking forward for the PR.
Thanks!

**Comment by colinbjohnson** [comment]
Relatively simple, to be honest: https://github.com/pykaldi/pykaldi/pull/213.

I did test both a `Dockerfile` and `Dockerfile.min` build to completion.

**Comment by colinbjohnson** [comment]
Has been merged in.
