### ISSUE TITLE
move from "svn co" to "git clone" or "svn export" in for llvm/install_clif.sh

### ISSUE THREAD

**Issue by colinbjohnson** [pykaldi/pykaldi#214]
I would be interested in submitting a PR that modifies the `install_clif.sh` file to do one of the following:

1. Moves to `git clone` (from svn) to reflect the move of the official repositories to "git" (note: I wanted to confirm this and the https://llvm.org/ home page states "GitHub Migration: Completed! Many thanks to all the participants").

2. Moves the commands `svn co https://llvm.org/svn/llvm-project/llvm/trunk@307315 llvm` and `svn co https://llvm.org/svn/llvm-project/cfe/trunk@307315 clang` to `svn co https://llvm.org/svn/llvm-project/llvm/trunk@307315 llvm` and `svn co https://llvm.org/svn/llvm-project/cfe/trunk@307315 clang`, respectively.

My feeling is `git clone` would be ideal and I'm happy to submit a PR to either move to using `git clone` or `svn export` if either is preferred.

**Comment by vrmpx** [comment]
Go for it. My sole recommendation would be just make sure you're cloning the same version as the svn.
