### ISSUE TITLE
Not Supported - Issue while installing pykaldi from source

### ISSUE THREAD

**Issue by Manogna-Nadella** [pykaldi/pykaldi#222]
Hi,

I am trying to install pykaldi. I have followed all the installation steps mentioned in the below link
https://github.com/pykaldi/pykaldi#installation

I have successfully installed all the dependencies using the scripts under tools directory

However when i am running "python setup.py install", i am getting the following error. I also set KALDI_DIR environment variable to the path where kaldi is installed
Also, i have run all the installation steps at the same time

"Kaldi installation at /data/manogna/pykaldi/tools/kaldi is not supported.
Please update Kaldi to match https://github.com/pykaldi/kaldi/tree/pykaldi"

Any help regarding this would be appreciated

Regards,
Manogna Nadella

**Comment by Manogna-Nadella** [comment]
Below is the error. There seems to be a problem with an option for git

(pykaldi_env) [jioapp@AZDEJIOADSAP02 pykaldi]$ python setup.py install
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

Kaldi installation at /data/manogna/pykaldi/tools/kaldi is not supported.
Please update Kaldi to match https://github.com/pykaldi/kaldi/tree/pykaldi.
--------------------------------------------------------------------------------------
If i try to correct it and change 'C' to 'c', the error is as below
(pykaldi_env) [jioapp@AZDEJIOADSAP02 pykaldi]$ python setup.py install
fatal: Not a valid commit name 5dc5d41bb603ba935c6244c7b32788ea90b9cee3

Kaldi installation at /data/manogna/pykaldi/tools/kaldi is not supported.
Please update Kaldi to match https://github.com/pykaldi/kaldi/tree/pykaldi.

**Comment by bmilde** [comment]
Note that we changed a lot recently to allow PyKaldi to build with newer OS versions, newer gcc version + Python 3.8 and Python 3.9. Please try again and let us know with a new issue if you still have problems. Thank you.

**Comment by vivianamarquez** [comment]
@Manogna-Nadella I was facing a similar problem... then I went to `kaldi/tools/extras` and ran `./install_mkl.sh`
