### ISSUE TITLE
Dim mismatch

### ISSUE THREAD

**Issue by mnbv7581** [pykaldi/pykaldi#228]
**When I ran the GmmLatticeFasterRecognizer using the mono and tri1 models, it worked.
However, when using the tri2 to tri4 models I get the following error. I want to know the solution.**

`ERROR ([5.5.201~1-7d4bd]:LogLikelihoodZeroBased():decodable-am-diag-gmm.cc:50) Dim mismatch: data dim = 39 vs. model dim = 40
ERROR ([5.5.201~1-7d4bd]:LogLikelihoodZeroBased():decodable-am-diag-gmm.cc:50) Dim mismatch: data dim = 39 vs. model dim = 40
Traceback (most recent call last):
  File "main.py", line 53, in <module>
    out = asr.decode(feats)
  File "/usr/local/lib/python3.7/dist-packages/pykaldi-0.1.2-py3.7-linux-x86_64.egg/kaldi/asr.py", line 145, in decode
    self.decoder.decode(self._make_decodable(input))
RuntimeError: C++ exception: 
WARNING ([5.5.201~1-7d4bd]:~HashList():util/hash-list-inl.h:117) Possible memory leak: 1023 != 1024: you might have forgotten to call Delete on some Elems
`

**Comment by geoph9** [comment]
This is a kaldi error. In your case, you used a `tri1` model, so I guess that your features are Deltas + Delta-Deltas. For your `tri4` model I suspect that you also used an LDA transformation (which would result in 40 dimension features). So, in your `feats_rspecifier` add the corresponding script (inside the pipeline) for the LDA transformation, just as you would with kaldi. (Check `steps/decode.sh` if you are not sure on how that is done in Kaldi.)
