### ISSUE TITLE
Docker image version with python3.8 (Ubuntu20.04)

### ISSUE THREAD

**Issue by lucgeo** [pykaldi/pykaldi#229]
Hello,

I'm working on a project where I want to take advantage of new feature of Python3.8, the [multiprocessing shared memory library]. Could you please provide a docker image based on Ubuntu 20.04, where default python is 3.8? I tried to do it myself, but I encountered some issues installing protobuf and clif after that.

Thank you!

[multiprocessing shared memory library]: https://docs.python.org/3/library/multiprocessing.shared_memory.html

**Comment by geoph9** [comment]
You could still use Ubuntu 18.04 and install python 3.8 on it via an external repository (check [here](https://linuxize.com/post/how-to-install-python-3-8-on-ubuntu-18-04/) for an example). 

For protobuf check [this](https://github.com/protocolbuffers/protobuf/issues/6958 ) issue which says that `python 3.8` is supported on version `3.11.2`.

For CLIF, you should be careful if you have 2 python versions installed. Check the [building instructions](https://github.com/google/clif#building) and you will probably be able to resolve the issue by changing in params in cmake.

**Comment by bmilde** [comment]
We have now released whl files for Python 3.7, 3.8 and 3.9. That should make the installation much easier and you could install those in your own docker project as well!

Unfortunately the official pykaldi docker builds are unmaintained atm. If you'd like to maintain these, please get in touch.
