### ISSUE TITLE
give more weight to the language model

### ISSUE THREAD

**Issue by lucgeo** [pykaldi/pykaldi#236]
Hi,

I wish to play a bit with the acoustic model and language model weights, but I don't know which parameters I have to modify. One of them I think is "decodable_opts.acoustic_scale" which in the examples in 1.0. Can somebody please explain which is the range of this parameter? What happens if I increase/decrease it? Does it exist a similar parameter for the language model?

Thanks!

**Comment by bmilde** [comment]
This is not really related to PyKaldi, but Kaldi. You can search for Kaldi+acoustic_scale as well, thats how Kaldi models it. Other toolkits have a weight for LM, Kaldi has one for the acoustic model.
