### ISSUE TITLE
Error attempting to run ./install_clif.sh on macOS Catalina 10.15.7. Can't build proto_util.cc

### ISSUE THREAD

**Issue by enderzhangpro** [pykaldi/pykaldi#246]
When attempting to install pykaldi I can't run ./install_clif.sh. It keeps crashing when trying to build proto_util.cc. I keep getting this:
error: cannot initialize a member subobject of type 'Py_ssize_t' (aka 'long') with an rvalue of type 'nullptr_t'
I can't figure out a fix. Any help?

**Comment by bmilde** [comment]
probably related https://github.com/pykaldi/pykaldi/issues/234

**Comment by bmilde** [comment]
Should be fixed now, I successfully compiled the current version of PyKaldi on Mac as well (with Python 3.9 from brew)
