### ISSUE TITLE
Phone level recognition

### ISSUE THREAD

**Issue by FirasHm** [pykaldi/pykaldi#254]
Hello, thank you for this great work! I would like to get the phone recognition level. Does PyKaldi have a function for that ?

**Comment by bmilde** [comment]
PyKaldi is just a wrapper around Kaldi, that said, you can train phone recognition models with Kaldi, see for example the TIMIT recipe in Kaldi.  Probably you can also use some output of TDNN-HMM nnet3 models. Basically the posteriorgram (forward propagation through the neural network part) of most TDNN-HMMs recipes in Kaldi egs is actually mono-phone, so you could use that as well.
