### ISSUE TITLE
clif build fails due to error in LLI building on Fedora 33 with GCC10

### ISSUE THREAD

**Issue by dmhowcroft** [pykaldi/pykaldi#255]
When I got to `./install_clif`, I got the following error:

    pykaldi/tools/clif_backend/llvm/include/llvm/ExecutionEngine/Orc/OrcRemoteTargetClient.h:722:26: error: could not convert ‘((llvm::orc::remote::OrcRemoteTargetClient<ChannelT>*)this)->callB<llvm::orc::remote::OrcRemoteTargetRPCAPI::ReadMem>(Src, Size)’ from ‘Expected<vector<unsigned char,allocator<unsigned char>>>’ to ‘Expected<vector<char,allocator<char>>>’
    722 |     return callB<ReadMem>(Src, Size);

Applying the patch suggested [here](https://bugzilla.redhat.com/attachment.cgi?id=1389687&action=diff) fixed it.

**Comment by bmilde** [comment]
Thanks for the feedback and trying out the red had patch! Seems to solve compilation in Gcc9 as well: https://github.com/pykaldi/pykaldi/pull/226

We'll probably include the fix into install_clif.sh, so that the files gets patched automatically.
