### ISSUE TITLE
Can I use the pykaldi to replace kaldi in all things.(a whole process such, as training a model )

### ISSUE THREAD

**Issue by friedrich1993322** [pykaldi/pykaldi#257]
I have to say, the pykaldi has not so much instructions text as kaldi. Now I want to train a model. If I use kaldi, I can use the example thchs-30 in the folder egs. Could you tell me, can I use pykaldi to do the same thing? How can I use the pykaldi to achieve this purpose?

I am a beginner, please tell me what I should do.

**Comment by tjysdsg** [comment]
From my understanding, you have to rewrite all bash script and perl script if you wanna go full python, which is an enormous amount of work. So for training, you probably wanna stick with kaldi scripts.

I think pykaldi is mostly used for inference. I used pykaldi to load a pretrained model and do inferring in one of my projects.
