### ISSUE TITLE
test failure

### ISSUE THREAD

**Issue by pankaj2701** [pykaldi/pykaldi#27]
I installed pykaldi on ubuntu 16.04. Installation went all well without any errors. But when I ran the 
command python setup.py test, following error was reported
running test
running egg_info
writing requirements to pykaldi.egg-info/requires.txt
writing pykaldi.egg-info/PKG-INFO
writing top-level names to pykaldi.egg-info/top_level.txt
writing dependency_links to pykaldi.egg-info/dependency_links.txt
reading manifest file 'pykaldi.egg-info/SOURCES.txt'
writing manifest file 'pykaldi.egg-info/SOURCES.txt'
running build_ext
Using PYCLIF: /home/pankaj/asr/pykaldi/env/bin/pyclif
Using CLIF_MATCHER: /home/pankaj/asr/pykaldi/env/clang/bin/clif-matcher
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pankaj/asr/pykaldi/build
ninja: no work to do.

copying build/lib/kaldi/_clif.so -> kaldi
error: can't copy 'build/lib/kaldi/asr.so': doesn't exist or not a regular file

**Comment by dogancan** [comment]
Thanks for the report. I just pushed a fix. Luckily, you won't need to reinstall. Try rerunning the tests after pulling the latest master branch.
