### ISSUE TITLE
Any pythonic way to fine-tune/train Kaldi model(final.mdl)

### ISSUE THREAD

**Issue by amiyamandal-dev** [pykaldi/pykaldi#286]
is their any way to fine-tune/train kaldi model(final.mdl) using pykaldi. I have tried lot of way but docs it incomplete or hard to understand.

It would be a great help will try to make a docs on it.

**Comment by bmilde** [comment]
There is currently no recipe to train/fine-tune models with PyKaldi. I don't want to discourage you, but it's gonna be a non-trivial task to translate the bash/python scripts from Kaldi into PyKaldi equivalents. It's not impossible though and certainly something that would be desirable. Please let us know if you have a working script!
