### ISSUE TITLE
pykaldi intall on ubuntu 18

### ISSUE THREAD

**Issue by liroda** [pykaldi/pykaldi#289]
I have  successfully install clif kaldi  
when i do python setup.py install  the last , The error comes 
i do no know what happen , can help me?

Using PYCLIF: /usr/local/bin/pyclif
Using CLIF_MATCHER: /usr/clang/bin/clif-matcher
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/pykaldi/build
[3/987] Generating iostream-clifwrap.cc, iostream-clifwrap.h, iostream-clifwrap-init.cc
FAILED: kaldi/base/iostream-clifwrap.cc kaldi/base/iostream-clifwrap.h kaldi/base/iostream-clifwrap-init.cc 
cd /opt/pykaldi/build/kaldi/base && /usr/local/bin/pyclif --py3output --matcher_bin=/usr/clang/bin/clif-matcher --ccdeps_out /opt/pykaldi/build/kaldi/base/iostream-clifwrap.cc --header_out /opt/pykaldi/build/kaldi/base/iostream-clifwrap.h --ccinit_out /opt/pykaldi/build/kaldi/base/iostream-clifwrap-init.cc --modname=kaldi.base._iostream --prepend=clif/python/types.h -I/opt/pykaldi/kaldi/lib -I/opt/pykaldi/kaldi -I/opt/pykaldi/build/kaldi -I/opt/pykaldi/tools/kaldi/src "-f-I/usr/include/python3.6m              -I/opt/pykaldi/kaldi/lib              -I/opt/pykaldi/kaldi              -I/opt/pykaldi/build/kaldi              -I/opt/pykaldi/tools/kaldi/src              -I/usr/clang/lib/clang/5.0.0/include               -std=c++11 -I.. -I/opt/pykaldi/tools/kaldi/tools/openfst/include -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_ATLAS -I/opt/pykaldi/tools/kaldi/tools/ATLAS_headers/include -msse -msse2 -pthread -g -fPIC -Wno-maybe-uninitialized" /opt/pykaldi/kaldi/base/iostream.clif && /opt/pykaldi/tools/use_namespace.sh /opt/pykaldi/build/kaldi/base/iostream-clifwrap.cc

Line .123456789.123456789.123456789.123456789
   1:"""C++ std::iostream wrapper.\n
   2:\n
   3:This module provides the wrappers needed for working with C++ std::iostream\n
   4:instances. The wrappers for input and/or output stream types do not expose any\n
   5:members other than `good` since we do not want to work with them directly in\n
   6:Python. They can be used for wrapping methods and functions that accept or\n
   7:return iostream objects. The get_* utility functions provide the handles for\n
   8:the standard C++ streams.\n
   9:"""\n
  10:\n
  11:from "base/iostream-ext.h":\n
  12:  namespace `::std`:\n
  13:    class istream:\n
  14:      """Input stream."""\n
  15:      def `good` as good(self) -> bool:\n
  16:        """Checks whether the state of the stream is good."""\n
  17:\n
  18:    class ostream:\n
  19:      """Output stream."""\n
  20:      def `good` as good(self) -> bool:\n
  21:        """Checks whether the state of the stream is good."""\n
  22:\n
  23:    class iostream(istream):\n
  24:      """Input/output stream."""\n
  25:      pass\n
  26:\n
  27:    def `GetStdinPtr` as get_stdin() -> istream:\n
  28:      """Returns standard input stream."""\n
  29:\n
  30:    def `GetStdoutPtr` as get_stdout() -> ostream:\n
  31:      """Returns standard output stream."""\n
  32:\n
  33:    def `GetStderrPtr` as get_stderr() -> ostream:\n
  34:      """Returns standard error stream."""\n
  35:\n
  36:    def `Flush` as flush(os: ostream):\n
  37:      """Flushes output stream."""\n
  38:\n
  39:    def `Read` as read_text(is: istream) -> str:\n
  40:      """Reads and returns the contents of the stream as a unicode string."""\n
  41:\n
  42:    def `Read` as read(is: istream) -> bytes:\n
  43:      """Reads and returns the contents of the stream as a bytes object."""\n
  44:\n
  45:    def `ReadLine` as readline_text(is: istream) -> str:\n
  46:      """Reads and returns a line from the input stream.\n
  47:\n
  48:      If the stream is already at EOF, an empty unicode string is returned.\n
  49:      """\n
  50:\n
  51:    def `ReadLine` as readline(is: istream) -> bytes:\n
  52:      """Reads and returns a line from the input stream.\n
  53:\n
  54:      If the stream is already at EOF, an empty bytes object is returned.\n
  55:      """\n
  56:\n
  57:    def `Write` as write_text(os: ostream, s: str):\n
  58:      """Writes unicode string to output stream."""\n
  59:\n
  60:    def `Write` as write(os: ostream, b: bytes):\n
  61:      """Writes bytes object to output stream."""\n
_ParseError: Expected {Suppress:(line_end) | {'from' string enclosed in '"' Suppress:(':') Suppress:(line_end) - indented block} | {Suppress:('from') WordEnd name [. name]... - 'import' name} | {Empty Suppress:('from') string enclosed in '"' Suppress:('import') - Suppress:('*') [Suppress:('as') - name]} | {'type' - name Suppress:('=') type} | {'use' - string enclosed in '`' Suppress:('as') - name [. name]...} | {'interface' - name - Suppress:('<') - name [{Suppress:(',') name}]... - Suppress:('>') - Suppress:(':') Suppress:(line_end) - indented block}}, found '"'  (at char 0), (line:1, col:1)
[4/987] Generating timer-clifwrap.cc, timer-clifwrap.h, timer-clifwrap-init.cc
FAILED: kaldi/base/timer-clifwrap.cc kaldi/base/timer-clifwrap.h kaldi/base/timer-clifwrap-init.cc 
cd /opt/pykaldi/build/kaldi/base && /usr/local/bin/pyclif --py3output --matcher_bin=/usr/clang/bin/clif-matcher --ccdeps_out /opt/pykaldi/build/kaldi/base/timer-clifwrap.cc --header_out /opt/pykaldi/build/kaldi/base/timer-clifwrap.h --ccinit_out /opt/pykaldi/build/kaldi/base/timer-clifwrap-init.cc --modname=kaldi.base._timer --prepend=clif/python/types.h -I/opt/pykaldi/kaldi/lib -I/opt/pykaldi/kaldi -I/opt/pykaldi/build/kaldi -I/opt/pykaldi/tools/kaldi/src "-f-I/usr/include/python3.6m              -I/opt/pykaldi/kaldi/lib              -I/opt/pykaldi/kaldi              -I/opt/pykaldi/build/kaldi              -I/opt/pykaldi/tools/kaldi/src              -I/usr/clang/lib/clang/5.0.0/include               -std=c++11 -I.. -I/opt/pykaldi/tools/kaldi/tools/openfst/include -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_ATLAS -I/opt/pykaldi/tools/kaldi/tools/ATLAS_headers/include -msse -msse2 -pthread -g -fPIC -Wno-maybe-uninitialized" /opt/pykaldi/kaldi/base/timer.clif && /opt/pykaldi/tools/use_namespace.sh /opt/pykaldi/build/kaldi/base/timer-clifwrap.cc

**Comment by bmilde** [comment]
PyKaldi's current supported Python versions are 3.7, 3.8 and 3.9. Please test again with a newer Python version. We also have released pre-compiled whl packages for an easier installation.
