### ISSUE TITLE
SingleUtteranceGmmDecoder.feature_pipeline() causes segmentation fault

### ISSUE THREAD

**Issue by vb42e** [pykaldi/pykaldi#294]
Kaldi:  compiled from master (d366a93aad)
PyKaldi: pykaldi-cpu 0.1.3 py37h14c3975_1 pykaldi
Python: 3.7.11
OS: Manjaro Linux VM

When calling `feature_pipeline()` from a `SingleUtteranceGmmDecoder` object twice, a segmentation fault occurs.

I am trying to run online GMM based decoding. I translated a similar c++ example that can be found here: <https://kaldi-asr.org/doc/online_decoding.html#GMM-based>, to PyKaldi. But when I try to feed the `OnlineFeaturePipeline` instance with audio data, it crashes with a segmentation fault. 

I could enclose the error to being thrown when trying to get the feature pipeline twice and created following minimal working example:

```py
#!/usr/bin/env python

from kaldi.online2 import (
    SingleUtteranceGmmDecoder,
    OnlineGmmAdaptationState,
    OnlineFeaturePipelineCommandLineConfig,
    OnlineGmmDecodingConfig,
    OnlineFeaturePipelineConfig,
    OnlineFeaturePipeline,
    OnlineGmmDecodingModels,
)
from kaldi.fstext import read_fst_kaldi

import subprocess, sys
from os.path import expanduser

base_path = expanduser("~/speech/kaldi/asr")
kaldi_root = expanduser("~/speech/kaldi/kaldi")

subprocess.run(
    f"{kaldi_root}/src/bin/matrix-sum --binary=false scp:{base_path}/data/train/cmvn.scp - >/tmp/global_cmvn.stats", shell=True
)

feature_cmdline_config = OnlineFeaturePipelineCommandLineConfig()
feature_cmdline_config.feature_type = "mfcc"
feature_cmdline_config.mfcc_config = f"{base_path}/conf/mfcc.conf"
feature_cmdline_config.global_cmvn_stats_rxfilename = "/tmp/global_cmvn.stats"
feature_config = OnlineFeaturePipelineConfig.from_config(feature_cmdline_config)

decode_config = OnlineGmmDecodingConfig()
decode_config.faster_decoder_opts.beam = 11.0
decode_config.faster_decoder_opts.max_active = 7000
decode_config.model_rxfilename = f"{base_path}/exp/mono/final.mdl"


gmm_models = OnlineGmmDecodingModels(decode_config)
pipeline_prototype = OnlineFeaturePipeline(feature_config)
decode_fst = read_fst_kaldi(f"{base_path}/exp/mono/graph/HCLG.fst")
adaptation_state = OnlineGmmAdaptationState()

decoder = SingleUtteranceGmmDecoder(
    decode_config, gmm_models, pipeline_prototype, decode_fst, adaptation_state
)

# this one does not crash, but using pipe.accept_waveform crashed for me
pipe = decoder.feature_pipeline()
# the next line crashes with "segmentation fault (core dumped)"
pipe = decoder.feature_pipeline()
```

**Comment by bmilde** [comment]
You're using an old version of PyKaldi. You need a matching Kaldi installation from https://github.com/pykaldi/kaldi, the master version there is compatible with the master version of PyKaldi. 

If you really want to use an old v0.1 PyKaldi, you'd need https://github.com/pykaldi/kaldi/tree/pykaldi_01

I really recommend to use the latest version though since you're otherwise likely to run into compatibility issues with newer models.
