### ISSUE TITLE
Failed to install pykaldi(installing  CLIF)

### ISSUE THREAD

**Issue by dreamermary** [pykaldi/pykaldi#298]
I followed the instructions and ran the following to commands to install pykaldi:
```
git clone https://github.com/pykaldi/pykaldi.git
cd pykaldi

sudo apt-get install autoconf automake cmake curl g++ git graphviz \
    libatlas3-base libtool make pkg-config subversion unzip wget zlib1g-dev
pip install numpy pyparsing ninja 
git clone -b pykaldi https://github.com/pykaldi/clif
git clone -b pykaldi https://github.com/pykaldi/kaldi

cd tools
./check_dependencies.sh 
./install_protobuf.sh  
./install_clif.sh  
```
I get this error for the last line:
```
-- Checking for module 'protobuf'
--   Found protobuf, version 3.19.3
-- Found PythonLibs: /root/data/software/miniconda/envs/fairseq/lib/libpython3.8.so (found version "3.8.11") 
-- Configuring done
-- Generating done
-- Build files have been written to: /root/data/git/fairseq/pykaldi/tools/clif_backend/build_matcher
[98/1787] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/Process.cpp.o
In file included from /root/data/git/fairseq/pykaldi/tools/clif_backend/llvm/lib/Support/Unix/Unix.h:24:0,
                 from /root/data/git/fairseq/pykaldi/tools/clif_backend/llvm/lib/Support/Unix/Process.inc:14,
                 from /root/data/git/fairseq/pykaldi/tools/clif_backend/llvm/lib/Support/Process.cpp:85:
/root/data/git/fairseq/pykaldi/tools/clif_backend/llvm/include/llvm/Support/Errno.h:34:13: warning: mangled name for ‘decltype (F(llvm::sys::RetryAfterSignal::As ...)) llvm::sys::RetryAfterSignal(const FailT&, const Fun&, const Args& ...) [with FailT = int; Fun = int(int, stat*) throw (); Args = {int, stat*}]’ will change in C++17 because the exception specification is part of a function type [-Wnoexcept-type]
 inline auto RetryAfterSignal(const FailT &Fail, const Fun &F,
             ^~~~~~~~~~~~~~~~
[349/1787] Building CXX object lib/CodeGen/CMakeFiles/LLVMCodeGen.dir/LatencyPriorityQueue.cpp.o
SSH CONNECTION CLOSED
```

My system spec(I have a conda virtual env):
* python 3.8.11
* ubuntu1 18.04.1
* gcc version 7.4.0
* Numpy 1.19.5

**Comment by the01** [comment]
The instructions from the [github actions](https://github.com/pykaldi/pykaldi/blob/master/.github/workflows/test.yml) should use the ubuntu 18.04 base and are working.

Is it possible that it would have continued, but you just lost the ssh connection?

**Comment by dreamermary** [comment]
> The instructions from the [github actions](https://github.com/pykaldi/pykaldi/blob/master/.github/workflows/test.yml) should use the ubuntu 18.04 base and are working.
> 
> Is it possible that it would have continued, but you just lost the ssh connection?

it is certain , lost the ssh connection is because run this instruction `./install_clif.sh` (I have tried three times)

**Comment by bmilde** [comment]
I'm not seeing an error here and there are always some warnings during the build process. Looks like you lost the SSH connection. I'd recommend to compile inside a screen (https://www.gnu.org/software/screen/).

Btw you do not need to clone https://github.com/pykaldi/clif and https://github.com/pykaldi/kaldi, the install scripts in tools/  do this for you.
