### ISSUE TITLE
ImportError: libkaldi-base.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by aisolus02** [pykaldi/pykaldi#311]
I installed pykaldi, follow:
http://ltdata1.informatik.uni-hamburg.de/pykaldi/
When I try import kaldi, I receive error:
ImportError: libkaldi-base.so: cannot open shared object file: No such file or directory

File path.sh:                              
export KALDI_ROOT=kaldi
export LD_LIBRARY_PATH=$KALDI_ROOT/src/lib:$KALDI_ROOT/tools/openfst-1.6.7/lib:\
$LD_LIBRARY_PATH
export PATH=$KALDI_ROOT/src/lmbin/:$KALDI_ROOT/../kaldi_lm/:$PWD/utils/:$KALDI_\
ROOT/src/bin:$KALDI_ROOT/tools/openfst/bin:$KALDI_ROOT/src/fstbin/:$KALDI_ROOT/\
src/gmmbin/:$KALDI_ROOT/src/featbin/:$KALDI_ROOT/src/lm/:$KALDI_ROOT/src/sgmmbi\
n/:$KALDI_ROOT/src/sgmm2bin/:$KALDI_ROOT/src/fgmmbin/:$KALDI_ROOT/src/latbin/:$\
KALDI_ROOT/src/nnetbin:$KALDI_ROOT/src/nnet2bin/:$KALDI_ROOT/src/online2bin/:$K\
ALDI_ROOT/src/ivectorbin/:$KALDI_ROOT/src/kwsbin:$KALDI_ROOT/src/nnet3bin:$KALD\
I_ROOT/src/chainbin:$KALDI_ROOT/tools/sph2pipe_v2.5/:$KALDI_ROOT/src/rnnlmbin:$\
PWD:$PATH

**Comment by bmilde** [comment]
I recommend following the new "install from wheel" instructions in pykaldi's readme
