### ISSUE TITLE
clif setup.py fails for python3.10

### ISSUE THREAD

**Issue by JPunch** [pykaldi/pykaldi#314]
The version comparison at the top of setup.py fails.

    if py_version < ("2", "7") or py_version[0] == '3' and py_version < ("3", "4"):
        raise RuntimeError('Python version 2.7 or 3.4+ required')

This fails as `"10" < "4"` is True.

I changed the py_version to a tuple of ints to get around it but specifiying `python_requires='>=3.4.0'` in the setuptools.setup would be a better fix.

**Comment by bmilde** [comment]
Thank you. Is it compiling through and does it work with 3.10 otherwise?

**Comment by JPunch** [comment]
Just finished the install.

It failed a couple times on `python setup.py install` but I think that's to do with the amount of cpu cores on the vm I'm using.

The results from `pythonsetup.py test` is 

     167 passed, 8 skipped in 1.92s

Are there some other tests I should perform before using the installation?

**Comment by bmilde** [comment]
It's fixed now and compiles for Python 3.10 and 3.11
