### ISSUE TITLE
python setup.py test failes with kaldi module not found

### ISSUE THREAD

**Issue by jumbothecomdian** [pykaldi/pykaldi#316]
As the tittle suggests, I get the following error when running 'python setup.py test'

`============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-7.2.2, pluggy-1.0.0 -- /home/foo/build/pykaldi/env/bin/python
cachedir: .pytest_cache
rootdir: /home/foo/build/pykaldi, configfile: setup.cfg, testpaths: tests
collected 0 items / 15 errors                                                  

==================================== ERRORS ====================================
________________ ERROR collecting tests/base/kaldi-math-test.py ________________
ImportError while importing test module '/home/foo/build/pykaldi/tests/base/kaldi-math-test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/base/kaldi-math-test.py:1: in <module>
    from kaldi.base import math as kaldi_math
kaldi/__init__.py:14: in <module>
    from . import base
kaldi/base/__init__.py:1: in <module>
    from ._kaldi_error import *
E   ModuleNotFoundError: No module named 'kaldi.base._kaldi_error'
______________ ERROR collecting tests/chain/languge-model-test.py ______________
ImportError while importing test module '/home/foo/build/pykaldi/tests/chain/languge-model-test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/chain/languge-model-test.py:4: in <module>
    from kaldi.base import math as kaldi_math
kaldi/__init__.py:14: in <module>
    from . import base
kaldi/base/__init__.py:1: in <module>
    from ._kaldi_error import *
E   ModuleNotFoundError: No module named 'kaldi.base._kaldi_error'
_____________ ERROR collecting tests/cudamatrix/cu-device-test.py ______________
ImportError while importing test module '/home/foo/build/pykaldi/tests/cudamatrix/cu-device-test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/cudamatrix/cu-device-test.py:4: in <module>
    from kaldi.base import math as kaldi_math
kaldi/__init__.py:14: in <module>
    from . import base
kaldi/base/__init__.py:1: in <module>
    from ._kaldi_error import *
E   ModuleNotFoundError: No module named 'kaldi.base._kaldi_error'
_____________ ERROR collecting tests/cudamatrix/cu-matrix-test.py ______________
ImportError while importing test module '/home/foo/build/pykaldi/tests/cudamatrix/cu-matrix-test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/cudamatrix/cu-matrix-test.py:1: in <module>
    from kaldi.base import math as kaldi_math
kaldi/__init__.py:14: in <module>
    from . import base
kaldi/base/__init__.py:1: in <module>
    from ._kaldi_error import *
E   ModuleNotFoundError: No module named 'kaldi.base._kaldi_error'
_____________ ERROR collecting tests/cudamatrix/cu-vector-test.py ______________
ImportError while importing test module '/home/foo/build/pykaldi/tests/cudamatrix/cu-vector-test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/cudamatrix/cu-vector-test.py:5: in <module>
    from kaldi.base import math as kaldi_math
kaldi/__init__.py:14: in <module>
    from . import base
kaldi/base/__init__.py:1: in <module>
    from ._kaldi_error import *
E   ModuleNotFoundError: No module named 'kaldi.base._kaldi_error'
_________________ ERROR collecting tests/gmm/full-gmm-test.py __________________
ImportError while importing test module '/home/foo/build/pykaldi/tests/gmm/full-gmm-test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/gmm/full-gmm-test.py:7: in <module>
    from kaldi.base import math as kaldi_math
kaldi/__init__.py:14: in <module>
    from . import base
kaldi/base/__init__.py:1: in <module>
    from ._kaldi_error import *
E   ModuleNotFoundError: No module named 'kaldi.base._kaldi_error'
_______________ ERROR collecting tests/hmm/hmm-topology-test.py ________________
ImportError while importing test module '/home/foo/build/pykaldi/tests/hmm/hmm-topology-test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/hmm/hmm-topology-test.py:4: in <module>
    from kaldi.base.io import istringstream, ostringstream
kaldi/__init__.py:14: in <module>
    from . import base
kaldi/base/__init__.py:1: in <module>
    from ._kaldi_error import *
E   ModuleNotFoundError: No module named 'kaldi.base._kaldi_error'
_________________ ERROR collecting tests/matrix/matrix-test.py _________________
ImportError while importing test module '/home/foo/build/pykaldi/tests/matrix/matrix-test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/matrix/matrix-test.py:5: in <module>
    from kaldi.matrix import Matrix, SubMatrix, SubVector
kaldi/__init__.py:14: in <module>
    from . import base
kaldi/base/__init__.py:1: in <module>
    from ._kaldi_error import *
E   ModuleNotFoundError: No module named 'kaldi.base._kaldi_error'
_________________ ERROR collecting tests/matrix/vector-test.py _________________
ImportError while importing test module '/home/foo/build/pykaldi/tests/matrix/vector-test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/matrix/vector-test.py:4: in <module>
    from kaldi.matrix import Vector, SubVector
kaldi/__init__.py:14: in <module>
    from . import base
kaldi/base/__init__.py:1: in <module>
    from ._kaldi_error import *
E   ModuleNotFoundError: No module named 'kaldi.base._kaldi_error'
______________ ERROR collecting tests/nnet3/nnet-compute-test.py _______________
ImportError while importing test module '/home/foo/build/pykaldi/tests/nnet3/nnet-compute-test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/nnet3/nnet-compute-test.py:6: in <module>
    from kaldi.base.io import istringstream, ostringstream
kaldi/__init__.py:14: in <module>
    from . import base
kaldi/base/__init__.py:1: in <module>
    from ._kaldi_error import *
E   ModuleNotFoundError: No module named 'kaldi.base._kaldi_error'
_________________ ERROR collecting tests/util/kaldi-io-test.py _________________
ImportError while importing test module '/home/foo/build/pykaldi/tests/util/kaldi-io-test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/util/kaldi-io-test.py:6: in <module>
    from kaldi.util.io import *
kaldi/__init__.py:14: in <module>
    from . import base
kaldi/base/__init__.py:1: in <module>
    from ._kaldi_error import *
E   ModuleNotFoundError: No module named 'kaldi.base._kaldi_error'
_______________ ERROR collecting tests/util/kaldi-table-test.py ________________
ImportError while importing test module '/home/foo/build/pykaldi/tests/util/kaldi-table-test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/util/kaldi-table-test.py:1: in <module>
    from kaldi.util.table import *
kaldi/__init__.py:14: in <module>
    from . import base
kaldi/base/__init__.py:1: in <module>
    from ._kaldi_error import *
E   ModuleNotFoundError: No module named 'kaldi.base._kaldi_error'
____________________ ERROR collecting tests/util/mixins.py _____________________
ImportError while importing test module '/home/foo/build/pykaldi/tests/util/mixins.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/util/mixins.py:5: in <module>
    import kaldi.util
kaldi/__init__.py:14: in <module>
    from . import base
kaldi/base/__init__.py:1: in <module>
    from ._kaldi_error import *
E   ModuleNotFoundError: No module named 'kaldi.base._kaldi_error'
_________________ ERROR collecting tests/util/readers-test.py __________________
ImportError while importing test module '/home/foo/build/pykaldi/tests/util/readers-test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/util/readers-test.py:6: in <module>
    from kaldi.matrix import *
kaldi/__init__.py:14: in <module>
    from . import base
kaldi/base/__init__.py:1: in <module>
    from ._kaldi_error import *
E   ModuleNotFoundError: No module named 'kaldi.base._kaldi_error'
_________________ ERROR collecting tests/util/writers-test.py __________________
ImportError while importing test module '/home/foo/build/pykaldi/tests/util/writers-test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/util/writers-test.py:5: in <module>
    from kaldi.matrix import Vector, Matrix, SubMatrix, SubVector
kaldi/__init__.py:14: in <module>
    from . import base
kaldi/base/__init__.py:1: in <module>
    from ._kaldi_error import *
E   ModuleNotFoundError: No module named 'kaldi.base._kaldi_error'
=========================== short test summary info ============================
ERROR tests/base/kaldi-math-test.py
ERROR tests/chain/languge-model-test.py
ERROR tests/cudamatrix/cu-device-test.py
ERROR tests/cudamatrix/cu-matrix-test.py
ERROR tests/cudamatrix/cu-vector-test.py
ERROR tests/gmm/full-gmm-test.py
ERROR tests/hmm/hmm-topology-test.py
ERROR tests/matrix/matrix-test.py
ERROR tests/matrix/vector-test.py
ERROR tests/nnet3/nnet-compute-test.py
ERROR tests/util/kaldi-io-test.py
ERROR tests/util/kaldi-table-test.py
ERROR tests/util/mixins.py
ERROR tests/util/readers-test.py
ERROR tests/util/writers-test.py
!!!!!!!!!!!!!!!!!!! Interrupted: 15 errors during collection !!!!!!!!!!!!!!!!!!!
============================== 15 errors in 0.19s ==============================`

The only thing I've changed is commenting out the version check in the clif installer. I am using Python 3.10.6.

**Comment by bmilde** [comment]
Not really sure what happened here. Our Github build pipeline (https://github.com/pykaldi/pykaldi/blob/master/.github/workflows/test.yml) runs through the tests without problems in Python 3.10 and Python 3.11. FYI there are also wheels for these Python versions now.
