### ISSUE TITLE
PyKaldi Installed successfully but can not be imported

### ISSUE THREAD

**Issue by RakefetW** [pykaldi/pykaldi#317]
Hello
I've successfully installed and checked Kaldi on my Ubuntu pc.
Then, I followed PyKaldi instructions for installation with wheel files inside a virtual env.
I also validated that KALDI_ROOT variable is defined properly.
PyKaldi install is reported to succeed. I can see PyKaldi on pip list of my virtual env.

However, I can NOT find PyKaldi directory inside 'site-packages' (inside the virtual env). 
Only Kaldi directory and pyKaldi_info directory.
When I run import pykaldi within the virtual env it fails.

what could be the problem?

**Comment by bmilde** [comment]
Try running one of examples. Note that the correct import is "kaldi" not "pykaldi"
