### ISSUE TITLE
In Protobuf installation, google test is not pulled.

### ISSUE THREAD

**Issue by alexraju91** [pykaldi/pykaldi#33]
Adding 
```
git submodule update --init --recursive
```
in protobuf directory does this.

**Comment by vrmpx** [comment]
Hello @alexforever86,

Thank you for your comment. I was just wondering how did you come across this? Did you find an issue when not including google test?

**Comment by alexforever86** [comment]
@vrmpx  Yup, I was shown an error message that there are no files in third-party/googletest. BTW I'm trying to build a debian based docker image.
