### ISSUE TITLE
An example of a recipe implemented with pykaldi

### ISSUE THREAD

**Issue by dmitriy-serdyuk** [pykaldi/pykaldi#36]
Is there a place where I can find some standard recipes (say, TIMIT s5) reimplemented in python using pykaldi?

**Comment by dogancan** [comment]
Hi Dmitriy

No, we don't have any kaldi recipes implemented in python using pykaldi and I don't think we will have a complete ASR training recipe implemented purely in python using pykaldi for a long time.

The main reason is there is no ASR training API in Kaldi C++ library. As you probably know, Kaldi ASR training happens at the shell level by orchestrating a large number of kaldi binaries and other scripts. Reimplementing such recipes is a lot of hard work. 

Beyond the difficulty of replicating kaldi recipes in python, we (pykaldi maintainers) don't intend to replicate the behavior of existing kaldi binaries (or recipes) unless there is a very good reason to do so. The reimplementation examples we currently provide in the repo are purely educational. Of course pykaldi users might still contribute code and recipes that replicate kaldi behavior and such contributions are very welcome. 

As it is pykaldi is great for implementing new kaldi compatible tools in python and working with kaldi classes/functions interactively in ipython. The goal of pykaldi project is to enable seamless interop with kaldi libraries in python. In that, it is not very different from the awesome kaldi-python repo you guys are maintaining but with a much larger scope. I have used kaldi-python on numerous occasions before implementing pykaldi and you will definitely notice the effect it had on the design of the [util.io](https://pykaldi.github.io/api/kaldi.util.html#module-kaldi.util.table) package.

**Comment by dmitriy-serdyuk** [comment]
Thank you for the clarification of the scope for this project!
