### ISSUE TITLE
Calling TrainingGraphCompiler(...) gives segmentation fault error

### ISSUE THREAD

**Issue by mollynatsu** [pykaldi/pykaldi#40]
Calling TrainingGraphCompiler(trans_model, ctx_dep, lex_fst, disambig_syms, opts) in kaldi.decoder gives a segmentation fault (core dump) error. 

My code is as simple as follow:
```
    # loading models
    model_in_filename = "final.mdl"
    decode_fst_filename = "HCLG.fst"
    tree_filename = "tree"
    lex_fst_filename = "L.fst"
    disambig_filename = "disambig.int"
    
    trans_model = TransitionModel()
    with xopen(model_in_filename) as ki:
        trans_model.read(ki.stream(), ki.binary)
    
    ctx_dep = ContextDependency()
    with xopen(tree_filename) as ki:
        ctx_dep.read(ki.stream(), ki.binary)
    
    lex_fst = StdVectorFst.read(lex_fst_filename)

    disambig_syms = []
    with open(disambig_filename) as f:
        for line in f.read().splitlines():
            disambig_syms.append(int(line))

    gopts = TrainingGraphCompilerOptions()
    gopts.transition_scale = 0.0
    gopts.self_loop_scale = 0.0

    # Initializing train graph compiler
    TrainingGraphCompiler(trans_model, ctx_dep, lex_fst, disambig_syms, gopts)
```

I didn't have a problem loading the parameters, and I have confirmed that it is this initialization function that is causing the error. Does anyone know why it happens and how to fix it?

**Comment by dogancan** [comment]
If you can provide a test script causing the segfault, I can look into what is happening. Please make sure you  include all the files necessary for running the script.

**Comment by dogancan** [comment]
I just tried initializing a graph compiler with existing model files and it seems to initialize without a segfault on my end. Did you by any chance rebuild the kaldi libraries pykaldi is linked against and not reinstall pykaldi afterwards?

**Comment by mollynatsu** [comment]
Hi dogancan, thanks for the reply. My script is the same as I mentioned in the initial thread, however, the model files are too large to upload. The complete script is as follow:

```
import kaldi
from kaldi.decoder import TrainingGraphCompiler, TrainingGraphCompilerOptions
from kaldi.fstext import StdVectorFst
from kaldi.hmm import TransitionModel
from kaldi.util.io import xopen
from kaldi.tree import ContextDependency
import os

if __name__ == '__main__':
    # loading models
    model_in_filename = "final.mdl"
    decode_fst_filename = "HCLG.fst"
    tree_filename = "tree"
    lex_fst_filename = "L.fst"
    disambig_filename = "disambig.int"

    trans_model = TransitionModel()
    with xopen(model_in_filename) as ki:
        trans_model.read(ki.stream(), ki.binary)

    ctx_dep = ContextDependency()
    with xopen(tree_filename) as ki:
        ctx_dep.read(ki.stream(), ki.binary)

    lex_fst = StdVectorFst.read(lex_fst_filename)

    disambig_syms = []
    with open(disambig_filename) as f:
        for line in f.read().splitlines():
            disambig_syms.append(int(line))

    gopts = TrainingGraphCompilerOptions()
    gopts.transition_scale = 0.0
    gopts.self_loop_scale = 0.0

    # initializing traning graph compiler
    gc = TrainingGraphCompiler(trans_model, ctx_dep, lex_fst, disambig_syms, gopts)
```

I can confirm that the model files work with the Kaldi command line tool "compile-train-graph", so I think they are not the cause of the problem.  I followed the instructions to install Pykaldi and did not recompile anything afterwards. I'll try to reinstall Pykaldi and see if the problem resolves.

**Comment by dogancan** [comment]
I was able to replicate the segfault. It is not about the initialization of graph compiler. 
Segfault happens when the interpreter is shutting down, i.e. during the deallocation of objects. I'll look into it.

**Comment by mollynatsu** [comment]
Ahh, that explains why I can use the graph compiler to compile graph and it still gives the segfault error afterwards. Thanks for looking into it!

**Comment by dogancan** [comment]
C++ TrainingGraphCompiler class was taking ownership of the lexicon FST and we were not handing over the ownership while initiating the compiler. I just pushed a fix. Let me know if you continue to have problems.

**Comment by mollynatsu** [comment]
Yeah, it's working! Thank you so much.

**Comment by dogancan** [comment]
You're welcome. Please do let us know of any issues you might have or any features you find missing. At this stage user feedback is very valuable for us not only to understand the pain points and but also to figure out where we should focus our development efforts.
