### ISSUE TITLE
ImportError: dynamic module does not define init function (PyInit__kaldi_error)

### ISSUE THREAD

**Issue by vishnuprasadb** [pykaldi/pykaldi#41]
Can someone help me in Resolving this error?

**Comment by dogancan** [comment]
If you provide more context as to how you got this error, e.g. a test script causing this error, I can look into it.

**Comment by vishnuprasadb** [comment]
Yeah ! That was the issue. I had "build" it using python 2 and ran with python 3.
Thanks a lot.!!
