### ISSUE TITLE
Installation taking up too much memory

### ISSUE THREAD

**Issue by Rushab1** [pykaldi/pykaldi#43]
The final installation step ```python setup.py install``` takes up too much memory, my system kind of hangs.

**Comment by dogancan** [comment]
Could you try the following and see if it helps?
```
MAKE_NUM_JOBS=2 python setup.py install
```
Adjust the number of jobs based on how much memory you can spare. For this to have an affect, you need to use Make for building, so make sure ninja is not installed in the active Python environment.

**Comment by dogancan** [comment]
I just pushed a change that enables setting the number of parallel jobs for ninja as well. Let me know if you are still having memory problems.

**Comment by drzraf** [comment]
Building dependency already hang 8 cores machines. You should rather not hardcode CPU number from /proc/cpuinfo (as done in install_clif.sh) and just pass additional options down to the underlying command.

Side note: the toolchain is horribly complex (compiling a custom version of clang+llvm in order to compile clif, and is likely the main showstopper)

**Comment by dogancan** [comment]
If you are not installing inside a virtual environment, CLIF installer tries to install everything globally under `/usr` directory.

**Comment by RobertLevenbach** [comment]
> Building dependencies hung my 8 cores machines.
> It would be better to not hardcode number of CPU (detected from /proc/cpuinfo in install_clif.sh) and just pass additional options from command line down to the underlying command.
> 
> Side note: the toolchain is horribly complex (compiling a custom version of clang+llvm in order to compile clif, and is likely the main showstopper)
> Personally, I get a:
> 
> ```
> [489/490] Install the project...
> -- Install configuration: "Release"
> CMake Error at tools/lto/cmake_install.cmake:41 (file):
>   file cannot create directory: /usr/clang/lib.  Maybe need administrative
>   privileges.
> Call Stack (most recent call first):
>   tools/cmake_install.cmake:42 (include)
>   cmake_install.cmake:55 (include)
> FAILED: CMakeFiles/install.util 
> cd ////tools/clif_backend/build_matcher && /usr/bin/cmake -P cmake_install.cmake
> ninja: build stopped: subcommand failed.
> ```
> 
> (I'm not expecting the need to go root...)

Hi, did you find a solution to this?

**Comment by BilalDendani** [comment]
> > Building dependencies hung my 8 cores machines.
> > It would be better to not hardcode number of CPU (detected from /proc/cpuinfo in install_clif.sh) and just pass additional options from command line down to the underlying command.
> > Side note: the toolchain is horribly complex (compiling a custom version of clang+llvm in order to compile clif, and is likely the main showstopper)
> > Personally, I get a:
> > ```
> > [489/490] Install the project...
> > -- Install configuration: "Release"
> > CMake Error at tools/lto/cmake_install.cmake:41 (file):
> >   file cannot create directory: /usr/clang/lib.  Maybe need administrative
> >   privileges.
> > Call Stack (most recent call first):
> >   tools/cmake_install.cmake:42 (include)
> >   cmake_install.cmake:55 (include)
> > FAILED: CMakeFiles/install.util 
> > cd ////tools/clif_backend/build_matcher && /usr/bin/cmake -P cmake_install.cmake
> > ninja: build stopped: subcommand failed.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (I'm not expecting the need to go root...)
> 
> Hi, did you find a solution to this?

Hi, I am facing the same problem. 
Did you find any solution?
