### ISSUE TITLE
No such file or directory: 'kaldi/__version__.py'

### ISSUE THREAD

**Issue by YihengJiang** [pykaldi/pykaldi#44]
when i run "python setup.py install",it excepts this error.
I m sure that I have install all of c++ library before execute this command.
and I have run"find" and "locate" to find __version__.py,but it has no result.
Please give me some advise,and what should I do now???

List the error traceBack as follow:

  Traceback (most recent call last):
    File "setup.py", line 309, in <module>
      with open(os.path.join('kaldi', '__version__.py')) as f:
  FileNotFoundError: [Errno 2] No such file or directory: 'kaldi/__version__.py'

**Comment by dogancan** [comment]
There should be a [`__version__.py`](https://github.com/pykaldi/pykaldi/blob/master/kaldi/__version__.py) file inside [`pykaldi/kaldi`](https://github.com/pykaldi/pykaldi/tree/master/kaldi) directory. This file is part of pykaldi source code so it should be there when you clone the repository.

The command `python setup.py install` should be run inside the `pykaldi` root directory. Did you by any chance run it in another directory?

**Comment by YihengJiang** [comment]
I have re-install kaldi in pykaldi/tools directory,but it seems not make sense.I found that my machine does
not generate kaldi directory in pykaldi directory,it just generate in pykaldi/tools.but in other machine,it will generate to both these two directory.what is wrong？thank you

**Comment by dogancan** [comment]
`pykaldi/kaldi` directory is different from `pykaldi/tools/kaldi`. The first one contains pykaldi source code and it should be there when you clone the pykaldi repository. The second one contains kaldi source code and is automatically generated if you run `install_kaldi.sh` inside the `pykaldi/tools` directory. You need both directories.

**Comment by dogancan** [comment]
I am not sure if there is anything to do on our end about this issue. Feel free to reopen the issue if you are continuing to have this problem after a fresh clone of the repository.
