### ISSUE TITLE
Use cmake3 for installation on CentOS

### ISSUE THREAD

**Issue by itsmesatwik** [pykaldi/pykaldi#46]
CentOS package manager (yum) mirrors by default have cmake2.6 and use `cmake3` for cmake ver >=3.0. Hence it would be useful to include a script that takes care of that, shouldn't be a problem, just replace `cmake` with `cmake3` in the installation script for clif.

**Comment by dogancan** [comment]
Thanks for the heads up. Apart from this change, do the current installation scripts and instructions work out of the box on CentOS? If that is the case, that's awesome :)

**Comment by itsmesatwik** [comment]
@dogancan I tried installation after linking cmake3 to cmake. For some reason the script fails due to not being able to import `google.protobuf` which I am unable to identify the reason for, even though the installation for protobuf goes without a hitch.

**Comment by dogancan** [comment]
Which script are you referring to?

**Comment by dogancan** [comment]
It would be really cool if you can put together a set of installation scripts for CentOS once we figure out the problems.

> For some reason the script fails due to not being able to import google.protobuf which I am unable to identify the reason for

Which script is this?

> the clif script is unable to recognize the installation of ninja

Does it print "Using make.  Build will take a long time.  Consider installing ninja." ? what do you get when you do `which ninja`?

**Comment by itsmesatwik** [comment]
Sure, I would love to contribute to this project, I'm actually working on it at NCSA right now to create a cloud based captioning system for our Clowder Api.
`install_clif.sh` is the one that fails, even though `install_protobuf.sh` runs perfectly giving the expected `Done installing Protobuf` output.
`which ninja` shows `/env/bin/ninja` as expected

**Comment by dogancan** [comment]
What happens if you try to import google.protobuf module in a python session?

**Comment by itsmesatwik** [comment]
When I try to import the module in a python session it gives me no error.
Ninja is installed on the env, however the script is for some reason looking for it elsewhere (see attached picture), instead of /env/bin/ninja.
![screen shot 2018-07-13 at 6 05 52 pm](https://user-images.githubusercontent.com/30192501/42717660-32ce9832-86c8-11e8-8ee8-40c420c3b901.png)

**Comment by dogancan** [comment]
Looks like something is wrong with the python environment. 

Where is the environment installed on your computer? At the system root as the path  `/env/bin/ninja` suggests? 

Can you call the `ninja` binary after activating the environment?

**Comment by itsmesatwik** [comment]
The env is inside pykaldi directory which is inside a repository that I have on an ssh.
~/work/repo/pykaldi/env
Hmm, you're right, When I try it without sudo it gives me an error that "python library libpython3.4m.a could not be found".

**Comment by dogancan** [comment]
I think sudo is messing up your path and that's why the script cannot find the packages and binaries. Make sure you run all install scripts without sudo so everything is installed locally.

**Comment by itsmesatwik** [comment]
I can't call ninja, even though it is already installed.

**Comment by dogancan** [comment]
did you use sudo when  installing ninja?

**Comment by itsmesatwik** [comment]
I did not

**Comment by itsmesatwik** [comment]
I only used sudo (I believe) when I was unable to run ./install_clif.sh

**Comment by dogancan** [comment]
I don't think I quite follow. What do you get when you do `which ninja`?

**Comment by itsmesatwik** [comment]
~/work/repo/pykaldi/env/bin/ninja

**Comment by dogancan** [comment]
So what happens if you do say `ninja --help`?

**Comment by itsmesatwik** [comment]
It works

**Comment by dogancan** [comment]
Ok, I think the clif install script will pick ninja up if you call it without sudo.

> python library libpython3.4m.a could not be found

The clif install script may not be able to find the python library if it has an unusual extension on your platform. You can call it as follows if to override the paths manually

```
./install_clif.sh [PYTHON_EXECUTABLE_PATH] [PYTHON_LIBRARY_PATH]
```

Make sure you set the correct paths though. They should point to the binary and library associated with the virtual environment.

**Comment by itsmesatwik** [comment]
I am doing everything again without sudo, will let you know if I hit a roadblock.

**Comment by itsmesatwik** [comment]
First problem, while running install_clif.sh, the build stops due to not being able to import google.protobuf. Any possible fixes for this, since I followed the installation so far.

**Comment by dogancan** [comment]
I asked this before but just making sure it is not an environment problem. Could you check again if you can import that module from within the virtual python environment ?

**Comment by itsmesatwik** [comment]
<img width="524" alt="screen shot 2018-07-17 at 2 55 41 pm" src="https://user-images.githubusercontent.com/30192501/42842013-8ad89c24-89d1-11e8-9106-e1a82a970c1f.png">
Yep, I don't have problems importing it when I do it in python

**Comment by dogancan** [comment]
You are running `install_clif.sh` without any arguments, right?

**Comment by itsmesatwik** [comment]
No, I am running it with arguments pointing to env python

**Comment by dogancan** [comment]
Can you copy and paste the exact command line you are using to call `install_clif.sh` and the exact error message you are getting?

**Comment by dogancan** [comment]
Hey @itsmesatwik, did you make any progress on this?

**Comment by itsmesatwik** [comment]
Hey, @dogancan , sorry I couldn't reply, for the past I have been working on something else that was urgent. I tried to run the script with the paths to the env python but it doesn't work for some reason, could you tell me the path to the executable and library in the virtual env.

**Comment by dogancan** [comment]
My guess is [this script](https://github.com/pykaldi/pykaldi/blob/master/tools/find_python_library.py) is failing to find the python library. We haven't tested it on CentOS so this is not surprising. The path of the executable should be the output of`which python`. You can try the following to figure out the path of the library.
```
ldd `which python` | grep python
```

**Comment by dogancan** [comment]
Hey @itsmesatwik, I am closing this issue but feel free to reopen if you need additional help.
