### ISSUE TITLE
The compatibility of pykaldi and kaldi5.1 issues

### ISSUE THREAD

**Issue by Diamondyelo** [pykaldi/pykaldi#49]
Calculating GOP requires kaldi5.1 and the mfcc calculated by kaldi 5.1 and the latest version of kaldi
 is different. So i must use kaldi 5.1 to calculate mfcc. I have tried two method:

(1)Replace the whole tools/kaldi with kaldi5.1. 
(2)Only replace tools/kaldi/src/featbins/compute-mfcc-feats with compute-mfcc-feats in kaldi5.1.

But neither of these methods works. Is there any way to make pykaldi compatible with kaldi5.1, I only need the the module of calculating mfcc. 

Thank you for help!

**Comment by dogancan** [comment]
Unfortunately there is no way of making PyKaldi compatible with Kaldi 5.1. 

I am surprised that MFCC features computed with the current Kaldi is substantially different from the ones computed with Kaldi 5.1. Are you sure this is the case? Did you ask about this on kaldi-help? I mean there might be small inconsequential differences between the two versions but such differences shouldn't have a significant effect on GOP calculation. By the way, if you all you need is to compute MFCC features, why don't you use compute-mfcc-feats executable directly?

**Comment by Diamondyelo** [comment]
The results of the MFCC in these two versions have large errors. To my surprise, the relative error of the results I calculated using the same scripts and parameters reached a staggering 30 percent!

Maybe I need to find other solutions.

Finally, thanks for your help and advice.

**Comment by dogancan** [comment]
I am closing this issue but feel free to reopen if you think there is anything we can do to help.
