### ISSUE TITLE
fatal error: unicode/ucnv.h: No such file or directory

### ISSUE THREAD

**Issue by Vernboy** [pykaldi/pykaldi#50]
Getting the following error when running the install_clif script.

(sfr_env) paperspace@ps3mpwqc8:~/SFR/start_follow_read/pykaldi/tools$ ./install_clif.sh
Destination /home/paperspace/SFR/start_follow_read/pykaldi/tools/clif already exists.
Already up-to-date.
/home/paperspace/anaconda3/envs/sfr_env/bin/ninja
Using ninja for the clif backend build.
Checked out revision 307315.
Checked out revision 307315.
-- Native target architecture is X86
-- Threads enabled.
-- Doxygen disabled.
-- Go bindings disabled.
-- Could NOT find OCaml (missing:  OCAMLFIND OCAML_VERSION OCAML_STDLIB_PATH) 
-- Could NOT find OCaml (missing:  OCAMLFIND OCAML_VERSION OCAML_STDLIB_PATH) 
-- OCaml bindings disabled.
-- LLVM host triple: x86_64-unknown-linux-gnu
-- LLVM default target triple: x86_64-unknown-linux-gnu
-- Building with -fPIC
-- Constructing LLVMBuild project information
-- Targeting X86
-- Could NOT find Z3 (missing:  Z3_LIBRARIES Z3_INCLUDE_DIR) (Required is at least version "4.5")
-- Clang version: 5.0.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/paperspace/SFR/start_follow_read/pykaldi/tools/clif_backend/build_matcher
[1/11] Generating SVNVersion.inc
-- Found Subversion: /usr/bin/svn (found version "1.9.3") 
[1/184] Building C object tools/clang/tools/c-index-test/CMakeFiles/c-index-test.dir/c-index-test.c.o
FAILED: tools/clang/tools/c-index-test/CMakeFiles/c-index-test.dir/c-index-test.c.o 
/usr/bin/cc  -DCLANG_ENABLE_ARCMT -DCLANG_ENABLE_OBJC_REWRITER -DCLANG_ENABLE_STATIC_ANALYZER -DGTEST_HAS_RTTI=0 -DLLVM_BUILD_GLOBAL_ISEL -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/clang/tools/c-index-test -I/home/paperspace/SFR/start_follow_read/pykaldi/tools/clif_backend/llvm/tools/clang/tools/c-index-test -I/home/paperspace/SFR/start_follow_read/pykaldi/tools/clif_backend/llvm/tools/clang/include -Itools/clang/include -Iinclude -I/home/paperspace/SFR/start_follow_read/pykaldi/tools/clif_backend/llvm/include -isystem /home/paperspace/anaconda3/include/libxml2 -fPIC -Werror=date-time -Wall -W -Wno-unused-parameter -Wwrite-strings -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-comment -ffunction-sections -fdata-sections -O3 -DNDEBUG   -std=gnu89 -MMD -MT tools/clang/tools/c-index-test/CMakeFiles/c-index-test.dir/c-index-test.c.o -MF tools/clang/tools/c-index-test/CMakeFiles/c-index-test.dir/c-index-test.c.o.d -o tools/clang/tools/c-index-test/CMakeFiles/c-index-test.dir/c-index-test.c.o   -c /home/paperspace/SFR/start_follow_read/pykaldi/tools/clif_backend/llvm/tools/clang/tools/c-index-test/c-index-test.c
In file included from /home/paperspace/anaconda3/include/libxml2/libxml/parser.h:810:0,
                 from /home/paperspace/SFR/start_follow_read/pykaldi/tools/clif_backend/llvm/tools/clang/tools/c-index-test/c-index-test.c:15:
/home/paperspace/anaconda3/include/libxml2/libxml/encoding.h:31:26: fatal error: unicode/ucnv.h: No such file or directory
compilation terminated.
[2/184] Linking CXX executable bin/verify-uselistorder
ninja: build stopped: subcommand failed.

**Comment by vrmpx** [comment]
Hello @Vernboy,

It seems that your anaconda installation is missing `<ANACONDA_ROOT>/include/unicode/ucnv.h`.

Could you tell us a bit more on your setup (e.g., OS, python version)?

**Comment by Vernboy** [comment]
I'm on a paperspace VM and uname -a gives me:
Linux 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

launching python gives me Python 2.7.13

**Comment by vrmpx** [comment]
I think I found a workaround by manually installing the icu package: 

```
conda install icu
```

After installing this package there should be a directory called `unicode` inside your anaconda root directory. This will have the `ucnv.h` file that is missing.

Please let me know if this works,

**Comment by Vernboy** [comment]
(sfr_env) paperspace@ps3mpwqc8:~/SFR/start_follow_read/pykaldi/tools$ conda install icu
Fetching package metadata ...........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /home/paperspace/anaconda3/envs/sfr_env:
#
icu                       58.2                 h9c2bf20_1  
(sfr_env) paperspace@ps3mpwqc8:~/SFR/start_follow_read/pykaldi/tools$ ./install_clif.sh
Destination /home/paperspace/SFR/start_follow_read/pykaldi/tools/clif already exists.
Already up-to-date.
/home/paperspace/anaconda3/envs/sfr_env/bin/ninja
Using ninja for the clif backend build.
Checked out revision 307315.
Checked out revision 307315.
-- Native target architecture is X86
-- Threads enabled.
-- Doxygen disabled.
-- Go bindings disabled.
-- Could NOT find OCaml (missing:  OCAMLFIND OCAML_VERSION OCAML_STDLIB_PATH) 
-- Could NOT find OCaml (missing:  OCAMLFIND OCAML_VERSION OCAML_STDLIB_PATH) 
-- OCaml bindings disabled.
-- LLVM host triple: x86_64-unknown-linux-gnu
-- LLVM default target triple: x86_64-unknown-linux-gnu
-- Building with -fPIC
-- Constructing LLVMBuild project information
-- Targeting X86
-- Could NOT find Z3 (missing:  Z3_LIBRARIES Z3_INCLUDE_DIR) (Required is at least version "4.5")
-- Clang version: 5.0.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/paperspace/SFR/start_follow_read/pykaldi/tools/clif_backend/build_matcher
[1/11] Generating SVNVersion.inc
-- Found Subversion: /usr/bin/svn (found version "1.9.3") 
[4/183] Building C object tools/clang/tools/c-index-test/CMakeFiles/c-index-test.dir/c-index-test.c.o
FAILED: tools/clang/tools/c-index-test/CMakeFiles/c-index-test.dir/c-index-test.c.o 
/usr/bin/cc  -DCLANG_ENABLE_ARCMT -DCLANG_ENABLE_OBJC_REWRITER -DCLANG_ENABLE_STATIC_ANALYZER -DGTEST_HAS_RTTI=0 -DLLVM_BUILD_GLOBAL_ISEL -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/clang/tools/c-index-test -I/home/paperspace/SFR/start_follow_read/pykaldi/tools/clif_backend/llvm/tools/clang/tools/c-index-test -I/home/paperspace/SFR/start_follow_read/pykaldi/tools/clif_backend/llvm/tools/clang/include -Itools/clang/include -Iinclude -I/home/paperspace/SFR/start_follow_read/pykaldi/tools/clif_backend/llvm/include -isystem /home/paperspace/anaconda3/include/libxml2 -fPIC -Werror=date-time -Wall -W -Wno-unused-parameter -Wwrite-strings -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-comment -ffunction-sections -fdata-sections -O3 -DNDEBUG   -std=gnu89 -MMD -MT tools/clang/tools/c-index-test/CMakeFiles/c-index-test.dir/c-index-test.c.o -MF tools/clang/tools/c-index-test/CMakeFiles/c-index-test.dir/c-index-test.c.o.d -o tools/clang/tools/c-index-test/CMakeFiles/c-index-test.dir/c-index-test.c.o   -c /home/paperspace/SFR/start_follow_read/pykaldi/tools/clif_backend/llvm/tools/clang/tools/c-index-test/c-index-test.c
In file included from /home/paperspace/anaconda3/include/libxml2/libxml/parser.h:810:0,
                 from /home/paperspace/SFR/start_follow_read/pykaldi/tools/clif_backend/llvm/tools/clang/tools/c-index-test/c-index-test.c:15:
/home/paperspace/anaconda3/include/libxml2/libxml/encoding.h:31:26: fatal error: unicode/ucnv.h: No such file or directory
compilation terminated.
[5/183] Building CXX object tools/llvm-pdbutil/CMakeFiles/llvm-pdbutil.dir/PrettyVariableDumper.cpp.o
ninja: build stopped: subcommand failed.

**Comment by Vernboy** [comment]
It seems like the requested package was already installed and I got the same error after trying to install it

**Comment by vrmpx** [comment]
Yes. You already have the package installed in your SFR environment. 

Couple of ideas,

1. Just to be absolutely certain, there is a `ucnv.h` inside 
`/home/paperspace/anaconda3/include/unicode/` right?

2. In the compilation, you have ` -isystem /home/paperspace/anaconda3/include/libxml2`. I think this should be `-isystem /home/paperspace/anaconda3/include/`, since that is where we want to look for the unicode/ucnv.h.

**Comment by Vernboy** [comment]
yeah, the ucnv.h is there in that folder.  I'm not sure how to change the lookup location though... sorry to be so dense

**Comment by vrmpx** [comment]
Yeah, it looks like either llvm or clif scripts are not picking up the correct location.

Before we continue, make sure to delete 
`/home/paperspace/SFR/start_follow_read/pykaldi/tools/clif_backend` 
to delete the cached build config.

Maybe `CPATH=/home/paperspace/anaconda3/include/:$CPATH ./install_clif.sh` works?

**Comment by vrmpx** [comment]
I am glad it worked :) 
I'll close this issue, but if anything else comes up be sure to let us know.
