### ISSUE TITLE
How to get the value of gmm parameters?

### ISSUE THREAD

**Issue by kresle** [pykaldi/pykaldi#58]
The `get_means()`, `get_vars()` and `weights_` for GMM classes return `_kaldi_matrix.Matrix` and `_kaldi_vector.Vector` instances rather than Matrix or Vector instances. These instances don't support `numpy()` conversion. I looked through all their member value and functions, but couldn't figure how to get their values into numpy array or print to screen.
Can anyone help me with this problem? Thanks~

**Comment by dogancan** [comment]
Thanks for the report. I remember fixing these methods some time back but it seems I fixed them only for the `FullGmm` class. I'll try to fix them for other Gmm types later today -- no promises though. If you have installed pykaldi from source, you should be able to update your installation once the fix is up. If you have installed using conda, you will have to wait until we update the conda package which might take a day or so.

**Comment by dogancan** [comment]
I just pushed a fix. Feel free to reopen this issue if you continue to have this problem.

**Comment by dogancan** [comment]
It seems like the second file does not exist on that path or it is not readable. Can you check if it is indeed there? If it is there, could you copy and paste the output of “ls -l full_ubm”?

**Comment by kresle** [comment]
@dogancan It works now. Maybe I typed in some error, but the error occured when calling `gmm.read(ki.stream(), ki.binary)` instead of xopen. Anyway, thanks for your time!

**Comment by dogancan** [comment]
You’re welcome.

**Comment by jvel07** [comment]
> @dogancan Thanks a lot!
> I just compiled and these methods work perfectly now for both of DiagGmm and FullGmm.
> But I have another problem with FullGmm when reading data.
> `ki = xopen('diag_ubm/final.dubm',mode='rb')` for DiagGmm ubm works fine but `ki = xopen('full_ubm/final.dubm',mode='rb')` for FullGmm ubm gives `IOError: Could not open stream for reading.`
> Can you give me some advice?

Hi, @kresle. Please, would you mind sharing what was the exact way/solution you used to getting the gmm parameters from the already existing ubm models?
