### ISSUE TITLE
A bug with compute_deltas

### ISSUE THREAD

**Issue by Entonytang** [pykaldi/pykaldi#59]
the output of compute_deltas  is a class of _kaldi_matrix.Matrix
AttributeError: '_kaldi_matrix.Matrix' object has no attribute 'numpy'.

**Comment by dogancan** [comment]
Feel free to reopen this issue if you continue to have problems.

**Comment by dogancan** [comment]
Note that to see the changes, you will have to build from source until conda packages are updated.

CC @vrmpx.
