### ISSUE TITLE
Phoneme Aligner example

### ISSUE THREAD

**Issue by hadware** [pykaldi/pykaldi#60]
Considering other (closed) issues that seemed to be making similar requests (that were denied), I'm guessing I'm not sure this is a legitimate request, but I'll regret not asking since I really need this.

Would you guys be able to help me write (or even better, write yourself :stuck_out_tongue: ) an example file for phoneme forced alignment with PyKaldi?

**Comment by dogancan** [comment]
Hey @hadware. We can definitely help you write one by making sure classes/functions you need are available and fixing any PyKaldi bugs or limitations you might come across, but we won't be writing one for you. Let us know what you need and we will see what we can do.

**Comment by hadware** [comment]
Alright, thanks a lot. We'll first see how to do that cleanly in pure Kaldi first and then see what we might need. I'll keep you posted in this issue if we need stuff. Thanks a lot for your help, I really appreciate it :grinning:

PS: tagging @rachine

**Comment by dogancan** [comment]
I have thought a bit more about this and I think it would make sense to add a high level alignment module to pykaldi -- something similar to the high level asr module kaldi/asr.py. We can have it at the top level, e.g. kaldi/alignment.py. If you guys are interested in working on it, I think we can help with the design and implementation. I'll also look into what is needed for such a module. We can use this issue to discuss -- a WIP pull request would be even better once we have some code to share.

I think it would be great if we have a single aligner class that can accept alternative input representations (word string, phoneme string, list of integers, etc.) and produce both word and phoneme level alignments. Let us know what you guys think would be the ideal interface for the aligner  and we can go from there.

**Comment by dogancan** [comment]
Great! I looked at the `kaldi.asr` module to see if we can do something similar for alignment. It seemed like the `Recognizer.__init__` method is not really noob friendly. I made some changes to the `kaldi.asr` module over the weekend and added new high-level classes that are easier to instantiate from model files. These changes are not ready to be merged yet but they will soon be. I'll drop a comment here once they are up. FYI

**Comment by dogancan** [comment]
I just updated the `kaldi.asr` module. It doesn't yet have the high-level neural network based recognizers, but the GMM based recognizers should give good idea of the API aligners should provide.

**Comment by hadware** [comment]
Fantastic, I'll take a look!

**Comment by dogancan** [comment]
I just updated the asr module and added a new alignment module. There are also new example scripts demonstrating how to use the new recognizers/aligners. Note that you will have to upgrade kaldi, i.e. run `git pull` inside `pykaldi/tools/kaldi`, before rebuilding pykaldi from source. Let me know what you guys think of the API.

**Comment by hadware** [comment]
This is awesome! Thanks a lot! I'll take a look at both.

**Comment by hadware** [comment]
Well, tbh we're currently diving into how ASR and alignment work to have a better understand of each part of kaldi and your code (both functionally and theoretically). We're also both having some other tasks that need some immediate work, so we'll probably be more active in 1-2 weeks (of after christmas).

Sorry for this intermission, but we're still both very much interested by your work (and if we have a good enough comprehension of it, I'd definitely like to help).

**Comment by dogancan** [comment]
I'm closing this issue since there hasn't been any activity for a couple of months and I don't know if there is anything left to do on our end. Feel free to reopen though.
