### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by cici20052016** [pykaldi/pykaldi#65]
Traceback (most recent call last):
  File "setup.py", line 44, in <module>
    PYCLIF = check_output(['which', 'pyclif'])
  File "setup.py", line 19, in check_output
    return subprocess.check_output(*args, **kwargs).decode("utf-8").strip()
  File "/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/anaconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['which', 'pyclif']' returned non-zero exit status 1.

**Comment by dogancan** [comment]
Can you tell us exactly what commands you ran before `python setup.py install` ?

**Comment by cici20052016** [comment]
`git clone https://github.com/pykaldi/pykaldi.git`
`cd pykaldi`
`python setup.py install`

**Comment by dogancan** [comment]
Well, then you did not read the install instructions in the README :)

**Comment by dogancan** [comment]
To install pykaldi from source, you need to install its dependencies first. I suggest you install the binary package via conda unless you need to install from source.

**Comment by dogancan** [comment]
I am closing this but feel free to reopen it if you continue having install problems.
