### ISSUE TITLE
setup.py install fail

### ISSUE THREAD

**Issue by bar13290** [pykaldi/pykaldi#67]
while I am trying to run the setup.py install script (on python 3.6, ubuntu 18.04), I  got this error:

_Traceback (most recent call last):
  File "setup.py", line 44, in <module>
    PYCLIF = check_output(['which', 'pyclif'])
  File "setup.py", line 19, in check_output
    return subprocess.check_output(*args, **kwargs).decode("utf-8").strip()
  File "/home/madarb/anaconda3/envs/SPEAKER/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/madarb/anaconda3/envs/SPEAKER/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['which', 'pyclif']' returned non-zero exit status 1._

The protobuf, clif and kaldi installed successfully.

I would like to get some help with this error, thanks!

**Comment by dogancan** [comment]
Did you by any chance install pyclif package in a different python environment? This exception is happening because pyclif executable  is not on your PATH. If clif has been installed successfully, that is the only explanation that I can think of.

**Comment by bar13290** [comment]
Thanks, you are right. The pyclif was installed on different env.
I installed it again , and it works.
