### ISSUE TITLE
Rescoring output with grammar

### ISSUE THREAD

**Issue by DinoTheDinosaur** [pykaldi/pykaldi#69]
Current Kaldi source code includes a binary `lattice-lmrescore` which enables to run the recognition with the original HCLG.fst, and then re-align the results of recognition according to new grammar G.fst.
Does your package have some similar functionalities, and if not, what could be the possible solution using your package?

I'm aware that it's not an issue, but I don't know any other places to pose the question :)

**Comment by dogancan** [comment]
I just added a new class for lattice LM rescoring. Check out the example usage in [nnet3-recognizer.py](https://github.com/pykaldi/pykaldi/blob/master/examples/asr/nnet3-recognizer.py).

**Comment by DinoTheDinosaur** [comment]
Thank you! Looks very cool.
May I also ask, what is the the `G.rescore.fst` file I also have to provide?

**Comment by DinoTheDinosaur** [comment]
Or `G.fst` is the original grammar, and `G.rescore.fst` - new?

**Comment by dogancan** [comment]
Yes, you need to provide both the original grammar G.fst and the new grammar G.rescore.fst.

**Comment by DinoTheDinosaur** [comment]
Though, I can't seem to use the class outside project directory. Please check the installation procedure!

**Comment by DinoTheDinosaur** [comment]
I built the package from source and installed it, the class can be imported when I run scripts in the cloned directory, but I cannot import the class outside of it (using the installed version of the package)

**Comment by dogancan** [comment]
What happens when you open a python interpreter (while outside pykaldi directory) and try to import the class as follows?

```
from kaldi.asr import LatticeLmRescorer
```

**Comment by DinoTheDinosaur** [comment]
>>> from kaldi.asr import LatticeLmRescorer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'LatticeLmRescorer'

**Comment by dogancan** [comment]
I think I know why that happened. I just pushed a fix. Can you pull the latest change, reinstall from source and check if it works now?

**Comment by DinoTheDinosaur** [comment]
Yeah, it works now, thank you!
