### ISSUE TITLE
NnetSAD and NnetLatticeFasterOnlineRecognizer changes MFCC computation

### ISSUE THREAD

**Issue by ldeseynes** [pykaldi/pykaldi#70]
Hi @dogancan !
I am computing MFCC features using `kaldi.feat.mfcc.compute_feature` method to perform speech activity detection on a wav test file.

I first realized that creating a SAD object through `kaldi.segmentation.NnetSAD` before computing MFCC changed the output of `kaldi.feat.mfcc.compute_feature` even if I am not using this object during the computation. Second I also noticed the same behavior when calling first `kaldi.asr.NnetLatticeOnlineRecognizer`.

Here is my code:

```
#!/usr/bin/env python3.6

from __future__ import print_function

from kaldi.matrix import Vector
from kaldi.feat.mfcc import Mfcc, MfccOptions
from kaldi.util.options import ParseOptions

import os
import codecs
import wave
import struct

from kaldi.asr import NnetLatticeFasterOnlineRecognizer
from kaldi.segmentation import NnetSAD

# Construct recognizer
asr = NnetLatticeFasterOnlineRecognizer.from_files(
 	"decode/final.mdl", "decode/HCLG.fst", "decode/words.txt")


# Construct SAD
model = NnetSAD.read_model("SAD/exp/segmentation_1a/tdnn_stats_asr_sad_1a/final.raw")
post = NnetSAD.read_average_posteriors("SAD/exp/segmentation_1a/tdnn_stats_asr_sad_1a/post_output.vec")
transform = NnetSAD.make_sad_transform(post)
graph = NnetSAD.make_sad_graph()
sad = NnetSAD(model, transform, graph)


# MFCC config
mfcc_usage = """Extract MFCC features.
		   Usage:  example.py [opts...] <rspec> <wspec>
		"""

po_mfcc = ParseOptions(mfcc_usage)
po_mfcc.register_float("min-duration", 0.0,
				  "minimum segment duration")
mfcc_opts = MfccOptions()
mfcc_opts.frame_opts.samp_freq = 16000
mfcc_opts.use_energy = False
mfcc_opts.num_ceps = 40
mfcc_opts.mel_opts.num_bins = 40
mfcc_opts.mel_opts.high_freq = -400
mfcc_opts.mel_opts.low_freq = 20

mfcc_opts.register(po_mfcc)

mfcc = Mfcc(mfcc_opts)
sf = mfcc_opts.frame_opts.samp_freq



wf = wave.open('SAD/audio/test.short.wav','rb')
input_frames = wf.getnframes()
chunk = 1600
num_frames = 0
mfcc_pykaldi_file = codecs.open('mfcc_pykaldi.txt', 'w', encoding = 'utf-8')

# MFCC computation
while num_frames < input_frames:
	if (num_frames + chunk) < input_frames:
		nframes = chunk
	else:
		nframes = input_frames - num_frames

	data = wf.readframes(nframes)
	data_struct = struct.unpack_from('<%dh' % 1600, data)
	
	num_frames += nframes
	data_vec = Vector(data_struct)
	f = mfcc.compute_features(data_vec, sf, 1.0)
	for i in range(len(f)):
		mfcc_pykaldi_file.write(str(f[i]))

```

As you can see, the **asr** and **sad** objects should be useless but if you comment 

`asr = NnetLatticeFasterOnlineRecognizer.from_files(
 	"decode/final.mdl", "decode/HCLG.fst", "decode/words.txt")` 

or

`sad = NnetSAD(model, transform, graph)`

or both of them, you'll end up with different MFCC vectors.

In the table below are three MFCC vectors (40-dim) corresponding to the three cases above, computed on the first 25ms of my test file.

No asr & no sad | asr | sad
------------ | ------------- | -------------
68.1835 |  68.1532 |  68.1784
-20.2310 | -19.8629 | -20.0390
-16.3968 | -16.7663 | -16.6460
 -8.0430 |  -7.7936 |  -7.8147
-21.9416 | -20.9534 | -21.1954
  5.0883 |   3.9446 |   3.9356
 -4.5188 |  -3.4223 |  -4.6011
  7.2100 |   6.8197 |   8.3315
 26.5404 |  24.0173 |  24.6763
 14.2824 |  16.6121 |  16.5472
 -6.4256 |  -8.7899 |  -9.3176
-18.3546 | -18.5420 | -18.3494
  4.1023 |   2.2490 |   2.4281
 31.9681 |  33.4585 |  35.2552
 17.3717 |  14.2230 |  12.8806
-25.9906 | -23.7150 | -23.2355
  4.7358 |   3.2480 |   2.9003
  9.3317 |   9.9033 |  11.1418
 -4.1933 |  -4.5594 |  -5.8049
 -3.6752 |  -3.0705 |  -2.1171
  1.2225 |   1.0135 |   0.6585
 -0.3392 |  -0.5516 |  -0.4541
  0.0423 |   0.2120 |   0.1225
 -0.0437 |   0.0185 |  -0.0353
  2.3822 |   2.1908 |   2.4821
 -0.6596 |  -0.6640 |  -0.5034
 -3.5008 |  -3.5127 |  -3.7470
  1.6946 |   1.6432 |   1.6080
 -0.4791 |  -1.0352 |  -0.8828
 -7.6661 |  -6.9776 |  -6.7119
 -0.8695 |  -1.6926 |  -1.8929
 -3.5768 |  -3.0292 |  -3.0005
  1.0912 |   0.7228 |  -0.1199
  4.4466 |   4.5943 |   5.3442
 -1.5589 |  -1.6910 |  -2.5004
  9.1514 |   9.6523 |  10.4633
  1.5344 |   0.6773 |   0.3549
 -2.8008 |  -2.7846 |  -3.0110
  1.3539 |   1.7080 |   1.2172
 -3.7193 |  -3.8221 |  -3.3396

Any idea about why this is happening?

**Comment by dogancan** [comment]
These small differences are likely due to dithering, i.e. some small random noise added to your input audio prior to feature extraction. Try setting `mfcc_opts.frame_opts.dither = 0.0` and see if that helps. Note that I am not recommending disabling dithering, because in general it is a good thing to do.

**Comment by ldeseynes** [comment]
It definitely helps, thanks !
