### ISSUE TITLE
【Question】Get cuArray from pytorch or cupy

### ISSUE THREAD

**Issue by kamo-naoyuki** [pykaldi/pykaldi#73]
Can I convert `kaldi::cuArray` <-> any python CUDA-library such as `pytorch` or `cupy` directly without transferring to CPU? I'm interesting to glue `chain` with such framework.

**Comment by danpovey** [comment]
I am considering a rewrite of the matrix/cudamatrix stuff, and the neural net training stuff, to be more similar conceptually to how other neural network toolkits do it.
But it would still not be that easy to combine with PyTorch at the C++ level, most likely, for complex reasons including memory management models. 

 I have strongly considered integrating Kaldi more deeply with PyTorch, but the thing holding me back is that PyTorch seems to be in a rather disorganized and undocumented state, at the C++ level.  (Actually with TensorFlow it was the same issue, except TensorFlow's Python code was also pretty horrendous, and its overall design model was much more complex).
