### ISSUE TITLE
installation error.

### ISSUE THREAD

**Issue by prows12** [pykaldi/pykaldi#81]
I try to install pykaldi on my server.
It seems that "python setup.py install" process is going well.
But after I typing it "python setup.py test"
The error message like below appear.
How can I fix this error?

===============================================================

ImportError while importing test module '/data1/jongin/after_2018/PH_D/STT_TTS/KALDI_TECHMANUAL_backup/pykaldi/tests/base/kaldi-math-test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/base/kaldi-math-test.py:1: in <module>
    from kaldi.base import math as kaldi_math
kaldi/__init__.py:14: in <module>
    from . import base
kaldi/base/__init__.py:1: in <module>
    from ._kaldi_error import *
E   ImportError: /data1/jongin/after_2018/PH_D/STT_TTS/KALDI_TECHMANUAL_backup/pykaldi/kaldi/base/../lib/_clif.so: undefined symbol: PyClass_Type
_____________________ ERROR collecting tests/chain/languge-model-test.py ______________________
ImportError while importing test module '/data1/jongin/after_2018/PH_D/STT_TTS/KALDI_TECHMANUAL_backup/pykaldi/tests/chain/languge-model-test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/chain/languge-model-test.py:4: in <module>
    from kaldi.base import math as kaldi_math
kaldi/__init__.py:14: in <module>
    from . import base
kaldi/base/__init__.py:1: in <module>
    from ._kaldi_error import *
E   ImportError: /data1/jongin/after_2018/PH_D/STT_TTS/KALDI_TECHMANUAL_backup/pykaldi/kaldi/base/../lib/_clif.so: undefined symbol: PyClass_Type
_____________________ ERROR collecting tests/cudamatrix/cu-device-test.py _____________________
ImportError while importing test module '/data1/jongin/after_2018/PH_D/STT_TTS/KALDI_TECHMANUAL_backup/pykaldi/tests/cudamatrix/cu-device-test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/cudamatrix/cu-device-test.py:4: in <module>
    from kaldi.base import math as kaldi_math
kaldi/__init__.py:14: in <module>
    from . import base
kaldi/base/__init__.py:1: in <module>
    from ._kaldi_error import *
E   ImportError: /data1/jongin/after_2018/PH_D/STT_TTS/KALDI_TECHMANUAL_backup/pykaldi/kaldi/base/../lib/_clif.so: undefined symbol: PyClass_Type
_____________________ ERROR collecting tests/cudamatrix/cu-matrix-test.py _____________________
ImportError while importing test module '/data1/jongin/after_2018/PH_D/STT_TTS/KALDI_TECHMANUAL_backup/pykaldi/tests/cudamatrix/cu-matrix-test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/cudamatrix/cu-matrix-test.py:1: in <module>
    from kaldi.base import math as kaldi_math
kaldi/__init__.py:14: in <module>
    from . import base
kaldi/base/__init__.py:1: in <module>
    from ._kaldi_error import *
E   ImportError: /data1/jongin/after_2018/PH_D/STT_TTS/KALDI_TECHMANUAL_backup/pykaldi/kaldi/base/../lib/_clif.so: undefined symbol: PyClass_Type
_____________________ ERROR collecting tests/cudamatrix/cu-vector-test.py _____________________
ImportError while importing test module '/data1/jongin/after_2018/PH_D/STT_TTS/KALDI_TECHMANUAL_backup/pykaldi/tests/cudamatrix/cu-vector-test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/cudamatrix/cu-vector-test.py:5: in <module>
    from kaldi.base import math as kaldi_math
kaldi/__init__.py:14: in <module>
    from . import base
kaldi/base/__init__.py:1: in <module>
    from ._kaldi_error import *
E   ImportError: /data1/jongin/after_2018/PH_D/STT_TTS/KALDI_TECHMANUAL_backup/pykaldi/kaldi/base/../lib/_clif.so: undefined symbol: PyClass_Type
_________________________ ERROR collecting tests/gmm/full-gmm-test.py _________________________
ImportError while importing test module '/data1/jongin/after_2018/PH_D/STT_TTS/KALDI_TECHMANUAL_backup/pykaldi/tests/gmm/full-gmm-test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/gmm/full-gmm-test.py:7: in <module>
    from kaldi.base import math as kaldi_math
kaldi/__init__.py:14: in <module>
    from . import base
kaldi/base/__init__.py:1: in <module>
    from ._kaldi_error import *
E   ImportError: /data1/jongin/after_2018/PH_D/STT_TTS/KALDI_TECHMANUAL_backup/pykaldi/kaldi/base/../lib/_clif.so: undefined symbol: PyClass_Type
_______________________ ERROR collecting tests/hmm/hmm-topology-test.py _______________________
ImportError while importing test module '/data1/jongin/after_2018/PH_D/STT_TTS/KALDI_TECHMANUAL_backup/pykaldi/tests/hmm/hmm-topology-test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/hmm/hmm-topology-test.py:4: in <module>
    from kaldi.base.io import istringstream, ostringstream
kaldi/__init__.py:14: in <module>
    from . import base
kaldi/base/__init__.py:1: in <module>
    from ._kaldi_error import *
E   ImportError: /data1/jongin/after_2018/PH_D/STT_TTS/KALDI_TECHMANUAL_backup/pykaldi/kaldi/base/../lib/_clif.so: undefined symbol: PyClass_Type
________________________ ERROR collecting tests/matrix/matrix-test.py _________________________
ImportError while importing test module '/data1/jongin/after_2018/PH_D/STT_TTS/KALDI_TECHMANUAL_backup/pykaldi/tests/matrix/matrix-test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/matrix/matrix-test.py:5: in <module>
    from kaldi.matrix import Matrix, SubMatrix, SubVector
kaldi/__init__.py:14: in <module>
    from . import base
kaldi/base/__init__.py:1: in <module>
    from ._kaldi_error import *
E   ImportError: /data1/jongin/after_2018/PH_D/STT_TTS/KALDI_TECHMANUAL_backup/pykaldi/kaldi/base/../lib/_clif.so: undefined symbol: PyClass_Type
________________________ ERROR collecting tests/matrix/vector-test.py _________________________
ImportError while importing test module '/data1/jongin/after_2018/PH_D/STT_TTS/KALDI_TECHMANUAL_backup/pykaldi/tests/matrix/vector-test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/matrix/vector-test.py:4: in <module>
    from kaldi.matrix import Vector, SubVector
kaldi/__init__.py:14: in <module>
    from . import base
kaldi/base/__init__.py:1: in <module>
    from ._kaldi_error import *
E   ImportError: /data1/jongin/after_2018/PH_D/STT_TTS/KALDI_TECHMANUAL_backup/pykaldi/kaldi/base/../lib/_clif.so: undefined symbol: PyClass_Type
______________________ ERROR collecting tests/nnet3/nnet-compute-test.py ______________________
ImportError while importing test module '/data1/jongin/after_2018/PH_D/STT_TTS/KALDI_TECHMANUAL_backup/pykaldi/tests/nnet3/nnet-compute-test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/nnet3/nnet-compute-test.py:6: in <module>
    from kaldi.base.io import istringstream, ostringstream
kaldi/__init__.py:14: in <module>
    from . import base
kaldi/base/__init__.py:1: in <module>
    from ._kaldi_error import *
E   ImportError: /data1/jongin/after_2018/PH_D/STT_TTS/KALDI_TECHMANUAL_backup/pykaldi/kaldi/base/../lib/_clif.so: undefined symbol: PyClass_Type
________________________ ERROR collecting tests/util/kaldi-io-test.py _________________________
ImportError while importing test module '/data1/jongin/after_2018/PH_D/STT_TTS/KALDI_TECHMANUAL_backup/pykaldi/tests/util/kaldi-io-test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/util/kaldi-io-test.py:6: in <module>
    from kaldi.util.io import *
kaldi/__init__.py:14: in <module>
    from . import base
kaldi/base/__init__.py:1: in <module>
    from ._kaldi_error import *
E   ImportError: /data1/jongin/after_2018/PH_D/STT_TTS/KALDI_TECHMANUAL_backup/pykaldi/kaldi/base/../lib/_clif.so: undefined symbol: PyClass_Type
_______________________ ERROR collecting tests/util/kaldi-table-test.py _______________________
ImportError while importing test module '/data1/jongin/after_2018/PH_D/STT_TTS/KALDI_TECHMANUAL_backup/pykaldi/tests/util/kaldi-table-test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/util/kaldi-table-test.py:1: in <module>
    from kaldi.util.table import *
kaldi/__init__.py:14: in <module>
    from . import base
kaldi/base/__init__.py:1: in <module>
    from ._kaldi_error import *
E   ImportError: /data1/jongin/after_2018/PH_D/STT_TTS/KALDI_TECHMANUAL_backup/pykaldi/kaldi/base/../lib/_clif.so: undefined symbol: PyClass_Type
____________________________ ERROR collecting tests/util/mixins.py ____________________________
ImportError while importing test module '/data1/jongin/after_2018/PH_D/STT_TTS/KALDI_TECHMANUAL_backup/pykaldi/tests/util/mixins.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/util/mixins.py:5: in <module>
    import kaldi.util
kaldi/__init__.py:14: in <module>
    from . import base
kaldi/base/__init__.py:1: in <module>
    from ._kaldi_error import *
E   ImportError: /data1/jongin/after_2018/PH_D/STT_TTS/KALDI_TECHMANUAL_backup/pykaldi/kaldi/base/../lib/_clif.so: undefined symbol: PyClass_Type
_________________________ ERROR collecting tests/util/readers-test.py _________________________
ImportError while importing test module '/data1/jongin/after_2018/PH_D/STT_TTS/KALDI_TECHMANUAL_backup/pykaldi/tests/util/readers-test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/util/readers-test.py:6: in <module>
    from kaldi.matrix import *
kaldi/__init__.py:14: in <module>
    from . import base
kaldi/base/__init__.py:1: in <module>
    from ._kaldi_error import *
E   ImportError: /data1/jongin/after_2018/PH_D/STT_TTS/KALDI_TECHMANUAL_backup/pykaldi/kaldi/base/../lib/_clif.so: undefined symbol: PyClass_Type
_________________________ ERROR collecting tests/util/writers-test.py _________________________
ImportError while importing test module '/data1/jongin/after_2018/PH_D/STT_TTS/KALDI_TECHMANUAL_backup/pykaldi/tests/util/writers-test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/util/writers-test.py:5: in <module>
    from kaldi.matrix import Vector, Matrix, SubMatrix, SubVector
kaldi/__init__.py:14: in <module>
    from . import base
kaldi/base/__init__.py:1: in <module>
    from ._kaldi_error import *
E   ImportError: /data1/jongin/after_2018/PH_D/STT_TTS/KALDI_TECHMANUAL_backup/pykaldi/kaldi/base/../lib/_clif.so: undefined symbol: PyClass_Type

**Comment by dogancan** [comment]
It seems like you built pykaldi against python 2 but you are trying to run the tests with python 3.

**Comment by dogancan** [comment]
@prows12 Did you figure out what happened? Is there anything we can help with?

**Comment by prows12** [comment]
Really Appreciate you. Works Well!! Thank you!!

**Comment by dogancan** [comment]
You're welcome.

**Comment by Tzenthin** [comment]
@prows12 Could you please tell me how to fix the error? The same error happened to me .

**Comment by giantest** [comment]
@prows how did you solve this issue? i ran into exactly the same problem while using colab and its not obvious to me how to resolve this.
