### ISSUE TITLE
Multiprocessing using the same recognizer 

### ISSUE THREAD

**Issue by Cloud299** [pykaldi/pykaldi#82]
I have a question regarding multiprocessing with pykaldi. 

I'm writing a function that takes in a .wav file as a parameter and returns the transcript. The function works well when I instantiates the recognizer _once_ and the use it to transcribe multiple .wav files _sequentially_. I then use multiprocessing Process/Pool to transcribe multiple .wav files _in parallel_. However, the function does not work and gets locked when I instantiate the recognizer _outside_ of the function. When I instantiate the recognizer _inside_ the function, it works fine; however, instantiating the recognizer takes a lot of time. I'm wondering if it'd possible to instantiate the recognizer _once_ and then use it for multiple processes ?

**Comment by dogancan** [comment]
Recognizer objects are not safe to share between processes/threads. What you can do instead is to initialize the decoding graph and model and share those between threads, so each thread constructs it’s own recognizer which is a lightweight operation. 

Let me know if that doesn’t work.

**Comment by Cloud299** [comment]
Thank you; this is working well.

**Comment by dogancan** [comment]
You can decode them as they are if you are OK with the decoding speed -- short utterances are decoded faster due to beam search. I doubt you will get a better WER if you split them into short utterances. In fact, if you are using a RNNLM for rescoring, longer utterances will likely be better since they provide more context.

**Comment by Cloud299** [comment]
`You can decode them as they are if you are OK with the decoding speed -- short utterances are decoded faster due to beam search.`

Are you saying a 60-sec .wav file can be decoded faster if it's chunked into 3 segments of 20 sec and then decoded ? 

`In fact, if you are using a RNNLM for rescoring, longer utterances will likely be better since they provide more context.`

Thank you for the insight here. This is what I suspected too.

**Comment by dogancan** [comment]
> Are you saying a 60-sec .wav file can be decoded faster if it's chunked into 3 segments of 20 sec and then decoded ?

Yes. When you are decoding, you are constructing a search graph on the fly by expanding the nodes for the previous frame using the current frame. The frontier of this search space keeps growing as more frames are added. Beam search limits this growth so decoding speed does not slow down exponentially as more frames are added, but in general, the longer the utterance, the lower the real time factor of decoding.

**Comment by dogancan** [comment]
I am closing this but feel free to reopen if you have any further issues.

**Comment by SiyuanWei** [comment]
> I have a question regarding multiprocessing with pykaldi.
> 
> I'm writing a function that takes in a .wav file as a parameter and returns the transcript. The function works well when I instantiates the recognizer _once_ and the use it to transcribe multiple .wav files _sequentially_. I then use multiprocessing Process/Pool to transcribe multiple .wav files _in parallel_. However, the function does not work and gets locked when I instantiate the recognizer _outside_ of the function. When I instantiate the recognizer _inside_ the function, it works fine; however, instantiating the recognizer takes a lot of time. I'm wondering if it'd possible to instantiate the recognizer _once_ and then use it for multiple processes ?



> I have a question regarding multiprocessing with pykaldi.
> 
> I'm writing a function that takes in a .wav file as a parameter and returns the transcript. The function works well when I instantiates the recognizer _once_ and the use it to transcribe multiple .wav files _sequentially_. I then use multiprocessing Process/Pool to transcribe multiple .wav files _in parallel_. However, the function does not work and gets locked when I instantiate the recognizer _outside_ of the function. When I instantiate the recognizer _inside_ the function, it works fine; however, instantiating the recognizer takes a lot of time. I'm wondering if it'd possible to instantiate the recognizer _once_ and then use it for multiple processes ?

Hi,  I'm working on SE training that combines pytorch model and pykaldi recognizer with multi-process. But it raised an error  as follows:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/pykaldi2/bin/ops/ops.py", line 65, in decode
    decode_out = recognizer.decode(kaldi_matrix.Matrix(loglikes.numpy()))
  File "/usr/local/lib/python3.5/dist-packages/pykaldi-0.1.2-py3.5-linux-x86_64.egg/kaldi/asr.py", line 145, in decode
    self.decoder.decode(self._make_decodable(input))
  File "/usr/local/lib/python3.5/dist-packages/pykaldi-0.1.2-py3.5-linux-x86_64.egg/kaldi/asr.py", line 411, in _make_decodable
    self.acoustic_scale)
ValueError: __init__() argument tm is not valid: Value invalidated due to capture by std::unique_ptr

could you share your multiprocess related code if that doesn't bother you?

**Comment by uday156** [comment]
Hey @Cloud299 I am also trying to run Aspire model in Multi-thread, can you guide me through the process on how to run this, it would be very helpful.
Thanks in advance

**Comment by uday156** [comment]
Hey, @dogancan I am trying to run the Aspire model in Multithread can you help with the part that you are mentioning **"initialize the decoding graph and model and share those between threads"**, thank you.
