### ISSUE TITLE
compiling error when running ./install_clif.sh, target deployment error.

### ISSUE THREAD

**Issue by cyberyu** [pykaldi/pykaldi#86]
I am on Mac OS 10.13.6, ran into the following error when compiling clif. 
My libprotoc version is 3.2.0
I used python 2.7 (switched inside anaconda 3 env)
   
Processing /Users/admin/Documents/Project/pykaldi/tools/clif
Requirement already satisfied: setuptools>=18.5 in /Users/admin/anaconda3/envs/py2/lib/python2.7/site-packages (from pyclif==0.3) (40.8.0)
Requirement already satisfied: pyparsing>=2.2.0 in /Users/admin/anaconda3/envs/py2/lib/python2.7/site-packages (from pyclif==0.3) (2.3.1)
Requirement already satisfied: protobuf>=3.2 in /Users/admin/anaconda3/envs/py2/lib/python2.7/site-packages/protobuf-3.5.0-py2.7.egg (from pyclif==0.3) (3.5.0)
Requirement already satisfied: six>=1.9 in /Users/admin/anaconda3/envs/py2/lib/python2.7/site-packages/six-1.12.0-py2.7.egg (from protobuf>=3.2->pyclif==0.3) (1.12.0)
Building wheels for collected packages: pyclif
  Building wheel for pyclif (setup.py) ... error
  Complete output from command /Users/admin/anaconda3/envs/py2/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/8j/wh144j4j5d5c_rq3nbtftnk40000gn/T/pip-req-build-tamerO/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/8j/wh144j4j5d5c_rq3nbtftnk40000gn/T/pip-wheel-d03NDw --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.6-x86_64-2.7
  creating build/lib.macosx-10.6-x86_64-2.7/clif
  copying clif/pyclif.py -> build/lib.macosx-10.6-x86_64-2.7/clif
  copying clif/__init__.py -> build/lib.macosx-10.6-x86_64-2.7/clif
  creating build/lib.macosx-10.6-x86_64-2.7/clif/protos
  copying clif/protos/__init__.py -> build/lib.macosx-10.6-x86_64-2.7/clif/protos
  copying clif/protos/ast_pb2.py -> build/lib.macosx-10.6-x86_64-2.7/clif/protos
  creating build/lib.macosx-10.6-x86_64-2.7/clif/python
  copying clif/python/py2slots.py -> build/lib.macosx-10.6-x86_64-2.7/clif/python
  copying clif/python/postproc.py -> build/lib.macosx-10.6-x86_64-2.7/clif/python
  copying clif/python/postconv_test.py -> build/lib.macosx-10.6-x86_64-2.7/clif/python
  copying clif/python/pytd_parser.py -> build/lib.macosx-10.6-x86_64-2.7/clif/python
  copying clif/python/class_test.py -> build/lib.macosx-10.6-x86_64-2.7/clif/python
  copying clif/python/py3slots.py -> build/lib.macosx-10.6-x86_64-2.7/clif/python
  copying clif/python/pyext.py -> build/lib.macosx-10.6-x86_64-2.7/clif/python
  copying clif/python/gen.py -> build/lib.macosx-10.6-x86_64-2.7/clif/python
  copying clif/python/slots.py -> build/lib.macosx-10.6-x86_64-2.7/clif/python
  copying clif/python/astutils.py -> build/lib.macosx-10.6-x86_64-2.7/clif/python
  copying clif/python/pytd_parser_test.py -> build/lib.macosx-10.6-x86_64-2.7/clif/python
  copying clif/python/__init__.py -> build/lib.macosx-10.6-x86_64-2.7/clif/python
  copying clif/python/types.py -> build/lib.macosx-10.6-x86_64-2.7/clif/python
  copying clif/python/types_test.py -> build/lib.macosx-10.6-x86_64-2.7/clif/python
  copying clif/python/slot_extractor.py -> build/lib.macosx-10.6-x86_64-2.7/clif/python
  copying clif/python/module_test.py -> build/lib.macosx-10.6-x86_64-2.7/clif/python
  copying clif/python/slots_test.py -> build/lib.macosx-10.6-x86_64-2.7/clif/python
  copying clif/python/pytd2proto_test.py -> build/lib.macosx-10.6-x86_64-2.7/clif/python
  copying clif/python/proto.py -> build/lib.macosx-10.6-x86_64-2.7/clif/python
  copying clif/python/pytd2proto.py -> build/lib.macosx-10.6-x86_64-2.7/clif/python
  copying clif/python/pyext_test.py -> build/lib.macosx-10.6-x86_64-2.7/clif/python
  copying clif/python/postproc_test.py -> build/lib.macosx-10.6-x86_64-2.7/clif/python
  copying clif/python/postconv.py -> build/lib.macosx-10.6-x86_64-2.7/clif/python
  copying clif/python/func_test.py -> build/lib.macosx-10.6-x86_64-2.7/clif/python
  creating build/lib.macosx-10.6-x86_64-2.7/clif/python/utils
  copying clif/python/utils/__init__.py -> build/lib.macosx-10.6-x86_64-2.7/clif/python/utils
  running build_ext
  building 'clif.python.utils.proto_util' extension
  creating build/temp.macosx-10.6-x86_64-2.7
  creating build/temp.macosx-10.6-x86_64-2.7/clif
  creating build/temp.macosx-10.6-x86_64-2.7/clif/python
  creating build/temp.macosx-10.6-x86_64-2.7/clif/python/utils
  gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -D_THREAD_SAFE -I/Users/admin/Documents/Project/pykaldi/tools/protobuf/include -stdlib=libc++ -I./ -I/Users/admin/anaconda3/envs/py2/include/python2.7 -c clif/python/proto_util.cc -o build/temp.macosx-10.6-x86_64-2.7/clif/python/proto_util.o -std=c++11
  clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
  error: command 'gcc' failed with exit status 1
  
 
    ----------------------------------------
Command "/Users/admin/anaconda3/envs/py2/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/8j/wh144j4j5d5c_rq3nbtftnk40000gn/T/pip-req-build-tamerO/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/8j/wh144j4j5d5c_rq3nbtftnk40000gn/T/pip-record-th0TBa/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/8j/wh144j4j5d5c_rq3nbtftnk40000gn/T/pip-req-build-tamerO/

**Comment by dogancan** [comment]
Can you try running the following before install_clif.sh?

```
export MACOSX_DEPLOYMENT_TARGET=10.13
```

**Comment by cyberyu** [comment]
> export MACOSX_DEPLOYMENT_TARGET=10.13

it worked!  Thanks for pointing me to this solution

**Comment by dogancan** [comment]
You're welcome. It seems cmake is not detecting the macOS deployment target correctly on some machines for some reason.
