### ISSUE TITLE
Bug in kaldi/util/table.py

### ISSUE THREAD

**Issue by guanlongzhao** [pykaldi/pykaldi#87]
In this [line](https://github.com/pykaldi/pykaldi/blob/master/kaldi/util/table.py#L568), the method call to `Open` in `self.Open(table_rspecifier, map_rspecifier)` should be changed to lower case (`open`). I ran into this bug when trying to use the `RandomAccessMatrixReaderMapped` class.

**Comment by dogancan** [comment]
Thanks for the report. Would you like to open a PR for the bugfix?
