### ISSUE TITLE
Extracting for-word confidence score 

### ISSUE THREAD

**Issue by Cloud299** [pykaldi/pykaldi#89]
I have a question about extracting for-word confidence score for the transcription. For example, “THE (80%) RAIN (90%) IN (95%) SPAIN (55%)  MAINLY (40%) FALLS (80%) IN (70%) A(50%) SOCK (10%)". I'd like to compute the average confidence of the transcription and am not sure how to do this.

**Comment by dogancan** [comment]
Word confidences are estimated with minimum bayes risk (MBR) decoding in Kaldi. Documentation of relevant PyKaldi module is [here](https://pykaldi.github.io/api/kaldi.lat.html?highlight=mbr#module-kaldi.lat.sausages). In general, the sequence of words in MBR decoding output is different from the words in single best lattice path, so do not assume the confidence values you get correspond to word sequences returned by PyKaldi recognizers. Also, you will have to manually map the integer word ids to word symbols using the word symbol table.

**Comment by Cloud299** [comment]
Thank you. Is there an inherent way in pykaldi to separate the transcription into sentence-length segments ? 

For example, "it's going to rain today bring your umbrella" would be "it's going to rain today. Bring your umbrella".

**Comment by dogancan** [comment]
No. In ASR applications, segmentation is usually done with speech activity detection, which happens before decoding. Speech activity detection models output roughly sentence length segments, which we call utterances, but these segments are not really grammatical units. One way of achieving what you are asking is to preserve punctuation symbols inside the lexicon and the language model, so the decoding results would already include them. Another approach would be to train a segmentation or punctuation model for post-processing raw ASR transcripts. Keep in mind that neither of these approaches are standard or trivial.
