### ISSUE TITLE
why do i get different result for computing fbank-feature between pykaldi and kaldi

### ISSUE THREAD

**Issue by liuchenbaidu** [pykaldi/pykaldi#90]
i install the pykaldi from source.
then compare the result for using pykaldi to result for using compute-fbank-feats in kaldi with test.wav
1.code(use pykaldi)
sf_bank=16000.0
m3 = SubVector(mean(s3, axis=0))
f3=fbank.compute_features(m3,sf_fbank,1.00)

feature:
13.5067  10.8341  10.0170  ...   13.6531  13.5450  13.8087
  6.6261   5.5527   8.3816  ...   10.7848  10.2027   8.7894
  7.0736   8.8376  10.0984  ...   10.7526   9.8521   8.4278
           ...               ⋱              ...            
  9.5450  10.1321  10.1961  ...    9.6800   9.4741   9.2639
  8.4494   7.7848   7.4247  ...   10.3842  10.7975   9.4761
  4.6003   4.6669   8.1002  ...   10.0861   9.9920   9.1505

2.kaldi
set sample_frq=16000.0 in fbank.conf
compute-fbank-feats --verbose=0 --config=conf/fbank.conf scp,p:testfile.scp ark,t:- |less
feature:
 13.50692 10.83265 10.02174 ...13.64816 13.54409 13.81221
  6.617604 5.457501 8.411386 ...10.66659 10.40139 8.803407
  7.078373 8.840377 10.10209 ...10.81204 9.477433 8.874421
......

**Comment by dogancan** [comment]
Differences are likely due to dithering. A small amount of noise is added to input signal during feature extraction unless you disable dithering.

**Comment by liuchenbaidu** [comment]
how to disable dithering?i find there are result of four bit accuracy using pykaldi,but it is five bit accuracy in kaldi. the data for inputing to compute is same.

**Comment by dogancan** [comment]
Note that disabling dithering is not recommended, because in general it is a good thing to do. The feature values you are getting with pykaldi look fine, you don't need to make them exactly the same as kaldi.

If you want to make sure pykaldi and kaldi are computing the exact same values, you can disable dithering temporarily as follows:
```
from kaldi.feat.fbank import FbankOptions, Fbank

fbank_opts = FbankOptions()
fbank_opts.frame_opts.dither = 0.0
fbank = Fbank(fbank_opts)

...
```

Don't forget to disable dithering in conf/fbank.conf when comparing the results.

**Comment by liuchenbaidu** [comment]
yes.i disable dithering .it looks same ,but there are four bit accuracy in pykakdi and five inkaldi.
how to set same bit accuracy in pykaldi?
the feature is computed by using pykaldi:
13.5070  10.8380  10.0226  ...   13.6435  13.5225  13.8089
  6.6303   5.5863   8.3860  ...   10.3394   9.6571   8.1814
  7.0803   8.8464  10.1025  ...   10.5134   9.6472   8.0065
           ...               ⋱              ...            
  9.5476  10.1356  10.2011  ...    9.6542   9.5790   8.6285
  8.4407   7.7623   7.4209  ...   10.3636  10.2481   9.2865
  4.5558   4.6044   8.0948  ...    9.9634   9.4418   8.6904

the featur is computed by using kaldi:
 13.50695 10.83803 10.02256  ... 13.64353 13.52246 13.80895
  6.630312 5.586283 8.385966 ... 10.33942 9.657079 8.181444
  7.080257 8.846398 10.10247 ....10.51338 9.647183 8.00655
...
9.547586 10.13565 10.2011... 9.654152 9.578995 8.628512
8.440698 7.762303 7.420899 ... 10.36358 10.24814 9.286518
 4.55583 4.604392 8.094827... 9.963384 9.441837 8.690407

**Comment by dogancan** [comment]
By default floating point values in pykaldi matrices are printed with 4 significant digits. You can use [kaldi.matrix.set_printoptions](https://pykaldi.github.io/api/kaldi.matrix.html?highlight=set_print#kaldi.matrix.set_printoptions) function to change the number of significant digits printed. Note that this only affects how these matrices are printed. The underlying floating point numbers are already the same.

**Comment by liuchenbaidu** [comment]
yes.
