### ISSUE TITLE
Is paste-feats of kaldi realized in pykaldi?

### ISSUE THREAD

**Issue by liuchenbaidu** [pykaldi/pykaldi#91]
Is paste-feats of kaldi realized in pykaldi?

**Comment by dogancan** [comment]
No. There is no function in pykaldi that does the same thing as kaldi paste-feats binary.

**Comment by liuchenbaidu** [comment]
how to contact two features in pykaldi?

**Comment by dogancan** [comment]
I'm guessing you are trying to append two feature matrices. Say you have matrices A of size 5x3 and B of size 5x4. Allocate a new matrix C of size 5x7, and then copy A and B into C.

```python
from kaldi.matrix import Matrix, SubMatrix

A = Matrix(5,3)
B = Matrix(5,4)
C = Matrix(5,7)
C[:,0:3] = A
C[:,3:] = B
```

**Comment by liuchenbaidu** [comment]
yes,you solve my problem.

**Comment by liuchenbaidu** [comment]
there is more question.how to apply-cmvn in pykaldio

**Comment by liuchenbaidu** [comment]
there is more question.how to apply-cmvn in pykaldio?
