### ISSUE TITLE
it gives error when i use Cmvn.applpy_cmvn() function?

### ISSUE THREAD

**Issue by liuchenbaidu** [pykaldi/pykaldi#92]
# C is a kaldi matrix 124*83

from kaldi.transform import cmvn
from kaldi.matrix import DoubleMatrix

ki=Input("cmvn.ark")
cmvn_stats=DoubleMatrix()
cmvn_data=cmvn_stats.read_(ki.stream(),True)

from kaldi.transform.cmvn import Cmvn
cmvn=Cmvn(83)
cmvn.apply(C)

the error is :
/transform/cmvn.pyc in apply(self, feats, norm_vars, reverse)
     86             _cmvn.apply_cmvn_reverse(self.stats, norm_vars, feats)
     87         else:
---> 88             _cmvn.apply_cmvn(self.stats, norm_vars, feats)
     89 
     90     def init(self, dim):

RuntimeError: C++ exception:

**Comment by liuchenbaidu** [comment]
C

> # C is a kaldi matrix 124*83
> from kaldi.transform import cmvn
> from kaldi.matrix import DoubleMatrix
> 
> ki=Input("cmvn.ark")
> cmvn_stats=DoubleMatrix()
> cmvn_data=cmvn_stats.read_(ki.stream(),True)
> 
> from kaldi.transform.cmvn import Cmvn
> cmvn=Cmvn(83)
> cmvn.apply(C)
> 
> the error is :
> /transform/cmvn.pyc in apply(self, feats, norm_vars, reverse)
> 86 _cmvn.apply_cmvn_reverse(self.stats, norm_vars, feats)
> 87 else:
> ---> 88 _cmvn.apply_cmvn(self.stats, norm_vars, feats)
> 89
> 90 def init(self, dim):
> 
> RuntimeError: C++ exception:

**Comment by dogancan** [comment]
Assuming you are trying to do global CMVN, what you need is something like the following.

```python
from kaldi.transform.cmvn import Cmvn

cmvn = Cmvn(83)
cmvn.read_stats("global_cmvn.stats")
cmvn.apply(C)
```

Note that `global_cmvn.stats` is the global CMVN stats matrix. If you have CMVN stats saved as an archive, you can create this matrix using matrix-sum binary, e.g.

```
matrix-sum scp:data/cmvn.scp global_cmvn.stats
```

**Comment by liuchenbaidu** [comment]
i get the cmvn.ark from using "compute-cmvn-stats scp:data/${train_set}/feats.scp data/${train_set}/cmvn.ark" in kaldi.

so how to use the cmvn.ark in pykaldi?

**Comment by dogancan** [comment]
matrix-sum ark:cmvn.ark global_cmvn.stats

Then you read it with pykaldi as in the previous comment.
