### ISSUE TITLE
why do i get result for computing pitch feature between pykaldi and kaldi

### ISSUE THREAD

**Issue by liuchenbaidu** [pykaldi/pykaldi#93]
in pykaldi:
from kaldi.feat.pitch import PitchExtractionOptions,ProcessPitchOptions
from kaldi.feat.pitch import *
pitch_opts = PitchExtractionOptions()
pitch_opts.samp_freq=16000.0

feat_pitch=compute_kaldi_pitch(pitch_opts,m3)
processpitchoptions=ProcessPitchOptions()
f_pitch=process_pitch(processpitchoptions,feat_pitch)
the f_pitch is ：
-0.00033 -0.32365 -0.00476
-0.04422 -0.35449 -0.11915
-0.11965 -0.38455 -0.02502
-0.05340 -0.41164 0.00838
-0.38813 -0.41300 0.00322
-0.81145 -0.41330 -0.04063
-0.79117 -0.42419 -0.19170

in kaldi:
compute-kaldi-pitch-feats --verbose=2 --config=conf/pitch.conf scp,p:data/test_feat/wav.scp ark:-|process-kaldi-pitch-feats ark:- ark,t:-|less
the feature is 
-0.0003298404 -0.3236485 -0.07312001
  -0.04421688 -0.3544893 -0.06932247
  -0.119647 -0.3845539 -0.07284087
  -0.05339557 -0.411644 -0.04142658
  -0.3881297 -0.413003 -0.105396
  -0.8114476 -0.4132967 -0.08682314
  -0.7911729 -0.4241915 -0.1605325
 
why the last column is different?

**Comment by dogancan** [comment]
Last column is delta-pitch. Pitch post-processing algorithm adds a small amount of noise to delta-pitch to get rid of peaks caused by discretization of pitch values. Don't worry about it :)
