### ISSUE TITLE
why do i get different result for using between pykaldi and kaldi ?

### ISSUE THREAD

**Issue by liuchenbaidu** [pykaldi/pykaldi#94]
in kaldi:
fbank_feats="ark:extract-segments scp,p:$scp $logdir/segments.JOB ark:- | compute-fbank-feats $vtln_opts --verbose=2 --config=$fbank_config ark:- ark:- |"
 pitch_feats="ark,s,cs:extract-segments scp,p:$scp $logdir/segments.JOB ark:- | compute-kaldi-pitch-feats --verbose=2 --config=$pitch_config ark:- ark:- | process-kaldi-pitch-feats $postprocess_config_opt ark:- ark:- |"

paste-feats --length-tolerance=2 "$fbank_feats" "$pitch_feats" ark:- \| \
copy-feats --compress=true ark:- 
the feature: 
13.50576 10.83621 9.965789 ..... 13.80684 -0.001209596 -0.3213239 -0.07236693
  6.616467 5.593127 8.383032 .... 8.152615 -0.04414535 -0.3560306 -0.06883704
  7.116504 8.865319 10.10968 .... 8.034686 -0.1211404 -0.3849529 -0.07236693
  9.776829 10.66149 12.8332 ........ 8.565366 -0.05270034 -0.4138751 -0.0405979

in pykaldi
I comput fbank_feature and compute pitch_feature 
C = Matrix(142,83)

C[:,:80]=fbank_feature
C[:,80:]=pitch_feature
the feature:
13.50695 10.83803 10.02256  ...  -0.00033 -0.32365 -0.00476
 6.63031  5.58628  8.38597  ...  -0.04422 -0.35449 -0.11915
 7.08026  8.84640 10.10247  ...  -0.11965 -0.38455 -0.02502
           ...               ⋱              ...            
 9.54759 10.13565 10.20110  ...   0.11433 -0.59877 -0.01303
 8.44070  7.76230  7.42090  ...   0.11261 -0.59871 -0.06711
 4.55583  4.60439  8.09483  ...   0.07534 -0.59865 -0.05840

**Comment by dogancan** [comment]
I can think of at least three reasons: dithering, random noise added to delta-pitch features and feature compression. I don't think you need to worry about these differences as long as feature values are generally similar.

**Comment by liuchenbaidu** [comment]
how to disable random noise to delta-pitch?
if i should get the same result,what should i do?

**Comment by dogancan** [comment]
You can set [ProcessPitchOptions.delta_pitch_noise_stddev](https://pykaldi.github.io/api/kaldi.feat.html?highlight=pitch#kaldi.feat.pitch.ProcessPitchOptions.delta_pitch_noise_stddev) to zero to disable the delta-pitch noise. Note that setting this option to zero is not recommended. I don't understand why you are trying to exactly match the feature values. Small differences in acoustic features should result in insignificant changes in results.

**Comment by liuchenbaidu** [comment]
ths.I don't know how much difference is acceptable. What do you judge by?

**Comment by liuchenbaidu** [comment]
What is the difference standard?

**Comment by dogancan** [comment]
All of the differences due to feature compression, dithering or random noise added to features are acceptable. There is no standard tolerance that you can apply to all kinds of features. Basically, if the features look similar, e.g. the differences between the features are much smaller than the feature values themselves, then you are good. You can stop worrying whether feature values you get from pykaldi are similar to kaldi. The differences you will find between them will almost always be due to random noise or compression.

**Comment by liuchenbaidu** [comment]
ok.
