### ISSUE TITLE
there is a problem in installing from source  build PyKaldi using a different Kaldi installation

### ISSUE THREAD

**Issue by liuchenbaidu** [pykaldi/pykaldi#95]
i run ./install_protobuf.sh in directory of tools
Protobuf found in PATH.
Checking Protobuf version...
Protobuf version: 3.6.1
Protobuf version is compatible.
Checking Protobuf Python package...
Protobuf Python package version: 3.5.1
Protobuf Python package version is compatible.
Done installing Protobuf.

then ,i run ./install_clif.sh
it print out these:
.Package protobuf was not found in the pkg-config search path.
Perhaps you should add the directory containing `protobuf.pc'
to the PKG_CONFIG_PATH environment variable
No package 'protobuf' found

**Comment by dogancan** [comment]
It seems like you have a system wide protobuf installation. If you add the directory protobuf is installed on your system to PKG_CONFIG_PATH, install_clif.sh script should pick it up.

```
export PKG_CONFIG_PATH="/path/to/protobuf:$PKG_CONFIG_PATH"
```

**Comment by liuchenbaidu** [comment]
i use "which protc" ,it gives /usr/local/bin,i don' t find the directory of protobuf

**Comment by liuchenbaidu** [comment]
i watch the install_protobuf.sh 
if which protoc >/dev/null; then
    echo "Protobuf found in PATH."
    if check_protoc_version $(which protoc); then
        if check_protobuf_python_package; then
            echo "Done installing Protobuf."
           # exit 0
        fi
    fi
fi

**Comment by dogancan** [comment]
Yes, install_protobuf.sh is not installing anything because you already have a system wide protobuf installation.

**Comment by dogancan** [comment]
See if you can find protobuf.pc on your system. If you can, add that directory to PKG_CONFIG_PATH.

**Comment by dogancan** [comment]
I recommend activating a new python virtual environment, commenting out [these lines](https://github.com/pykaldi/pykaldi/blob/master/tools/install_protobuf.sh#L61-L70) and rerunning install_protobuf.sh which will install protobuf locally inside the tools directory and add the python package to the new python virtual environment.

**Comment by liuchenbaidu** [comment]
the above i just run a virtual environment that install protobuf=3.6.1,so i don't know the cause.

**Comment by dogancan** [comment]
I don't follow what you are saying. Did you try creating a new virtual environment, commenting out those lines and rerunning install_protobuf.sh?

**Comment by liuchenbaidu** [comment]
i run the virtual environment that is installed protobuf(version 3.6.1)

**Comment by liuchenbaidu** [comment]
with runing  install_protobuf.sh the virtual environment that is installed protobuf(version 3.6.1)
it gives prompt: 
Protobuf found in PATH.
Checking Protobuf version...
Protobuf version: 3.6.1
Protobuf version is compatible.
Checking Protobuf Python package...
Protobuf Python package version: 3.5.1
Protobuf Python package version is compatible.
Done installing Protobuf.

then i run install_clif.sh in the virtual environment.
it gives prompt:
.Package protobuf was not found in the pkg-config search path.
Perhaps you should add the directory containing `protobuf.pc'
to the PKG_CONFIG_PATH environment variable
No package 'protobuf' found

**Comment by dogancan** [comment]
Did you solve your installation problem?

**Comment by liuchenbaidu** [comment]
yes.i have solve the problem for creating a new virtual environment.
