### ISSUE TITLE
there is a problem in building PyKaldi using a different Kaldi installation.

### ISSUE THREAD

**Issue by liuchenbaidu** [pykaldi/pykaldi#96]
i have installed kaldi.then export KALDI_DIR=path to KALDI_DIR
with running "python setup.py install" it give propmt.

Kaldi installation at /wiki/victorliu/espnet03/espnet/tools/kaldi is not supported.
Please update Kaldi to match https://github.com/pykaldi/kaldi/tree/pykaldi.

**Comment by dogancan** [comment]
How did you install Kaldi? PyKaldi does not support upstream Kaldi. You need to install [our fork of Kaldi](https://github.com/pykaldi/kaldi/tree/pykaldi). The simplest is to use the install_kaldi.sh script which will install the latest compatible version.

**Comment by liuchenbaidu** [comment]
in install_kaldi.sh
KALDI_GIT="-b pykaldi https://github.com/pykaldi/kaldi.git"

KALDI_DIR="$PWD/kaldi"

if [ ! -d "$KALDI_DIR" ]; then
  git clone $KALDI_GIT $KALDI_DIR
else
  echo "$KALDI_DIR already exists!"  does add exit 1 in the line because i have installed the kaldi.
fi

**Comment by dogancan** [comment]
I don't follow what you are saying.

**Comment by liuchenbaidu** [comment]
i run install_kaldi.sh twice.it will build kaldi twice.

**Comment by liuchenbaidu** [comment]
i run install_kaldi.sh then run python setup.py install,it give prompt.
Kaldi installation at /wiki/victorliu/espnet03/pykaldi/pykaldi/tools/kaldi is not supported.
Please update Kaldi to match https://github.com/pykaldi/kaldi/tree/pykaldi.

**Comment by dogancan** [comment]
Try removing the kaldi installation inside tools before you run install_kaldi.sh. You cannot build pykaldi against upstream kaldi, you need to build it against our fork. install_kaldi.sh script will install our fork of kaldi.

**Comment by liuchenbaidu** [comment]
i use install_kaldi.sh to install your fork of kaldi.it also give kaldi installation is not supported.

**Comment by liuchenbaidu** [comment]
i use git log to see the version of kaldi.
commit 5dc5d41bb603ba935c6244c7b32788ea90b9cee3
Author: Dogan Can <dogancanbaz@gmail.com>
Date:   Sun Feb 24 20:40:02 2019 -0800

**Comment by dogancan** [comment]
Is that path for the kaldi installation correct? Do you have KALDI_DIR environment variable defined? I don’t see any other way of you getting this error if you used the script to install kaldi.

**Comment by liuchenbaidu** [comment]
yes.the path for kaldi installation correct.i don't care the error and use python setup.py install.then it is ok.

**Comment by Manogna-Nadella** [comment]
Hi,
I am facing the similar error as this
I am trying to install pykaldi. I have followed all the installation steps mentioned in the below link
https://github.com/pykaldi/pykaldi#installation

I have successfully installed all the dependencies using the scripts under tools directory

However when i am running "python setup.py install", i am getting the following error. I also set KALDI_DIR environment variable to the path where kaldi is installed
Also, i have run all the installation steps at the same time

"Kaldi installation at /data/manogna/pykaldi/tools/kaldi is not supported.
Please update Kaldi to match https://github.com/pykaldi/kaldi/tree/pykaldi"

Any help regarding this would be appreciated

Regards,
Manogna Nadella

**Comment by shakeel608** [comment]
After following the instruction steps, I installed everything in sequence, but I also got the same error in the end 
`Please install Kaldi under the tools directory or set KALDI_DIR environment variable.`

Even though I checked the KALDI_DIR variable, it is having a correct path to the kaldi folder pykaldi?

Any help would be appreciated
