### ISSUE TITLE
does the pykaldi support python(2.7.15)?

### ISSUE THREAD

**Issue by liuchenbaidu** [pykaldi/pykaldi#97]
conda install -c pykaldi pykaldi-cpu

it gives prompt。
The following packages will be DOWNGRADED:

  libedit                           3.1.20170329-h6b74fdf_2 --> 3.1-heed3624_0
  mkl_fft                             1.0.10-py27ha843d7b_0 --> 1.0.1-py27h3010b51_0
  mkl_random                           1.0.2-py27hd81dba3_0 --> 1.0.1-py27h629b387_0
  ncurses                                    6.1-he6710b0_1 --> 6.0-h9df7e31_2
  **python                                  2.7.15-h9bab390_6 --> 2.7.14-h89e7a4a_22**
  qt                                       5.9.7-h5867ecd_1 --> 5.9.6-h52aff34_0
  readline                                   7.0-h7b6447c_5 --> 7.0-ha6073c6_4
  sqlite                                  3.26.0-h7b6447c_0 --> 3.23.1-he433501_0

**Comment by dogancan** [comment]
It does. I am not sure why conda is trying to downgrade the packages. Try installing it in a fresh environment and see if that changs anything.

**Comment by liuchenbaidu** [comment]
installing in a fresh environment of python(2.7.15) is ok. the environment is installed by kaldio of other version ant it gives the  prompt.
