### ISSUE TITLE
there is  a problem in installation of build from source

### ISSUE THREAD

**Issue by liuchenbaidu** [pykaldi/pykaldi#98]
when i run python setup.py install .it finished.
when i import kaldi in python console.it gives the error.
ImportError: No module named _kaldi_error

**Comment by liuchenbaidu** [comment]
i run python setup.py test. it finised by 100%

**Comment by liuchenbaidu** [comment]
i use git log to see the version of kaldi.

commit 5dc5d41bb603ba935c6244c7b32788ea90b9cee3
Author: Dogan Can <dogancanbaz@gmail.com>
Date:   Sun Feb 24 20:40:02 2019 -0800

    [pykaldi] Fix Mac OS compiler/linker errors.

**Comment by dogancan** [comment]
Did you run python interpreter inside pykaldi directory? If you did, that would explain why you got the import error.

**Comment by liuchenbaidu** [comment]
yes.it goes rightly.and i do nothing.
and i run inside pykaldi directory,it doesn't give error.
