### ISSUE TITLE
how to use the pykaldi to open kalid ark file?

### ISSUE THREAD

**Issue by liuchenbaidu** [pykaldi/pykaldi#99]
the kaldi ark file is feat.1.ark.
in kaldi i use copy-feat to convert the feat.1.ark to feat.1.txt.
feat.1.txt:
BAC009S0002W0122  [
  1.941577 1.333705 0.6410908 0.3233848 0.06228554 -0.1446429 -0.4746644 -0.3502442 -0.5319012 -0.5207592 -0.1474853 -0.1811469 -0.3548306 -0.2564266 -0.2310169 -0.3788362 -0.0952335 -0.1058604 -0.04991314 0.3328016 0.1508013 0.2400788 0.05162342 0.1214133 0.2470734 0.2197762 0.2384987 0.2495203 0.4025008 0.3148366 0.2924945 0.4846471 0.3110846 0.3384699 0.3715141 0.2509116 0.2478335 0.2053427 0.2039097 0.1984591 0.2203279 0.1868063 0.2021785 0.1782573 0.1574272 0.1373978 0.1325672 0.08567977 0.03116369 0.02140456 -0.01645641 -0.0594392 -0.08722168 -0.08900917 -0.04856032 -0.003119648 0.07232487 0.1595126 0.2240406 0.3060741 0.3597144 0.4300551 0.4969574 0.5562356 0.6085856 0.7008696 0.8967255 1.027229 0.9873402 0.8749954 0.7147374 0.4126551 -0.1442962 -0.5279931 -0.02880782 0.1361507 0.1161642 0.04181379 0.1251643 0.4633213 1.169465 -0.9757594 -0.3849239]
 
the question is that how do i use pykaldi to convert it to Matrix?

**Comment by dogancan** [comment]
```python
from kaldi.util.table import SequentialMatrixReader

with SequentialMatrixReader("ark:feat.1.ark") as reader:
    for key, feat in reader:
        # feat is the feature matrix
```

**Comment by JerryPeng21cuhk** [comment]
I think you should read pykaldi's document carefully and have some basic knowledge of speech before asking so many questions.

**Comment by liuchenbaidu** [comment]
maybe you like read doc,i like ask. these question is helpful for Beginner.whatever the approach you use i support.
